// WARNING: This file was generated by PrimeCodeGen. DO NOT EDIT.

package io.github.primelib.confluence4j.rest.v1.operations;

import java.util.Objects;
import java.util.function.Consumer;
import javax.annotation.processing.Generated;
import lombok.EqualsAndHashCode;
import lombok.Getter;
import lombok.Setter;
import lombok.ToString;
import lombok.experimental.Accessors;
import org.jetbrains.annotations.ApiStatus;
import org.jspecify.annotations.NonNull;

/**
 * DeleteSpaceBySpaceKeyV1
 * <p>
 * Permanently deletes a space without sending it to the trash. Note, the space will be deleted in a long running task.
 * Therefore, the space may not be deleted yet when this method has
 * returned. Clients should poll the status link that is returned in the
 * response until the task completes.
 * 
 * **[Permissions](https://confluence.atlassian.com/x/_AozKw) required**:
 * 'Admin' permission for the space.
 *
 */
@Getter
@Setter
@EqualsAndHashCode
@ToString
@Accessors(fluent = true, chain = true)
@Generated(value = "io.github.primelib.primecodegen")
public class DeleteSpaceBySpaceKeyV1OperationSpec {
    /**
     * allows to disable validation of the spec, use with care!
     */
    @ApiStatus.Experimental
    public static Boolean VALIDATION_ENABLED = true;

    /**
     * The key of the space to delete.
     *
     */
    @NonNull
    private String spaceKey;

    /**
     * Constructs a validated instance of {@link DeleteSpaceBySpaceKeyV1OperationSpec}.
     *
     * @param spec the specification to process
     */
    @ApiStatus.Internal
    public DeleteSpaceBySpaceKeyV1OperationSpec(Consumer<DeleteSpaceBySpaceKeyV1OperationSpec> spec) {
        spec.accept(this);
        if (VALIDATION_ENABLED)
            validate();
    }

    /**
     * Validates the Spec, will throw a exception if required parameters are missing
     *
     * @throws NullPointerException
     */
    public void validate() {
        Objects.requireNonNull(spaceKey, "spaceKey is a required parameter!");
    }
}
