// WARNING: This file was generated by PrimeCodeGen. DO NOT EDIT.

package io.github.primelib.confluence4j.rest.v1.operations;

import java.util.List;
import java.util.Objects;
import java.util.function.Consumer;
import javax.annotation.processing.Generated;
import lombok.EqualsAndHashCode;
import lombok.Getter;
import lombok.Setter;
import lombok.ToString;
import lombok.experimental.Accessors;
import org.jetbrains.annotations.ApiStatus;
import org.jspecify.annotations.NonNull;
import org.jspecify.annotations.Nullable;

/**
 * GetContentByIDRestrictionV1
 * <p>
 * Returns the restrictions on a piece of content.
 * 
 * **[Permissions](https://confluence.atlassian.com/x/_AozKw) required**:
 * Permission to view the content.
 *
 */
@Getter
@Setter
@EqualsAndHashCode
@ToString
@Accessors(fluent = true, chain = true)
@Generated(value = "io.github.primelib.primecodegen")
public class GetContentByIDRestrictionV1OperationSpec {
    /**
     * allows to disable validation of the spec, use with care!
     */
    @ApiStatus.Experimental
    public static Boolean VALIDATION_ENABLED = true;

    /**
     * The ID of the content to be queried for its restrictions.
     *
     */
    @NonNull
    private String id;

    /**
     * A multi-value parameter indicating which properties of the content
     * restrictions to expand. By default, the following objects are expanded:
     * `restrictions.user`, `restrictions.group`.
     * 
     * - `restrictions.user` returns the piece of content that the restrictions are
     * applied to.
     * - `restrictions.group` returns the piece of content that the restrictions are
     * applied to.
     * - `content` returns the piece of content that the restrictions are
     * applied to.
     *
     */
    @Nullable
    private List<String> expand;

    /**
     * The starting index of the users and groups in the returned restrictions.
     *
     */
    @Nullable
    private Integer start;

    /**
     * The maximum number of users and the maximum number of groups, in the
     * returned restrictions, to return per page. Note, this may be restricted
     * by fixed system limits.
     *
     */
    @Nullable
    private Integer limit;

    /**
     * Constructs a validated instance of {@link GetContentByIDRestrictionV1OperationSpec}.
     *
     * @param spec the specification to process
     */
    @ApiStatus.Internal
    public GetContentByIDRestrictionV1OperationSpec(Consumer<GetContentByIDRestrictionV1OperationSpec> spec) {
        spec.accept(this);
        if (VALIDATION_ENABLED)
            validate();
    }

    /**
     * Validates the Spec, will throw a exception if required parameters are missing
     *
     * @throws NullPointerException
     */
    public void validate() {
        Objects.requireNonNull(id, "id is a required parameter!");
    }
}
