// WARNING: This file was generated by PrimeCodeGen. DO NOT EDIT.

package io.github.primelib.confluence4j.rest.v1.operations;

import java.util.function.Consumer;
import javax.annotation.processing.Generated;
import lombok.EqualsAndHashCode;
import lombok.Getter;
import lombok.Setter;
import lombok.ToString;
import lombok.experimental.Accessors;
import org.jetbrains.annotations.ApiStatus;
import org.jspecify.annotations.Nullable;

/**
 * GetSettingsLookandfeelV1
 * <p>
 * Returns the look and feel settings for the site or a single space. This
 * includes attributes such as the color scheme, padding, and border radius.
 * 
 * The look and feel settings for a space can be inherited from the global
 * look and feel settings or provided by a theme.
 * 
 * **[Permissions](https://confluence.atlassian.com/x/_AozKw) required**:
 * None
 *
 */
@Getter
@Setter
@EqualsAndHashCode
@ToString
@Accessors(fluent = true, chain = true)
@Generated(value = "io.github.primelib.primecodegen")
public class GetSettingsLookandfeelV1OperationSpec {
    /**
     * allows to disable validation of the spec, use with care!
     */
    @ApiStatus.Experimental
    public static Boolean VALIDATION_ENABLED = true;

    /**
     * The key of the space for which the look and feel settings will be
     * returned. If this is not set, only the global look and feel settings
     * are returned.
     *
     */
    @Nullable
    private String spaceKey;

    /**
     * Constructs a validated instance of {@link GetSettingsLookandfeelV1OperationSpec}.
     *
     * @param spec the specification to process
     */
    @ApiStatus.Internal
    public GetSettingsLookandfeelV1OperationSpec(Consumer<GetSettingsLookandfeelV1OperationSpec> spec) {
        spec.accept(this);
        if (VALIDATION_ENABLED)
            validate();
    }

    /**
     * Validates the Spec, will throw a exception if required parameters are missing
     *
     * @throws NullPointerException
     */
    public void validate() {
    }
}
