// WARNING: This file was generated by PrimeCodeGen. DO NOT EDIT.

package io.github.primelib.confluence4j.rest.v1.operations;

import java.util.Objects;
import java.util.function.Consumer;
import javax.annotation.processing.Generated;
import lombok.EqualsAndHashCode;
import lombok.Getter;
import lombok.Setter;
import lombok.ToString;
import lombok.experimental.Accessors;
import org.jetbrains.annotations.ApiStatus;
import org.jspecify.annotations.NonNull;
import org.jspecify.annotations.Nullable;

/**
 * PutContentByIDRestrictionByOperationByOperationKeyUserV1
 * <p>
 * Adds a user to a content restriction. That is, grant read or update
 * permission to the user for a piece of content.
 * 
 * **[Permissions](https://confluence.atlassian.com/x/_AozKw) required**:
 * Permission to edit the content.
 *
 */
@Getter
@Setter
@EqualsAndHashCode
@ToString
@Accessors(fluent = true, chain = true)
@Generated(value = "io.github.primelib.primecodegen")
public class PutContentByIDRestrictionByOperationByOperationKeyUserV1OperationSpec {
    /**
     * allows to disable validation of the spec, use with care!
     */
    @ApiStatus.Experimental
    public static Boolean VALIDATION_ENABLED = true;

    /**
     * The ID of the content that the restriction applies to.
     *
     */
    @NonNull
    private String id;

    /**
     * The operation that the restriction applies to.
     *
     */
    @NonNull
    private String operationKey;

    /**
     * This parameter is no longer available and will be removed from the documentation soon.
     * Use `accountId` instead.
     * See the [deprecation notice](/cloud/confluence/deprecation-notice-user-privacy-api-migration-guide/) for details.
     *
    * @deprecated
     */
    @Nullable
    @Deprecated
    private String key;

    /**
     * This parameter is no longer available and will be removed from the documentation soon.
     * Use `accountId` instead.
     * See the [deprecation notice](/cloud/confluence/deprecation-notice-user-privacy-api-migration-guide/) for details.
     *
    * @deprecated
     */
    @Nullable
    @Deprecated
    private String username;

    /**
     * The account ID of the user. The accountId uniquely identifies the user across all Atlassian products.
     * For example, `384093:32b4d9w0-f6a5-3535-11a3-9c8c88d10192`.
     *
     */
    @Nullable
    private String accountId;

    /**
     * Constructs a validated instance of {@link PutContentByIDRestrictionByOperationByOperationKeyUserV1OperationSpec}.
     *
     * @param spec the specification to process
     */
    @ApiStatus.Internal
    public PutContentByIDRestrictionByOperationByOperationKeyUserV1OperationSpec(Consumer<PutContentByIDRestrictionByOperationByOperationKeyUserV1OperationSpec> spec) {
        spec.accept(this);
        if (VALIDATION_ENABLED)
            validate();
    }

    /**
     * Validates the Spec, will throw a exception if required parameters are missing
     *
     * @throws NullPointerException
     */
    public void validate() {
        Objects.requireNonNull(id, "id is a required parameter!");
        Objects.requireNonNull(operationKey, "operationKey is a required parameter!");
    }
}
