// WARNING: This file was generated by PrimeCodeGen. DO NOT EDIT.

package io.github.primelib.confluence4j.rest.v1.operations;

import java.util.List;
import java.util.Objects;
import java.util.function.Consumer;
import javax.annotation.processing.Generated;
import lombok.EqualsAndHashCode;
import lombok.Getter;
import lombok.Setter;
import lombok.ToString;
import lombok.experimental.Accessors;
import org.jetbrains.annotations.ApiStatus;
import org.jspecify.annotations.NonNull;
import org.jspecify.annotations.Nullable;

/**
 * PutContentByIDRestrictionV1
 * <p>
 * Updates restrictions for a piece of content. This removes the existing
 * restrictions and replaces them with the restrictions in the request.
 * 
 * **[Permissions](https://confluence.atlassian.com/x/_AozKw) required**:
 * Permission to edit the content.
 *
 */
@Getter
@Setter
@EqualsAndHashCode
@ToString
@Accessors(fluent = true, chain = true)
@Generated(value = "io.github.primelib.primecodegen")
public class PutContentByIDRestrictionV1OperationSpec {
    /**
     * allows to disable validation of the spec, use with care!
     */
    @ApiStatus.Experimental
    public static Boolean VALIDATION_ENABLED = true;

    /**
     * The ID of the content to update restrictions for.
     *
     */
    @NonNull
    private String id;

    /**
     * A multi-value parameter indicating which properties of the content
     * restrictions (returned in response) to expand.
     * 
     * - `restrictions.user` returns the piece of content that the restrictions are
     * applied to. Expanded by default.
     * - `restrictions.group` returns the piece of content that the restrictions are
     * applied to. Expanded by default.
     * - `content` returns the piece of content that the restrictions are
     * applied to.
     *
     */
    @Nullable
    private List<String> expand;

    /**
     * The updated restrictions for the content.
     *
     */
    @NonNull
    private Object payload;

    /**
     * Constructs a validated instance of {@link PutContentByIDRestrictionV1OperationSpec}.
     *
     * @param spec the specification to process
     */
    @ApiStatus.Internal
    public PutContentByIDRestrictionV1OperationSpec(Consumer<PutContentByIDRestrictionV1OperationSpec> spec) {
        spec.accept(this);
        if (VALIDATION_ENABLED)
            validate();
    }

    /**
     * Validates the Spec, will throw a exception if required parameters are missing
     *
     * @throws NullPointerException
     */
    public void validate() {
        Objects.requireNonNull(id, "id is a required parameter!");
        Objects.requireNonNull(payload, "payload is a required parameter!");
    }
}
