// WARNING: This file was generated by PrimeCodeGen. DO NOT EDIT.

package io.github.primelib.confluence4j.rest.v1.enums;

import com.fasterxml.jackson.annotation.JsonTypeName;
import javax.annotation.processing.Generated;

/**
 * TypeEnum675952
 *
 */
@JsonTypeName("TypeEnum675952")
@Generated(value = "io.github.primelib.primecodegen")
public enum TypeEnum675952 {
    GROUP("group"),
    ;

    private final String value;

    TypeEnum675952(String value) {
        this.value = value;
    }
}
