// WARNING: This file was generated by PrimeCodeGen. DO NOT EDIT.

package io.github.primelib.confluence4j.rest.v1.enums;

import com.fasterxml.jackson.annotation.JsonTypeName;
import javax.annotation.processing.Generated;

/**
 * TypeEnumed0C22
 *
 */
@JsonTypeName("TypeEnumed0C22")
@Generated(value = "io.github.primelib.primecodegen")
public enum TypeEnumed0C22 {
    EXISTING_PAGE("existing_page"),
    PARENT_CONTENT("parent_content"),
    PARENT_PAGE("parent_page"),
    SPACE("space"),
    ;

    private final String value;

    TypeEnumed0C22(String value) {
        this.value = value;
    }
}
