// WARNING: This file was generated by PrimeCodeGen. DO NOT EDIT.

package io.github.primelib.confluence4j.rest.v1.models;

import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;
import com.fasterxml.jackson.annotation.JsonTypeName;
import java.util.function.Consumer;
import javax.annotation.processing.Generated;
import lombok.AccessLevel;
import lombok.EqualsAndHashCode;
import lombok.Getter;
import lombok.NoArgsConstructor;
import lombok.Setter;
import lombok.ToString;
import lombok.experimental.Accessors;
import org.jetbrains.annotations.ApiStatus;

/**
 * AffectedObject
 *
 */
@Getter
@Setter
@EqualsAndHashCode
@ToString
@Accessors(fluent = true, chain = true)
@NoArgsConstructor(access = AccessLevel.PROTECTED, force = true)
@JsonTypeName("AffectedObject")
@JsonPropertyOrder({
    "name",
    "objectType"
})
@Generated(value = "io.github.primelib.primecodegen")
public class AffectedObject {

    @JsonProperty("name")
    protected String name;

    @JsonProperty("objectType")
    protected String objectType;

    /**
     * Constructs a validated instance of {@link AffectedObject}.
     *
     * @param spec the specification to process
     */
    public AffectedObject(Consumer<AffectedObject> spec) {
        super();
        spec.accept(this);
    }

    /**
     * Constructs a validated instance of {@link AffectedObject}.
     * <p>
     * NOTE: This constructor is not considered stable and may change if the model is updated. Consider using {@link #AffectedObject(Consumer)} instead.
     * @param name name
     * @param objectType objectType
     */
    @ApiStatus.Internal
    public AffectedObject(String name, String objectType) {
        this.name = name;
        this.objectType = objectType;
    }
}
