// WARNING: This file was generated by PrimeCodeGen. DO NOT EDIT.

package io.github.primelib.confluence4j.rest.v1.models;

import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;
import com.fasterxml.jackson.annotation.JsonTypeName;
import java.util.function.Consumer;
import javax.annotation.processing.Generated;
import lombok.AccessLevel;
import lombok.EqualsAndHashCode;
import lombok.Getter;
import lombok.NoArgsConstructor;
import lombok.Setter;
import lombok.ToString;
import lombok.experimental.Accessors;
import org.jetbrains.annotations.ApiStatus;

/**
 * AncestorsItem97Fa4E
 *
 */
@Getter
@Setter
@EqualsAndHashCode
@ToString
@Accessors(fluent = true, chain = true)
@NoArgsConstructor(access = AccessLevel.PROTECTED, force = true)
@JsonTypeName("AncestorsItem97Fa4E")
@JsonPropertyOrder({
    "id"
})
@Generated(value = "io.github.primelib.primecodegen")
public class AncestorsItem97Fa4E {

    /**
     * The `id` of the parent content.
     */
    @JsonProperty("id")
    protected Object id;

    /**
     * Constructs a validated instance of {@link AncestorsItem97Fa4E}.
     *
     * @param spec the specification to process
     */
    public AncestorsItem97Fa4E(Consumer<AncestorsItem97Fa4E> spec) {
        super();
        spec.accept(this);
    }

    /**
     * Constructs a validated instance of {@link AncestorsItem97Fa4E}.
     * <p>
     * NOTE: This constructor is not considered stable and may change if the model is updated. Consider using {@link #AncestorsItem97Fa4E(Consumer)} instead.
     * @param id The `id` of the parent content.
     */
    @ApiStatus.Internal
    public AncestorsItem97Fa4E(Object id) {
        this.id = id;
    }
}
