// WARNING: This file was generated by PrimeCodeGen. DO NOT EDIT.

package io.github.primelib.confluence4j.rest.v1.models;

import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;
import com.fasterxml.jackson.annotation.JsonTypeName;
import java.util.List;
import java.util.Map;
import java.util.function.Consumer;
import javax.annotation.processing.Generated;
import lombok.AccessLevel;
import lombok.EqualsAndHashCode;
import lombok.Getter;
import lombok.NoArgsConstructor;
import lombok.Setter;
import lombok.ToString;
import lombok.experimental.Accessors;
import org.jetbrains.annotations.ApiStatus;

/**
 * AsyncContentBody
 *
 */
@Getter
@Setter
@EqualsAndHashCode
@ToString
@Accessors(fluent = true, chain = true)
@NoArgsConstructor(access = AccessLevel.PROTECTED, force = true)
@JsonTypeName("AsyncContentBody")
@JsonPropertyOrder({
    "value",
    "representation",
    "renderTaskId",
    "error",
    "status",
    "embeddedContent",
    "webresource",
    "mediaToken",
    "Expandable",
    "Links"
})
@Generated(value = "io.github.primelib.primecodegen")
public class AsyncContentBody {

    @JsonProperty("value")
    protected String value;

    @JsonProperty("representation")
    protected String representation;

    @JsonProperty("renderTaskId")
    protected String renderTaskId;

    @JsonProperty("error")
    protected String error;

    /**
     * Rerunning is reserved for when the job is working, but there is a previous run's value in the cache. You may choose to continue polling, or use the cached value.
     */
    @JsonProperty("status")
    protected String status;

    @JsonProperty("embeddedContent")
    protected List<Map<String, Object>> embeddedContent;

    @JsonProperty("webresource")
    protected WebResourceDependencies webresource;

    @JsonProperty("mediaToken")
    protected MediaToken mediaToken;

    @JsonProperty("_expandable")
    protected Expandable9Bc16D Expandable;

    @JsonProperty("_links")
    protected Map<String, Object> Links;

    /**
     * Constructs a validated instance of {@link AsyncContentBody}.
     *
     * @param spec the specification to process
     */
    public AsyncContentBody(Consumer<AsyncContentBody> spec) {
        super();
        spec.accept(this);
    }

    /**
     * Constructs a validated instance of {@link AsyncContentBody}.
     * <p>
     * NOTE: This constructor is not considered stable and may change if the model is updated. Consider using {@link #AsyncContentBody(Consumer)} instead.
     * @param value value
     * @param representation representation
     * @param renderTaskId renderTaskId
     * @param error error
     * @param status Rerunning is reserved for when the job is working, but there is a previous run's value in the cache. You may choose to continue polling, or use the cached value.
     * @param embeddedContent embeddedContent
     * @param webresource webresource
     * @param mediaToken mediaToken
     * @param Expandable Expandable
     * @param Links Links
     */
    @ApiStatus.Internal
    public AsyncContentBody(String value, String representation, String renderTaskId, String error, String status, List<Map<String, Object>> embeddedContent, WebResourceDependencies webresource, MediaToken mediaToken, Expandable9Bc16D Expandable, Map<String, Object> Links) {
        this.value = value;
        this.representation = representation;
        this.renderTaskId = renderTaskId;
        this.error = error;
        this.status = status;
        this.embeddedContent = embeddedContent;
        this.webresource = webresource;
        this.mediaToken = mediaToken;
        this.Expandable = Expandable;
        this.Links = Links;
    }
}
