// WARNING: This file was generated by PrimeCodeGen. DO NOT EDIT.

package io.github.primelib.confluence4j.rest.v1.models;

import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;
import com.fasterxml.jackson.annotation.JsonTypeName;
import java.util.List;
import java.util.Map;
import java.util.Objects;
import java.util.function.Consumer;
import javax.annotation.processing.Generated;
import org.jetbrains.annotations.ApiStatus;

/**
 * AsyncContentBody
 *
 */
@JsonTypeName("AsyncContentBody")
@JsonPropertyOrder({
    "value",
    "representation",
    "renderTaskId",
    "error",
    "status",
    "embeddedContent",
    "webresource",
    "mediaToken",
    "additionalExpandable",
    "additionalLinks"
})
@Generated(value = "io.github.primelib.primecodegen")
public class AsyncContentBody {

    @JsonProperty("value")
    protected String value;

    @JsonProperty("representation")
    protected String representation;

    @JsonProperty("renderTaskId")
    protected String renderTaskId;

    @JsonProperty("error")
    protected String error;

    /**
     * Rerunning is reserved for when the job is working, but there is a previous run's value in the cache. You may choose to continue polling, or use the cached value.
     */
    @JsonProperty("status")
    protected String status;

    @JsonProperty("embeddedContent")
    protected List<Map<String, Object>> embeddedContent;

    @JsonProperty("webresource")
    protected WebResourceDependencies webresource;

    @JsonProperty("mediaToken")
    protected MediaToken mediaToken;

    @JsonProperty("_expandable")
    protected Expandable9Bc16D additionalExpandable;

    @JsonProperty("_links")
    protected Map<String, Object> additionalLinks;

    /**
     * Constructs a validated instance of {@link AsyncContentBody}.
     *
     * @param spec the specification to process
     */
    public AsyncContentBody(Consumer<AsyncContentBody> spec) {
        super();
        spec.accept(this);
    }

    /**
     * Protected no-args constructor for use by serialization frameworks.
     */
    @ApiStatus.Internal
    protected AsyncContentBody() {
    }

    /**
     * Constructs a validated instance of {@link AsyncContentBody}.
     * <p>
     * NOTE: This constructor is not considered stable and may change if the model is updated. Consider using {@link #AsyncContentBody(Consumer)} instead.
     * @param value value
     * @param representation representation
     * @param renderTaskId renderTaskId
     * @param error error
     * @param status Rerunning is reserved for when the job is working, but there is a previous run's value in the cache. You may choose to continue polling, or use the cached value.
     * @param embeddedContent embeddedContent
     * @param webresource webresource
     * @param mediaToken mediaToken
     * @param additionalExpandable additionalExpandable
     * @param additionalLinks additionalLinks
     */
    @ApiStatus.Internal
    public AsyncContentBody(String value, String representation, String renderTaskId, String error, String status, List<Map<String, Object>> embeddedContent, WebResourceDependencies webresource, MediaToken mediaToken, Expandable9Bc16D additionalExpandable, Map<String, Object> additionalLinks) {
        this.value = value;
        this.representation = representation;
        this.renderTaskId = renderTaskId;
        this.error = error;
        this.status = status;
        this.embeddedContent = embeddedContent;
        this.webresource = webresource;
        this.mediaToken = mediaToken;
        this.additionalExpandable = additionalExpandable;
        this.additionalLinks = additionalLinks;
    }


    /**
     * Fluent getter for value.
     *
     * @return value
     */
    public String value() {
        return this.value;
    }

    /**
     * Fluent setter for value.
     *
     * @param value value
     * @return this
     */
    public AsyncContentBody value(String value) {
        this.value = value;
        return this;
    }

    /**
     * Gets the value of value.
     *
     * @return value
     */
    @JsonProperty("value")
    public String getValue() {
        return this.value;
    }

    /**
     * Sets the value of value.
     *
     * @param value value
     */
    public void setValue(String value) {
        this.value = value;
    }
    /**
     * Fluent getter for representation.
     *
     * @return representation
     */
    public String representation() {
        return this.representation;
    }

    /**
     * Fluent setter for representation.
     *
     * @param representation representation
     * @return this
     */
    public AsyncContentBody representation(String representation) {
        this.representation = representation;
        return this;
    }

    /**
     * Gets the value of representation.
     *
     * @return representation
     */
    @JsonProperty("representation")
    public String getRepresentation() {
        return this.representation;
    }

    /**
     * Sets the value of representation.
     *
     * @param representation representation
     */
    public void setRepresentation(String representation) {
        this.representation = representation;
    }
    /**
     * Fluent getter for renderTaskId.
     *
     * @return renderTaskId
     */
    public String renderTaskId() {
        return this.renderTaskId;
    }

    /**
     * Fluent setter for renderTaskId.
     *
     * @param renderTaskId renderTaskId
     * @return this
     */
    public AsyncContentBody renderTaskId(String renderTaskId) {
        this.renderTaskId = renderTaskId;
        return this;
    }

    /**
     * Gets the value of renderTaskId.
     *
     * @return renderTaskId
     */
    @JsonProperty("renderTaskId")
    public String getRenderTaskId() {
        return this.renderTaskId;
    }

    /**
     * Sets the value of renderTaskId.
     *
     * @param renderTaskId renderTaskId
     */
    public void setRenderTaskId(String renderTaskId) {
        this.renderTaskId = renderTaskId;
    }
    /**
     * Fluent getter for error.
     *
     * @return error
     */
    public String error() {
        return this.error;
    }

    /**
     * Fluent setter for error.
     *
     * @param error error
     * @return this
     */
    public AsyncContentBody error(String error) {
        this.error = error;
        return this;
    }

    /**
     * Gets the value of error.
     *
     * @return error
     */
    @JsonProperty("error")
    public String getError() {
        return this.error;
    }

    /**
     * Sets the value of error.
     *
     * @param error error
     */
    public void setError(String error) {
        this.error = error;
    }
    /**
     * Fluent getter for status.
     * <p>
     * Rerunning is reserved for when the job is working, but there is a previous run's value in the cache. You may choose to continue polling, or use the cached value.
     *
     * @return status
     */
    public String status() {
        return this.status;
    }

    /**
     * Fluent setter for status.
     * <p>
     * Rerunning is reserved for when the job is working, but there is a previous run's value in the cache. You may choose to continue polling, or use the cached value.
     *
     * @param status status
     * @return this
     */
    public AsyncContentBody status(String status) {
        this.status = status;
        return this;
    }

    /**
     * Gets the value of status.
     * <p>
     * Rerunning is reserved for when the job is working, but there is a previous run's value in the cache. You may choose to continue polling, or use the cached value.
     *
     * @return status
     */
    @JsonProperty("status")
    public String getStatus() {
        return this.status;
    }

    /**
     * Sets the value of status.
     * <p>
     * Rerunning is reserved for when the job is working, but there is a previous run's value in the cache. You may choose to continue polling, or use the cached value.
     *
     * @param status status
     */
    public void setStatus(String status) {
        this.status = status;
    }
    /**
     * Fluent getter for embeddedContent.
     *
     * @return embeddedContent
     */
    public List<Map<String, Object>> embeddedContent() {
        return this.embeddedContent;
    }

    /**
     * Fluent setter for embeddedContent.
     *
     * @param embeddedContent embeddedContent
     * @return this
     */
    public AsyncContentBody embeddedContent(List<Map<String, Object>> embeddedContent) {
        this.embeddedContent = embeddedContent;
        return this;
    }

    /**
     * Gets the value of embeddedContent.
     *
     * @return embeddedContent
     */
    @JsonProperty("embeddedContent")
    public List<Map<String, Object>> getEmbeddedContent() {
        return this.embeddedContent;
    }

    /**
     * Sets the value of embeddedContent.
     *
     * @param embeddedContent embeddedContent
     */
    public void setEmbeddedContent(List<Map<String, Object>> embeddedContent) {
        this.embeddedContent = embeddedContent;
    }
    /**
     * Fluent getter for webresource.
     *
     * @return webresource
     */
    public WebResourceDependencies webresource() {
        return this.webresource;
    }

    /**
     * Fluent setter for webresource.
     *
     * @param webresource webresource
     * @return this
     */
    public AsyncContentBody webresource(WebResourceDependencies webresource) {
        this.webresource = webresource;
        return this;
    }

    /**
     * Gets the value of webresource.
     *
     * @return webresource
     */
    @JsonProperty("webresource")
    public WebResourceDependencies getWebresource() {
        return this.webresource;
    }

    /**
     * Sets the value of webresource.
     *
     * @param webresource webresource
     */
    public void setWebresource(WebResourceDependencies webresource) {
        this.webresource = webresource;
    }
    /**
     * Fluent getter for mediaToken.
     *
     * @return mediaToken
     */
    public MediaToken mediaToken() {
        return this.mediaToken;
    }

    /**
     * Fluent setter for mediaToken.
     *
     * @param mediaToken mediaToken
     * @return this
     */
    public AsyncContentBody mediaToken(MediaToken mediaToken) {
        this.mediaToken = mediaToken;
        return this;
    }

    /**
     * Gets the value of mediaToken.
     *
     * @return mediaToken
     */
    @JsonProperty("mediaToken")
    public MediaToken getMediaToken() {
        return this.mediaToken;
    }

    /**
     * Sets the value of mediaToken.
     *
     * @param mediaToken mediaToken
     */
    public void setMediaToken(MediaToken mediaToken) {
        this.mediaToken = mediaToken;
    }
    /**
     * Fluent getter for additionalExpandable.
     *
     * @return additionalExpandable
     */
    public Expandable9Bc16D additionalExpandable() {
        return this.additionalExpandable;
    }

    /**
     * Fluent setter for additionalExpandable.
     *
     * @param additionalExpandable additionalExpandable
     * @return this
     */
    public AsyncContentBody additionalExpandable(Expandable9Bc16D additionalExpandable) {
        this.additionalExpandable = additionalExpandable;
        return this;
    }

    /**
     * Gets the value of additionalExpandable.
     *
     * @return additionalExpandable
     */
    @JsonProperty("_expandable")
    public Expandable9Bc16D getAdditionalExpandable() {
        return this.additionalExpandable;
    }

    /**
     * Sets the value of additionalExpandable.
     *
     * @param additionalExpandable additionalExpandable
     */
    public void setAdditionalExpandable(Expandable9Bc16D additionalExpandable) {
        this.additionalExpandable = additionalExpandable;
    }
    /**
     * Fluent getter for additionalLinks.
     *
     * @return additionalLinks
     */
    public Map<String, Object> additionalLinks() {
        return this.additionalLinks;
    }

    /**
     * Fluent setter for additionalLinks.
     *
     * @param additionalLinks additionalLinks
     * @return this
     */
    public AsyncContentBody additionalLinks(Map<String, Object> additionalLinks) {
        this.additionalLinks = additionalLinks;
        return this;
    }

    /**
     * Gets the value of additionalLinks.
     *
     * @return additionalLinks
     */
    @JsonProperty("_links")
    public Map<String, Object> getAdditionalLinks() {
        return this.additionalLinks;
    }

    /**
     * Sets the value of additionalLinks.
     *
     * @param additionalLinks additionalLinks
     */
    public void setAdditionalLinks(Map<String, Object> additionalLinks) {
        this.additionalLinks = additionalLinks;
    }

    @Override
    public boolean equals(Object o) {
        if (this == o) return true;
        if (o == null || getClass() != o.getClass()) return false;
        AsyncContentBody that = (AsyncContentBody) o;
        return
            Objects.equals(this.value, that.value) &&
            Objects.equals(this.representation, that.representation) &&
            Objects.equals(this.renderTaskId, that.renderTaskId) &&
            Objects.equals(this.error, that.error) &&
            Objects.equals(this.status, that.status) &&
            Objects.equals(this.embeddedContent, that.embeddedContent) &&
            Objects.equals(this.webresource, that.webresource) &&
            Objects.equals(this.mediaToken, that.mediaToken) &&
            Objects.equals(this.additionalExpandable, that.additionalExpandable) &&
            Objects.equals(this.additionalLinks, that.additionalLinks);
    }

    @Override
    public int hashCode() {
        return Objects.hash(
            this.value, 
            this.representation, 
            this.renderTaskId, 
            this.error, 
            this.status, 
            this.embeddedContent, 
            this.webresource, 
            this.mediaToken, 
            this.additionalExpandable, 
            this.additionalLinks
        );
    }

    @Override
    public String toString() {
        return "AsyncContentBody{" +
            "value=" + value + ", " + 
            "representation=" + representation + ", " + 
            "renderTaskId=" + renderTaskId + ", " + 
            "error=" + error + ", " + 
            "status=" + status + ", " + 
            "embeddedContent=" + embeddedContent + ", " + 
            "webresource=" + webresource + ", " + 
            "mediaToken=" + mediaToken + ", " + 
            "additionalExpandable=" + additionalExpandable + ", " + 
            "additionalLinks=" + additionalLinks +
            "}";
    }
}
