// WARNING: This file was generated by PrimeCodeGen. DO NOT EDIT.

package io.github.primelib.confluence4j.rest.v1.models;

import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;
import com.fasterxml.jackson.annotation.JsonTypeName;
import java.util.Map;
import java.util.function.Consumer;
import javax.annotation.processing.Generated;
import lombok.AccessLevel;
import lombok.EqualsAndHashCode;
import lombok.Getter;
import lombok.NoArgsConstructor;
import lombok.Setter;
import lombok.ToString;
import lombok.experimental.Accessors;
import org.jetbrains.annotations.ApiStatus;

/**
 * Body5304Ad
 * <p>
 * The body of the new content. Does not apply to attachments.
 * Only one body format should be specified as the property for
 * this object, e.g. `storage`.
 * 
 * Note, `editor2` format is used by Atlassian only. `anonymous_export_view` is
 * the same as `export_view` format but only content viewable by an anonymous
 * user is included.
 *
 */
@Getter
@Setter
@EqualsAndHashCode
@ToString
@Accessors(fluent = true, chain = true)
@NoArgsConstructor(access = AccessLevel.PROTECTED, force = true)
@JsonTypeName("Body5304Ad")
@JsonPropertyOrder({
    "view",
    "exportView",
    "styledView",
    "storage",
    "editor",
    "editor2",
    "wiki",
    "anonymousExportView",
    "plain",
    "atlasDocFormat",
    "raw"
})
@Generated(value = "io.github.primelib.primecodegen")
public class Body5304Ad {

    /**
     * This object is used when creating or updating content.
     */
    @JsonProperty("view")
    protected Map<String, Object> view;

    /**
     * This object is used when creating or updating content.
     */
    @JsonProperty("export_view")
    protected Map<String, Object> exportView;

    /**
     * This object is used when creating or updating content.
     */
    @JsonProperty("styled_view")
    protected Map<String, Object> styledView;

    /**
     * This object is used when creating or updating content.
     */
    @JsonProperty("storage")
    protected Map<String, Object> storage;

    /**
     * This object is used when creating or updating content.
     */
    @JsonProperty("editor")
    protected Map<String, Object> editor;

    /**
     * This object is used when creating or updating content.
     */
    @JsonProperty("editor2")
    protected Map<String, Object> editor2;

    /**
     * This object is used when creating or updating content.
     */
    @JsonProperty("wiki")
    protected Map<String, Object> wiki;

    /**
     * This object is used when creating or updating content.
     */
    @JsonProperty("anonymous_export_view")
    protected Map<String, Object> anonymousExportView;

    /**
     * This object is used when creating or updating content.
     */
    @JsonProperty("plain")
    protected Map<String, Object> plain;

    /**
     * This object is used when creating or updating content.
     */
    @JsonProperty("atlas_doc_format")
    protected Map<String, Object> atlasDocFormat;

    /**
     * This object is used when creating or updating content.
     */
    @JsonProperty("raw")
    protected Map<String, Object> raw;

    /**
     * Constructs a validated instance of {@link Body5304Ad}.
     *
     * @param spec the specification to process
     */
    public Body5304Ad(Consumer<Body5304Ad> spec) {
        super();
        spec.accept(this);
    }

    /**
     * Constructs a validated instance of {@link Body5304Ad}.
     * <p>
     * NOTE: This constructor is not considered stable and may change if the model is updated. Consider using {@link #Body5304Ad(Consumer)} instead.
     * @param view This object is used when creating or updating content.
     * @param exportView This object is used when creating or updating content.
     * @param styledView This object is used when creating or updating content.
     * @param storage This object is used when creating or updating content.
     * @param editor This object is used when creating or updating content.
     * @param editor2 This object is used when creating or updating content.
     * @param wiki This object is used when creating or updating content.
     * @param anonymousExportView This object is used when creating or updating content.
     * @param plain This object is used when creating or updating content.
     * @param atlasDocFormat This object is used when creating or updating content.
     * @param raw This object is used when creating or updating content.
     */
    @ApiStatus.Internal
    public Body5304Ad(Map<String, Object> view, Map<String, Object> exportView, Map<String, Object> styledView, Map<String, Object> storage, Map<String, Object> editor, Map<String, Object> editor2, Map<String, Object> wiki, Map<String, Object> anonymousExportView, Map<String, Object> plain, Map<String, Object> atlasDocFormat, Map<String, Object> raw) {
        this.view = view;
        this.exportView = exportView;
        this.styledView = styledView;
        this.storage = storage;
        this.editor = editor;
        this.editor2 = editor2;
        this.wiki = wiki;
        this.anonymousExportView = anonymousExportView;
        this.plain = plain;
        this.atlasDocFormat = atlasDocFormat;
        this.raw = raw;
    }
}
