// WARNING: This file was generated by PrimeCodeGen. DO NOT EDIT.

package io.github.primelib.confluence4j.rest.v1.models;

import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;
import com.fasterxml.jackson.annotation.JsonTypeName;
import java.util.Objects;
import java.util.function.Consumer;
import javax.annotation.processing.Generated;
import org.jetbrains.annotations.ApiStatus;

/**
 * Bodye84B79
 *
 */
@JsonTypeName("Bodye84B79")
@JsonPropertyOrder({
    "view",
    "exportView",
    "styledView",
    "storage",
    "wiki",
    "editor",
    "editor2",
    "anonymousExportView",
    "atlasDocFormat",
    "dynamic",
    "raw",
    "additionalExpandable"
})
@Generated(value = "io.github.primelib.primecodegen")
public class Bodye84B79 {

    @JsonProperty("view")
    protected ContentBody view;

    @JsonProperty("export_view")
    protected ContentBody exportView;

    @JsonProperty("styled_view")
    protected ContentBody styledView;

    @JsonProperty("storage")
    protected ContentBody storage;

    @JsonProperty("wiki")
    protected ContentBody wiki;

    @JsonProperty("editor")
    protected ContentBody editor;

    @JsonProperty("editor2")
    protected ContentBody editor2;

    @JsonProperty("anonymous_export_view")
    protected ContentBody anonymousExportView;

    @JsonProperty("atlas_doc_format")
    protected ContentBody atlasDocFormat;

    @JsonProperty("dynamic")
    protected ContentBody dynamic;

    @JsonProperty("raw")
    protected ContentBody raw;

    @JsonProperty("_expandable")
    protected Expandable7De7Ff additionalExpandable;

    /**
     * Constructs a validated instance of {@link Bodye84B79}.
     *
     * @param spec the specification to process
     */
    public Bodye84B79(Consumer<Bodye84B79> spec) {
        super();
        spec.accept(this);
    }

    /**
     * Protected no-args constructor for use by serialization frameworks.
     */
    @ApiStatus.Internal
    protected Bodye84B79() {
    }

    /**
     * Constructs a validated instance of {@link Bodye84B79}.
     * <p>
     * NOTE: This constructor is not considered stable and may change if the model is updated. Consider using {@link #Bodye84B79(Consumer)} instead.
     * @param view view
     * @param exportView exportView
     * @param styledView styledView
     * @param storage storage
     * @param wiki wiki
     * @param editor editor
     * @param editor2 editor2
     * @param anonymousExportView anonymousExportView
     * @param atlasDocFormat atlasDocFormat
     * @param dynamic dynamic
     * @param raw raw
     * @param additionalExpandable additionalExpandable
     */
    @ApiStatus.Internal
    public Bodye84B79(ContentBody view, ContentBody exportView, ContentBody styledView, ContentBody storage, ContentBody wiki, ContentBody editor, ContentBody editor2, ContentBody anonymousExportView, ContentBody atlasDocFormat, ContentBody dynamic, ContentBody raw, Expandable7De7Ff additionalExpandable) {
        this.view = view;
        this.exportView = exportView;
        this.styledView = styledView;
        this.storage = storage;
        this.wiki = wiki;
        this.editor = editor;
        this.editor2 = editor2;
        this.anonymousExportView = anonymousExportView;
        this.atlasDocFormat = atlasDocFormat;
        this.dynamic = dynamic;
        this.raw = raw;
        this.additionalExpandable = additionalExpandable;
    }


    /**
     * Fluent getter for view.
     *
     * @return view
     */
    public ContentBody view() {
        return this.view;
    }

    /**
     * Fluent setter for view.
     *
     * @param view view
     * @return this
     */
    public Bodye84B79 view(ContentBody view) {
        this.view = view;
        return this;
    }

    /**
     * Gets the value of view.
     *
     * @return view
     */
    @JsonProperty("view")
    public ContentBody getView() {
        return this.view;
    }

    /**
     * Sets the value of view.
     *
     * @param view view
     */
    public void setView(ContentBody view) {
        this.view = view;
    }
    /**
     * Fluent getter for exportView.
     *
     * @return exportView
     */
    public ContentBody exportView() {
        return this.exportView;
    }

    /**
     * Fluent setter for exportView.
     *
     * @param exportView exportView
     * @return this
     */
    public Bodye84B79 exportView(ContentBody exportView) {
        this.exportView = exportView;
        return this;
    }

    /**
     * Gets the value of exportView.
     *
     * @return exportView
     */
    @JsonProperty("export_view")
    public ContentBody getExportView() {
        return this.exportView;
    }

    /**
     * Sets the value of exportView.
     *
     * @param exportView exportView
     */
    public void setExportView(ContentBody exportView) {
        this.exportView = exportView;
    }
    /**
     * Fluent getter for styledView.
     *
     * @return styledView
     */
    public ContentBody styledView() {
        return this.styledView;
    }

    /**
     * Fluent setter for styledView.
     *
     * @param styledView styledView
     * @return this
     */
    public Bodye84B79 styledView(ContentBody styledView) {
        this.styledView = styledView;
        return this;
    }

    /**
     * Gets the value of styledView.
     *
     * @return styledView
     */
    @JsonProperty("styled_view")
    public ContentBody getStyledView() {
        return this.styledView;
    }

    /**
     * Sets the value of styledView.
     *
     * @param styledView styledView
     */
    public void setStyledView(ContentBody styledView) {
        this.styledView = styledView;
    }
    /**
     * Fluent getter for storage.
     *
     * @return storage
     */
    public ContentBody storage() {
        return this.storage;
    }

    /**
     * Fluent setter for storage.
     *
     * @param storage storage
     * @return this
     */
    public Bodye84B79 storage(ContentBody storage) {
        this.storage = storage;
        return this;
    }

    /**
     * Gets the value of storage.
     *
     * @return storage
     */
    @JsonProperty("storage")
    public ContentBody getStorage() {
        return this.storage;
    }

    /**
     * Sets the value of storage.
     *
     * @param storage storage
     */
    public void setStorage(ContentBody storage) {
        this.storage = storage;
    }
    /**
     * Fluent getter for wiki.
     *
     * @return wiki
     */
    public ContentBody wiki() {
        return this.wiki;
    }

    /**
     * Fluent setter for wiki.
     *
     * @param wiki wiki
     * @return this
     */
    public Bodye84B79 wiki(ContentBody wiki) {
        this.wiki = wiki;
        return this;
    }

    /**
     * Gets the value of wiki.
     *
     * @return wiki
     */
    @JsonProperty("wiki")
    public ContentBody getWiki() {
        return this.wiki;
    }

    /**
     * Sets the value of wiki.
     *
     * @param wiki wiki
     */
    public void setWiki(ContentBody wiki) {
        this.wiki = wiki;
    }
    /**
     * Fluent getter for editor.
     *
     * @return editor
     */
    public ContentBody editor() {
        return this.editor;
    }

    /**
     * Fluent setter for editor.
     *
     * @param editor editor
     * @return this
     */
    public Bodye84B79 editor(ContentBody editor) {
        this.editor = editor;
        return this;
    }

    /**
     * Gets the value of editor.
     *
     * @return editor
     */
    @JsonProperty("editor")
    public ContentBody getEditor() {
        return this.editor;
    }

    /**
     * Sets the value of editor.
     *
     * @param editor editor
     */
    public void setEditor(ContentBody editor) {
        this.editor = editor;
    }
    /**
     * Fluent getter for editor2.
     *
     * @return editor2
     */
    public ContentBody editor2() {
        return this.editor2;
    }

    /**
     * Fluent setter for editor2.
     *
     * @param editor2 editor2
     * @return this
     */
    public Bodye84B79 editor2(ContentBody editor2) {
        this.editor2 = editor2;
        return this;
    }

    /**
     * Gets the value of editor2.
     *
     * @return editor2
     */
    @JsonProperty("editor2")
    public ContentBody getEditor2() {
        return this.editor2;
    }

    /**
     * Sets the value of editor2.
     *
     * @param editor2 editor2
     */
    public void setEditor2(ContentBody editor2) {
        this.editor2 = editor2;
    }
    /**
     * Fluent getter for anonymousExportView.
     *
     * @return anonymousExportView
     */
    public ContentBody anonymousExportView() {
        return this.anonymousExportView;
    }

    /**
     * Fluent setter for anonymousExportView.
     *
     * @param anonymousExportView anonymousExportView
     * @return this
     */
    public Bodye84B79 anonymousExportView(ContentBody anonymousExportView) {
        this.anonymousExportView = anonymousExportView;
        return this;
    }

    /**
     * Gets the value of anonymousExportView.
     *
     * @return anonymousExportView
     */
    @JsonProperty("anonymous_export_view")
    public ContentBody getAnonymousExportView() {
        return this.anonymousExportView;
    }

    /**
     * Sets the value of anonymousExportView.
     *
     * @param anonymousExportView anonymousExportView
     */
    public void setAnonymousExportView(ContentBody anonymousExportView) {
        this.anonymousExportView = anonymousExportView;
    }
    /**
     * Fluent getter for atlasDocFormat.
     *
     * @return atlasDocFormat
     */
    public ContentBody atlasDocFormat() {
        return this.atlasDocFormat;
    }

    /**
     * Fluent setter for atlasDocFormat.
     *
     * @param atlasDocFormat atlasDocFormat
     * @return this
     */
    public Bodye84B79 atlasDocFormat(ContentBody atlasDocFormat) {
        this.atlasDocFormat = atlasDocFormat;
        return this;
    }

    /**
     * Gets the value of atlasDocFormat.
     *
     * @return atlasDocFormat
     */
    @JsonProperty("atlas_doc_format")
    public ContentBody getAtlasDocFormat() {
        return this.atlasDocFormat;
    }

    /**
     * Sets the value of atlasDocFormat.
     *
     * @param atlasDocFormat atlasDocFormat
     */
    public void setAtlasDocFormat(ContentBody atlasDocFormat) {
        this.atlasDocFormat = atlasDocFormat;
    }
    /**
     * Fluent getter for dynamic.
     *
     * @return dynamic
     */
    public ContentBody dynamic() {
        return this.dynamic;
    }

    /**
     * Fluent setter for dynamic.
     *
     * @param dynamic dynamic
     * @return this
     */
    public Bodye84B79 dynamic(ContentBody dynamic) {
        this.dynamic = dynamic;
        return this;
    }

    /**
     * Gets the value of dynamic.
     *
     * @return dynamic
     */
    @JsonProperty("dynamic")
    public ContentBody getDynamic() {
        return this.dynamic;
    }

    /**
     * Sets the value of dynamic.
     *
     * @param dynamic dynamic
     */
    public void setDynamic(ContentBody dynamic) {
        this.dynamic = dynamic;
    }
    /**
     * Fluent getter for raw.
     *
     * @return raw
     */
    public ContentBody raw() {
        return this.raw;
    }

    /**
     * Fluent setter for raw.
     *
     * @param raw raw
     * @return this
     */
    public Bodye84B79 raw(ContentBody raw) {
        this.raw = raw;
        return this;
    }

    /**
     * Gets the value of raw.
     *
     * @return raw
     */
    @JsonProperty("raw")
    public ContentBody getRaw() {
        return this.raw;
    }

    /**
     * Sets the value of raw.
     *
     * @param raw raw
     */
    public void setRaw(ContentBody raw) {
        this.raw = raw;
    }
    /**
     * Fluent getter for additionalExpandable.
     *
     * @return additionalExpandable
     */
    public Expandable7De7Ff additionalExpandable() {
        return this.additionalExpandable;
    }

    /**
     * Fluent setter for additionalExpandable.
     *
     * @param additionalExpandable additionalExpandable
     * @return this
     */
    public Bodye84B79 additionalExpandable(Expandable7De7Ff additionalExpandable) {
        this.additionalExpandable = additionalExpandable;
        return this;
    }

    /**
     * Gets the value of additionalExpandable.
     *
     * @return additionalExpandable
     */
    @JsonProperty("_expandable")
    public Expandable7De7Ff getAdditionalExpandable() {
        return this.additionalExpandable;
    }

    /**
     * Sets the value of additionalExpandable.
     *
     * @param additionalExpandable additionalExpandable
     */
    public void setAdditionalExpandable(Expandable7De7Ff additionalExpandable) {
        this.additionalExpandable = additionalExpandable;
    }

    @Override
    public boolean equals(Object o) {
        if (this == o) return true;
        if (o == null || getClass() != o.getClass()) return false;
        Bodye84B79 that = (Bodye84B79) o;
        return
            Objects.equals(this.view, that.view) &&
            Objects.equals(this.exportView, that.exportView) &&
            Objects.equals(this.styledView, that.styledView) &&
            Objects.equals(this.storage, that.storage) &&
            Objects.equals(this.wiki, that.wiki) &&
            Objects.equals(this.editor, that.editor) &&
            Objects.equals(this.editor2, that.editor2) &&
            Objects.equals(this.anonymousExportView, that.anonymousExportView) &&
            Objects.equals(this.atlasDocFormat, that.atlasDocFormat) &&
            Objects.equals(this.dynamic, that.dynamic) &&
            Objects.equals(this.raw, that.raw) &&
            Objects.equals(this.additionalExpandable, that.additionalExpandable);
    }

    @Override
    public int hashCode() {
        return Objects.hash(
            this.view, 
            this.exportView, 
            this.styledView, 
            this.storage, 
            this.wiki, 
            this.editor, 
            this.editor2, 
            this.anonymousExportView, 
            this.atlasDocFormat, 
            this.dynamic, 
            this.raw, 
            this.additionalExpandable
        );
    }

    @Override
    public String toString() {
        return "Bodye84B79{" +
            "view=" + view + ", " + 
            "exportView=" + exportView + ", " + 
            "styledView=" + styledView + ", " + 
            "storage=" + storage + ", " + 
            "wiki=" + wiki + ", " + 
            "editor=" + editor + ", " + 
            "editor2=" + editor2 + ", " + 
            "anonymousExportView=" + anonymousExportView + ", " + 
            "atlasDocFormat=" + atlasDocFormat + ", " + 
            "dynamic=" + dynamic + ", " + 
            "raw=" + raw + ", " + 
            "additionalExpandable=" + additionalExpandable +
            "}";
    }
}
