// WARNING: This file was generated by PrimeCodeGen. DO NOT EDIT.

package io.github.primelib.confluence4j.rest.v1.models;

import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;
import com.fasterxml.jackson.annotation.JsonTypeName;
import java.util.Map;
import java.util.function.Consumer;
import javax.annotation.processing.Generated;
import lombok.AccessLevel;
import lombok.EqualsAndHashCode;
import lombok.Getter;
import lombok.NoArgsConstructor;
import lombok.Setter;
import lombok.ToString;
import lombok.experimental.Accessors;
import org.jetbrains.annotations.ApiStatus;

/**
 * Comment
 *
 */
@Getter
@Setter
@EqualsAndHashCode
@ToString
@Accessors(fluent = true, chain = true)
@NoArgsConstructor(access = AccessLevel.PROTECTED, force = true)
@JsonTypeName("Comment")
@JsonPropertyOrder({
    "value",
    "Links"
})
@Generated(value = "io.github.primelib.primecodegen")
public class Comment {

    @JsonProperty("value")
    protected Boolean value;

    @JsonProperty("_links")
    protected Map<String, Object> Links;

    /**
     * Constructs a validated instance of {@link Comment}.
     *
     * @param spec the specification to process
     */
    public Comment(Consumer<Comment> spec) {
        super();
        spec.accept(this);
    }

    /**
     * Constructs a validated instance of {@link Comment}.
     * <p>
     * NOTE: This constructor is not considered stable and may change if the model is updated. Consider using {@link #Comment(Consumer)} instead.
     * @param value value
     * @param Links Links
     */
    @ApiStatus.Internal
    public Comment(Boolean value, Map<String, Object> Links) {
        this.value = value;
        this.Links = Links;
    }
}
