// WARNING: This file was generated by PrimeCodeGen. DO NOT EDIT.

package io.github.primelib.confluence4j.rest.v1.models;

import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;
import com.fasterxml.jackson.annotation.JsonTypeName;
import java.util.Map;
import java.util.function.Consumer;
import javax.annotation.processing.Generated;
import lombok.AccessLevel;
import lombok.EqualsAndHashCode;
import lombok.Getter;
import lombok.NoArgsConstructor;
import lombok.Setter;
import lombok.ToString;
import lombok.experimental.Accessors;
import org.jetbrains.annotations.ApiStatus;

/**
 * ContentChildren
 *
 */
@Getter
@Setter
@EqualsAndHashCode
@ToString
@Accessors(fluent = true, chain = true)
@NoArgsConstructor(access = AccessLevel.PROTECTED, force = true)
@JsonTypeName("ContentChildren")
@JsonPropertyOrder({
    "attachment",
    "comment",
    "page",
    "whiteboard",
    "database",
    "embed",
    "folder",
    "Expandable",
    "Links"
})
@Generated(value = "io.github.primelib.primecodegen")
public class ContentChildren {

    @JsonProperty("attachment")
    protected ContentArray attachment;

    @JsonProperty("comment")
    protected ContentArray comment;

    @JsonProperty("page")
    protected ContentArray page;

    @JsonProperty("whiteboard")
    protected ContentArray whiteboard;

    @JsonProperty("database")
    protected ContentArray database;

    @JsonProperty("embed")
    protected ContentArray embed;

    @JsonProperty("folder")
    protected ContentArray folder;

    @JsonProperty("_expandable")
    protected Map<String, Object> Expandable;

    @JsonProperty("_links")
    protected Map<String, Object> Links;

    /**
     * Constructs a validated instance of {@link ContentChildren}.
     *
     * @param spec the specification to process
     */
    public ContentChildren(Consumer<ContentChildren> spec) {
        super();
        spec.accept(this);
    }

    /**
     * Constructs a validated instance of {@link ContentChildren}.
     * <p>
     * NOTE: This constructor is not considered stable and may change if the model is updated. Consider using {@link #ContentChildren(Consumer)} instead.
     * @param attachment attachment
     * @param comment comment
     * @param page page
     * @param whiteboard whiteboard
     * @param database database
     * @param embed embed
     * @param folder folder
     * @param Expandable Expandable
     * @param Links Links
     */
    @ApiStatus.Internal
    public ContentChildren(ContentArray attachment, ContentArray comment, ContentArray page, ContentArray whiteboard, ContentArray database, ContentArray embed, ContentArray folder, Map<String, Object> Expandable, Map<String, Object> Links) {
        this.attachment = attachment;
        this.comment = comment;
        this.page = page;
        this.whiteboard = whiteboard;
        this.database = database;
        this.embed = embed;
        this.folder = folder;
        this.Expandable = Expandable;
        this.Links = Links;
    }
}
