// WARNING: This file was generated by PrimeCodeGen. DO NOT EDIT.

package io.github.primelib.confluence4j.rest.v1.models;

import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;
import com.fasterxml.jackson.annotation.JsonTypeName;
import java.util.List;
import java.util.Map;
import java.util.function.Consumer;
import javax.annotation.processing.Generated;
import lombok.AccessLevel;
import lombok.EqualsAndHashCode;
import lombok.Getter;
import lombok.NoArgsConstructor;
import lombok.Setter;
import lombok.ToString;
import lombok.experimental.Accessors;
import org.jetbrains.annotations.ApiStatus;

/**
 * ContentTemplateUpdate
 * <p>
 * This object is used to update content templates.
 *
 */
@Getter
@Setter
@EqualsAndHashCode
@ToString
@Accessors(fluent = true, chain = true)
@NoArgsConstructor(access = AccessLevel.PROTECTED, force = true)
@JsonTypeName("ContentTemplateUpdate")
@JsonPropertyOrder({
    "templateId",
    "name",
    "templateType",
    "body",
    "description",
    "labels",
    "space"
})
@Generated(value = "io.github.primelib.primecodegen")
public class ContentTemplateUpdate {

    /**
     * The ID of the template being updated.
     */
    @JsonProperty("templateId")
    protected String templateId;

    /**
     * The name of the template. Set to the current `name` if this field is
not being updated.
     */
    @JsonProperty("name")
    protected String name;

    /**
     * The type of the template. Set to `page`.
     */
    @JsonProperty("templateType")
    protected String templateType;

    /**
     * The body of the new content. Does not apply to attachments.
Only one body format should be specified as the property for
this object, e.g. `storage`.

Note, `editor2` format is used by Atlassian only. `anonymous_export_view` is
the same as `export_view` format but only content viewable by an anonymous
user is included.
     */
    @JsonProperty("body")
    protected ContentTemplateBodyCreate body;

    /**
     * A description of the template.
     */
    @JsonProperty("description")
    protected String description;

    /**
     * Labels for the template.
     */
    @JsonProperty("labels")
    protected List<Label> labels;

    /**
     * The key for the space of the template. Required if the template is a
space template. Set this to the current `space.key`.
     */
    @JsonProperty("space")
    protected Map<String, Object> space;

    /**
     * Constructs a validated instance of {@link ContentTemplateUpdate}.
     *
     * @param spec the specification to process
     */
    public ContentTemplateUpdate(Consumer<ContentTemplateUpdate> spec) {
        super();
        spec.accept(this);
    }

    /**
     * Constructs a validated instance of {@link ContentTemplateUpdate}.
     * <p>
     * NOTE: This constructor is not considered stable and may change if the model is updated. Consider using {@link #ContentTemplateUpdate(Consumer)} instead.
     * @param templateId The ID of the template being updated.
     * @param name The name of the template. Set to the current `name` if this field is
not being updated.
     * @param templateType The type of the template. Set to `page`.
     * @param body The body of the new content. Does not apply to attachments.
Only one body format should be specified as the property for
this object, e.g. `storage`.

Note, `editor2` format is used by Atlassian only. `anonymous_export_view` is
the same as `export_view` format but only content viewable by an anonymous
user is included.
     * @param description A description of the template.
     * @param labels Labels for the template.
     * @param space The key for the space of the template. Required if the template is a
space template. Set this to the current `space.key`.
     */
    @ApiStatus.Internal
    public ContentTemplateUpdate(String templateId, String name, String templateType, ContentTemplateBodyCreate body, String description, List<Label> labels, Map<String, Object> space) {
        this.templateId = templateId;
        this.name = name;
        this.templateType = templateType;
        this.body = body;
        this.description = description;
        this.labels = labels;
        this.space = space;
    }
}
