// WARNING: This file was generated by PrimeCodeGen. DO NOT EDIT.

package io.github.primelib.confluence4j.rest.v1.models;

import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;
import com.fasterxml.jackson.annotation.JsonTypeName;
import java.util.function.Consumer;
import javax.annotation.processing.Generated;
import lombok.AccessLevel;
import lombok.EqualsAndHashCode;
import lombok.Getter;
import lombok.NoArgsConstructor;
import lombok.Setter;
import lombok.ToString;
import lombok.experimental.Accessors;
import org.jetbrains.annotations.ApiStatus;

/**
 * ContentTemplateBody
 * <p>
 * The body of the new content. Does not apply to attachments.
 * Only one body format should be specified as the property for
 * this object, e.g. `storage`.
 * 
 * Note, `editor2` format is used by Atlassian only. `anonymous_export_view` is
 * the same as `export_view` format but only content viewable by an anonymous
 * user is included.
 *
 */
@Getter
@Setter
@EqualsAndHashCode
@ToString
@Accessors(fluent = true, chain = true)
@NoArgsConstructor(access = AccessLevel.PROTECTED, force = true)
@JsonTypeName("ContentTemplateBody")
@JsonPropertyOrder({
    "view",
    "exportView",
    "styledView",
    "storage",
    "editor",
    "editor2",
    "wiki",
    "atlasDocFormat",
    "anonymousExportView"
})
@Generated(value = "io.github.primelib.primecodegen")
public class ContentTemplateBody {

    @JsonProperty("view")
    protected ContentBody view;

    @JsonProperty("export_view")
    protected ContentBody exportView;

    @JsonProperty("styled_view")
    protected ContentBody styledView;

    @JsonProperty("storage")
    protected ContentBody storage;

    @JsonProperty("editor")
    protected ContentBody editor;

    @JsonProperty("editor2")
    protected ContentBody editor2;

    @JsonProperty("wiki")
    protected ContentBody wiki;

    @JsonProperty("atlas_doc_format")
    protected ContentBody atlasDocFormat;

    @JsonProperty("anonymous_export_view")
    protected ContentBody anonymousExportView;

    /**
     * Constructs a validated instance of {@link ContentTemplateBody}.
     *
     * @param spec the specification to process
     */
    public ContentTemplateBody(Consumer<ContentTemplateBody> spec) {
        super();
        spec.accept(this);
    }

    /**
     * Constructs a validated instance of {@link ContentTemplateBody}.
     * <p>
     * NOTE: This constructor is not considered stable and may change if the model is updated. Consider using {@link #ContentTemplateBody(Consumer)} instead.
     * @param view view
     * @param exportView exportView
     * @param styledView styledView
     * @param storage storage
     * @param editor editor
     * @param editor2 editor2
     * @param wiki wiki
     * @param atlasDocFormat atlasDocFormat
     * @param anonymousExportView anonymousExportView
     */
    @ApiStatus.Internal
    public ContentTemplateBody(ContentBody view, ContentBody exportView, ContentBody styledView, ContentBody storage, ContentBody editor, ContentBody editor2, ContentBody wiki, ContentBody atlasDocFormat, ContentBody anonymousExportView) {
        this.view = view;
        this.exportView = exportView;
        this.styledView = styledView;
        this.storage = storage;
        this.editor = editor;
        this.editor2 = editor2;
        this.wiki = wiki;
        this.atlasDocFormat = atlasDocFormat;
        this.anonymousExportView = anonymousExportView;
    }
}
