// WARNING: This file was generated by PrimeCodeGen. DO NOT EDIT.

package io.github.primelib.confluence4j.rest.v1.models;

import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;
import com.fasterxml.jackson.annotation.JsonTypeName;
import java.util.Map;
import java.util.Objects;
import java.util.function.Consumer;
import javax.annotation.processing.Generated;
import org.jetbrains.annotations.ApiStatus;

/**
 * ContentChildren
 *
 */
@JsonTypeName("ContentChildren")
@JsonPropertyOrder({
    "attachment",
    "comment",
    "page",
    "whiteboard",
    "database",
    "embed",
    "folder",
    "additionalExpandable",
    "additionalLinks"
})
@Generated(value = "io.github.primelib.primecodegen")
public class ContentChildren {

    @JsonProperty("attachment")
    protected ContentArray attachment;

    @JsonProperty("comment")
    protected ContentArray comment;

    @JsonProperty("page")
    protected ContentArray page;

    @JsonProperty("whiteboard")
    protected ContentArray whiteboard;

    @JsonProperty("database")
    protected ContentArray database;

    @JsonProperty("embed")
    protected ContentArray embed;

    @JsonProperty("folder")
    protected ContentArray folder;

    @JsonProperty("_expandable")
    protected Map<String, Object> additionalExpandable;

    @JsonProperty("_links")
    protected Map<String, Object> additionalLinks;

    /**
     * Constructs a validated instance of {@link ContentChildren}.
     *
     * @param spec the specification to process
     */
    public ContentChildren(Consumer<ContentChildren> spec) {
        super();
        spec.accept(this);
    }

    /**
     * Protected no-args constructor for use by serialization frameworks.
     */
    @ApiStatus.Internal
    protected ContentChildren() {
    }

    /**
     * Constructs a validated instance of {@link ContentChildren}.
     * <p>
     * NOTE: This constructor is not considered stable and may change if the model is updated. Consider using {@link #ContentChildren(Consumer)} instead.
     * @param attachment attachment
     * @param comment comment
     * @param page page
     * @param whiteboard whiteboard
     * @param database database
     * @param embed embed
     * @param folder folder
     * @param additionalExpandable additionalExpandable
     * @param additionalLinks additionalLinks
     */
    @ApiStatus.Internal
    public ContentChildren(ContentArray attachment, ContentArray comment, ContentArray page, ContentArray whiteboard, ContentArray database, ContentArray embed, ContentArray folder, Map<String, Object> additionalExpandable, Map<String, Object> additionalLinks) {
        this.attachment = attachment;
        this.comment = comment;
        this.page = page;
        this.whiteboard = whiteboard;
        this.database = database;
        this.embed = embed;
        this.folder = folder;
        this.additionalExpandable = additionalExpandable;
        this.additionalLinks = additionalLinks;
    }


    /**
     * Fluent getter for attachment.
     *
     * @return attachment
     */
    public ContentArray attachment() {
        return this.attachment;
    }

    /**
     * Fluent setter for attachment.
     *
     * @param attachment attachment
     * @return this
     */
    public ContentChildren attachment(ContentArray attachment) {
        this.attachment = attachment;
        return this;
    }

    /**
     * Gets the value of attachment.
     *
     * @return attachment
     */
    @JsonProperty("attachment")
    public ContentArray getAttachment() {
        return this.attachment;
    }

    /**
     * Sets the value of attachment.
     *
     * @param attachment attachment
     */
    public void setAttachment(ContentArray attachment) {
        this.attachment = attachment;
    }
    /**
     * Fluent getter for comment.
     *
     * @return comment
     */
    public ContentArray comment() {
        return this.comment;
    }

    /**
     * Fluent setter for comment.
     *
     * @param comment comment
     * @return this
     */
    public ContentChildren comment(ContentArray comment) {
        this.comment = comment;
        return this;
    }

    /**
     * Gets the value of comment.
     *
     * @return comment
     */
    @JsonProperty("comment")
    public ContentArray getComment() {
        return this.comment;
    }

    /**
     * Sets the value of comment.
     *
     * @param comment comment
     */
    public void setComment(ContentArray comment) {
        this.comment = comment;
    }
    /**
     * Fluent getter for page.
     *
     * @return page
     */
    public ContentArray page() {
        return this.page;
    }

    /**
     * Fluent setter for page.
     *
     * @param page page
     * @return this
     */
    public ContentChildren page(ContentArray page) {
        this.page = page;
        return this;
    }

    /**
     * Gets the value of page.
     *
     * @return page
     */
    @JsonProperty("page")
    public ContentArray getPage() {
        return this.page;
    }

    /**
     * Sets the value of page.
     *
     * @param page page
     */
    public void setPage(ContentArray page) {
        this.page = page;
    }
    /**
     * Fluent getter for whiteboard.
     *
     * @return whiteboard
     */
    public ContentArray whiteboard() {
        return this.whiteboard;
    }

    /**
     * Fluent setter for whiteboard.
     *
     * @param whiteboard whiteboard
     * @return this
     */
    public ContentChildren whiteboard(ContentArray whiteboard) {
        this.whiteboard = whiteboard;
        return this;
    }

    /**
     * Gets the value of whiteboard.
     *
     * @return whiteboard
     */
    @JsonProperty("whiteboard")
    public ContentArray getWhiteboard() {
        return this.whiteboard;
    }

    /**
     * Sets the value of whiteboard.
     *
     * @param whiteboard whiteboard
     */
    public void setWhiteboard(ContentArray whiteboard) {
        this.whiteboard = whiteboard;
    }
    /**
     * Fluent getter for database.
     *
     * @return database
     */
    public ContentArray database() {
        return this.database;
    }

    /**
     * Fluent setter for database.
     *
     * @param database database
     * @return this
     */
    public ContentChildren database(ContentArray database) {
        this.database = database;
        return this;
    }

    /**
     * Gets the value of database.
     *
     * @return database
     */
    @JsonProperty("database")
    public ContentArray getDatabase() {
        return this.database;
    }

    /**
     * Sets the value of database.
     *
     * @param database database
     */
    public void setDatabase(ContentArray database) {
        this.database = database;
    }
    /**
     * Fluent getter for embed.
     *
     * @return embed
     */
    public ContentArray embed() {
        return this.embed;
    }

    /**
     * Fluent setter for embed.
     *
     * @param embed embed
     * @return this
     */
    public ContentChildren embed(ContentArray embed) {
        this.embed = embed;
        return this;
    }

    /**
     * Gets the value of embed.
     *
     * @return embed
     */
    @JsonProperty("embed")
    public ContentArray getEmbed() {
        return this.embed;
    }

    /**
     * Sets the value of embed.
     *
     * @param embed embed
     */
    public void setEmbed(ContentArray embed) {
        this.embed = embed;
    }
    /**
     * Fluent getter for folder.
     *
     * @return folder
     */
    public ContentArray folder() {
        return this.folder;
    }

    /**
     * Fluent setter for folder.
     *
     * @param folder folder
     * @return this
     */
    public ContentChildren folder(ContentArray folder) {
        this.folder = folder;
        return this;
    }

    /**
     * Gets the value of folder.
     *
     * @return folder
     */
    @JsonProperty("folder")
    public ContentArray getFolder() {
        return this.folder;
    }

    /**
     * Sets the value of folder.
     *
     * @param folder folder
     */
    public void setFolder(ContentArray folder) {
        this.folder = folder;
    }
    /**
     * Fluent getter for additionalExpandable.
     *
     * @return additionalExpandable
     */
    public Map<String, Object> additionalExpandable() {
        return this.additionalExpandable;
    }

    /**
     * Fluent setter for additionalExpandable.
     *
     * @param additionalExpandable additionalExpandable
     * @return this
     */
    public ContentChildren additionalExpandable(Map<String, Object> additionalExpandable) {
        this.additionalExpandable = additionalExpandable;
        return this;
    }

    /**
     * Gets the value of additionalExpandable.
     *
     * @return additionalExpandable
     */
    @JsonProperty("_expandable")
    public Map<String, Object> getAdditionalExpandable() {
        return this.additionalExpandable;
    }

    /**
     * Sets the value of additionalExpandable.
     *
     * @param additionalExpandable additionalExpandable
     */
    public void setAdditionalExpandable(Map<String, Object> additionalExpandable) {
        this.additionalExpandable = additionalExpandable;
    }
    /**
     * Fluent getter for additionalLinks.
     *
     * @return additionalLinks
     */
    public Map<String, Object> additionalLinks() {
        return this.additionalLinks;
    }

    /**
     * Fluent setter for additionalLinks.
     *
     * @param additionalLinks additionalLinks
     * @return this
     */
    public ContentChildren additionalLinks(Map<String, Object> additionalLinks) {
        this.additionalLinks = additionalLinks;
        return this;
    }

    /**
     * Gets the value of additionalLinks.
     *
     * @return additionalLinks
     */
    @JsonProperty("_links")
    public Map<String, Object> getAdditionalLinks() {
        return this.additionalLinks;
    }

    /**
     * Sets the value of additionalLinks.
     *
     * @param additionalLinks additionalLinks
     */
    public void setAdditionalLinks(Map<String, Object> additionalLinks) {
        this.additionalLinks = additionalLinks;
    }

    @Override
    public boolean equals(Object o) {
        if (this == o) return true;
        if (o == null || getClass() != o.getClass()) return false;
        ContentChildren that = (ContentChildren) o;
        return
            Objects.equals(this.attachment, that.attachment) &&
            Objects.equals(this.comment, that.comment) &&
            Objects.equals(this.page, that.page) &&
            Objects.equals(this.whiteboard, that.whiteboard) &&
            Objects.equals(this.database, that.database) &&
            Objects.equals(this.embed, that.embed) &&
            Objects.equals(this.folder, that.folder) &&
            Objects.equals(this.additionalExpandable, that.additionalExpandable) &&
            Objects.equals(this.additionalLinks, that.additionalLinks);
    }

    @Override
    public int hashCode() {
        return Objects.hash(
            this.attachment, 
            this.comment, 
            this.page, 
            this.whiteboard, 
            this.database, 
            this.embed, 
            this.folder, 
            this.additionalExpandable, 
            this.additionalLinks
        );
    }

    @Override
    public String toString() {
        return "ContentChildren{" +
            "attachment=" + attachment + ", " + 
            "comment=" + comment + ", " + 
            "page=" + page + ", " + 
            "whiteboard=" + whiteboard + ", " + 
            "database=" + database + ", " + 
            "embed=" + embed + ", " + 
            "folder=" + folder + ", " + 
            "additionalExpandable=" + additionalExpandable + ", " + 
            "additionalLinks=" + additionalLinks +
            "}";
    }
}
