// WARNING: This file was generated by PrimeCodeGen. DO NOT EDIT.

package io.github.primelib.confluence4j.rest.v1.models;

import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;
import com.fasterxml.jackson.annotation.JsonTypeName;
import java.util.List;
import java.util.Map;
import java.util.function.Consumer;
import javax.annotation.processing.Generated;
import lombok.AccessLevel;
import lombok.EqualsAndHashCode;
import lombok.Getter;
import lombok.NoArgsConstructor;
import lombok.Setter;
import lombok.ToString;
import lombok.experimental.Accessors;
import org.jetbrains.annotations.ApiStatus;

/**
 * ContentBlueprintDraft
 *
 */
@Getter
@Setter
@EqualsAndHashCode
@ToString
@Accessors(fluent = true, chain = true)
@NoArgsConstructor(access = AccessLevel.PROTECTED, force = true)
@JsonTypeName("ContentBlueprintDraft")
@JsonPropertyOrder({
    "version",
    "title",
    "type",
    "status",
    "space",
    "ancestors"
})
@Generated(value = "io.github.primelib.primecodegen")
public class ContentBlueprintDraft {

    /**
     * The version for the new content.
     */
    @JsonProperty("version")
    protected Map<String, Object> version;

    /**
     * The title of the content. If you don't want to change the title,
set this to the current title of the draft.
     */
    @JsonProperty("title")
    protected String title;

    /**
     * The type of content. Set this to `page`.
     */
    @JsonProperty("type")
    protected String type;

    /**
     * The status of the content. Set this to `current` or omit it altogether.
     */
    @JsonProperty("status")
    protected String status;

    /**
     * The space for the content.
     */
    @JsonProperty("space")
    protected Map<String, Object> space;

    /**
     * The new ancestor (i.e. parent page) for the content. If you have
specified an ancestor, you must also specify a `space` property
in the request body for the space that the ancestor is in.

Note, if you specify more than one ancestor, the last ID in the array
will be selected as the parent page for the content.
     */
    @JsonProperty("ancestors")
    protected List<AncestorsItem> ancestors;

    /**
     * Constructs a validated instance of {@link ContentBlueprintDraft}.
     *
     * @param spec the specification to process
     */
    public ContentBlueprintDraft(Consumer<ContentBlueprintDraft> spec) {
        super();
        spec.accept(this);
    }

    /**
     * Constructs a validated instance of {@link ContentBlueprintDraft}.
     * <p>
     * NOTE: This constructor is not considered stable and may change if the model is updated. Consider using {@link #ContentBlueprintDraft(Consumer)} instead.
     * @param version The version for the new content.
     * @param title The title of the content. If you don't want to change the title,
set this to the current title of the draft.
     * @param type The type of content. Set this to `page`.
     * @param status The status of the content. Set this to `current` or omit it altogether.
     * @param space The space for the content.
     * @param ancestors The new ancestor (i.e. parent page) for the content. If you have
specified an ancestor, you must also specify a `space` property
in the request body for the space that the ancestor is in.

Note, if you specify more than one ancestor, the last ID in the array
will be selected as the parent page for the content.
     */
    @ApiStatus.Internal
    public ContentBlueprintDraft(Map<String, Object> version, String title, String type, String status, Map<String, Object> space, List<AncestorsItem> ancestors) {
        this.version = version;
        this.title = title;
        this.type = type;
        this.status = status;
        this.space = space;
        this.ancestors = ancestors;
    }
}
