// WARNING: This file was generated by PrimeCodeGen. DO NOT EDIT.

package io.github.primelib.confluence4j.rest.v1.models;

import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;
import com.fasterxml.jackson.annotation.JsonTypeName;
import java.util.List;
import java.util.Map;
import java.util.function.Consumer;
import javax.annotation.processing.Generated;
import lombok.AccessLevel;
import lombok.EqualsAndHashCode;
import lombok.Getter;
import lombok.NoArgsConstructor;
import lombok.Setter;
import lombok.ToString;
import lombok.experimental.Accessors;
import org.jetbrains.annotations.ApiStatus;

/**
 * ContentTemplateArray
 *
 */
@Getter
@Setter
@EqualsAndHashCode
@ToString
@Accessors(fluent = true, chain = true)
@NoArgsConstructor(access = AccessLevel.PROTECTED, force = true)
@JsonTypeName("ContentTemplateArray")
@JsonPropertyOrder({
    "results",
    "start",
    "limit",
    "size",
    "Links"
})
@Generated(value = "io.github.primelib.primecodegen")
public class ContentTemplateArray {

    @JsonProperty("results")
    protected List<ContentTemplate> results;

    @JsonProperty("start")
    protected Integer start;

    @JsonProperty("limit")
    protected Integer limit;

    @JsonProperty("size")
    protected Integer size;

    @JsonProperty("_links")
    protected Map<String, Object> Links;

    /**
     * Constructs a validated instance of {@link ContentTemplateArray}.
     *
     * @param spec the specification to process
     */
    public ContentTemplateArray(Consumer<ContentTemplateArray> spec) {
        super();
        spec.accept(this);
    }

    /**
     * Constructs a validated instance of {@link ContentTemplateArray}.
     * <p>
     * NOTE: This constructor is not considered stable and may change if the model is updated. Consider using {@link #ContentTemplateArray(Consumer)} instead.
     * @param results results
     * @param start start
     * @param limit limit
     * @param size size
     * @param Links Links
     */
    @ApiStatus.Internal
    public ContentTemplateArray(List<ContentTemplate> results, Integer start, Integer limit, Integer size, Map<String, Object> Links) {
        this.results = results;
        this.start = start;
        this.limit = limit;
        this.size = size;
        this.Links = Links;
    }
}
