// WARNING: This file was generated by PrimeCodeGen. DO NOT EDIT.

package io.github.primelib.confluence4j.rest.v1.models;

import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;
import com.fasterxml.jackson.annotation.JsonTypeName;
import java.util.function.Consumer;
import javax.annotation.processing.Generated;
import lombok.AccessLevel;
import lombok.EqualsAndHashCode;
import lombok.Getter;
import lombok.NoArgsConstructor;
import lombok.Setter;
import lombok.ToString;
import lombok.experimental.Accessors;
import org.jetbrains.annotations.ApiStatus;

/**
 * Containerb524B8
 * <p>
 * The new content to attach the attachment to.
 *
 */
@Getter
@Setter
@EqualsAndHashCode
@ToString
@Accessors(fluent = true, chain = true)
@NoArgsConstructor(access = AccessLevel.PROTECTED, force = true)
@JsonTypeName("Containerb524B8")
@JsonPropertyOrder({
    "id",
    "type"
})
@Generated(value = "io.github.primelib.primecodegen")
public class Containerb524B8 {

    /**
     * The `id` of the parent content.
     */
    @JsonProperty("id")
    protected String id;

    /**
     * The content type. You can only attach attachments to content
of type: `page`, `blogpost`.
     */
    @JsonProperty("type")
    protected String type;

    /**
     * Constructs a validated instance of {@link Containerb524B8}.
     *
     * @param spec the specification to process
     */
    public Containerb524B8(Consumer<Containerb524B8> spec) {
        super();
        spec.accept(this);
    }

    /**
     * Constructs a validated instance of {@link Containerb524B8}.
     * <p>
     * NOTE: This constructor is not considered stable and may change if the model is updated. Consider using {@link #Containerb524B8(Consumer)} instead.
     * @param id The `id` of the parent content.
     * @param type The content type. You can only attach attachments to content
of type: `page`, `blogpost`.
     */
    @ApiStatus.Internal
    public Containerb524B8(String id, String type) {
        this.id = id;
        this.type = type;
    }
}
