// WARNING: This file was generated by PrimeCodeGen. DO NOT EDIT.

package io.github.primelib.confluence4j.rest.v1.models;

import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;
import com.fasterxml.jackson.annotation.JsonTypeName;
import java.util.function.Consumer;
import javax.annotation.processing.Generated;
import lombok.AccessLevel;
import lombok.EqualsAndHashCode;
import lombok.Getter;
import lombok.NoArgsConstructor;
import lombok.Setter;
import lombok.ToString;
import lombok.experimental.Accessors;
import org.jetbrains.annotations.ApiStatus;

/**
 * Expandabled0Ed16
 *
 */
@Getter
@Setter
@EqualsAndHashCode
@ToString
@Accessors(fluent = true, chain = true)
@NoArgsConstructor(access = AccessLevel.PROTECTED, force = true)
@JsonTypeName("Expandabled0Ed16")
@JsonPropertyOrder({
    "operations"
})
@Generated(value = "io.github.primelib.primecodegen")
public class Expandabled0Ed16 {

    @JsonProperty("operations")
    protected String operations;

    /**
     * Constructs a validated instance of {@link Expandabled0Ed16}.
     *
     * @param spec the specification to process
     */
    public Expandabled0Ed16(Consumer<Expandabled0Ed16> spec) {
        super();
        spec.accept(this);
    }

    /**
     * Constructs a validated instance of {@link Expandabled0Ed16}.
     * <p>
     * NOTE: This constructor is not considered stable and may change if the model is updated. Consider using {@link #Expandabled0Ed16(Consumer)} instead.
     * @param operations operations
     */
    @ApiStatus.Internal
    public Expandabled0Ed16(String operations) {
        this.operations = operations;
    }
}
