// WARNING: This file was generated by PrimeCodeGen. DO NOT EDIT.

package io.github.primelib.confluence4j.rest.v1.models;

import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;
import com.fasterxml.jackson.annotation.JsonTypeName;
import java.util.Objects;
import java.util.function.Consumer;
import javax.annotation.processing.Generated;
import org.jetbrains.annotations.ApiStatus;

/**
 * Expandabled0Ed16
 *
 */
@JsonTypeName("Expandabled0Ed16")
@JsonPropertyOrder({
    "operations"
})
@Generated(value = "io.github.primelib.primecodegen")
public class Expandabled0Ed16 {

    @JsonProperty("operations")
    protected String operations;

    /**
     * Constructs a validated instance of {@link Expandabled0Ed16}.
     *
     * @param spec the specification to process
     */
    public Expandabled0Ed16(Consumer<Expandabled0Ed16> spec) {
        super();
        spec.accept(this);
    }

    /**
     * Protected no-args constructor for use by serialization frameworks.
     */
    @ApiStatus.Internal
    protected Expandabled0Ed16() {
    }

    /**
     * Constructs a validated instance of {@link Expandabled0Ed16}.
     * <p>
     * NOTE: This constructor is not considered stable and may change if the model is updated. Consider using {@link #Expandabled0Ed16(Consumer)} instead.
     * @param operations operations
     */
    @ApiStatus.Internal
    public Expandabled0Ed16(String operations) {
        this.operations = operations;
    }


    /**
     * Fluent getter for operations.
     *
     * @return operations
     */
    public String operations() {
        return this.operations;
    }

    /**
     * Fluent setter for operations.
     *
     * @param operations operations
     * @return this
     */
    public Expandabled0Ed16 operations(String operations) {
        this.operations = operations;
        return this;
    }

    /**
     * Gets the value of operations.
     *
     * @return operations
     */
    @JsonProperty("operations")
    public String getOperations() {
        return this.operations;
    }

    /**
     * Sets the value of operations.
     *
     * @param operations operations
     */
    public void setOperations(String operations) {
        this.operations = operations;
    }

    @Override
    public boolean equals(Object o) {
        if (this == o) return true;
        if (o == null || getClass() != o.getClass()) return false;
        Expandabled0Ed16 that = (Expandabled0Ed16) o;
        return
            Objects.equals(this.operations, that.operations);
    }

    @Override
    public int hashCode() {
        return Objects.hash(
            this.operations
        );
    }

    @Override
    public String toString() {
        return "Expandabled0Ed16{" +
            "operations=" + operations +
            "}";
    }
}
