// WARNING: This file was generated by PrimeCodeGen. DO NOT EDIT.

package io.github.primelib.confluence4j.rest.v1.models;

import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;
import com.fasterxml.jackson.annotation.JsonTypeName;
import java.util.function.Consumer;
import javax.annotation.processing.Generated;
import lombok.AccessLevel;
import lombok.EqualsAndHashCode;
import lombok.Getter;
import lombok.NoArgsConstructor;
import lombok.Setter;
import lombok.ToString;
import lombok.experimental.Accessors;
import org.jetbrains.annotations.ApiStatus;

/**
 * Expandable52D461
 *
 */
@Getter
@Setter
@EqualsAndHashCode
@ToString
@Accessors(fluent = true, chain = true)
@NoArgsConstructor(access = AccessLevel.PROTECTED, force = true)
@JsonTypeName("Expandable52D461")
@JsonPropertyOrder({
    "settings",
    "metadata",
    "operations",
    "lookAndFeel",
    "permissions",
    "icon",
    "description",
    "theme",
    "history",
    "homepage",
    "identifiers"
})
@Generated(value = "io.github.primelib.primecodegen")
public class Expandable52D461 {

    @JsonProperty("settings")
    protected String settings;

    @JsonProperty("metadata")
    protected String metadata;

    @JsonProperty("operations")
    protected String operations;

    @JsonProperty("lookAndFeel")
    protected String lookAndFeel;

    @JsonProperty("permissions")
    protected String permissions;

    @JsonProperty("icon")
    protected String icon;

    @JsonProperty("description")
    protected String description;

    @JsonProperty("theme")
    protected String theme;

    @JsonProperty("history")
    protected String history;

    @JsonProperty("homepage")
    protected String homepage;

    @JsonProperty("identifiers")
    protected String identifiers;

    /**
     * Constructs a validated instance of {@link Expandable52D461}.
     *
     * @param spec the specification to process
     */
    public Expandable52D461(Consumer<Expandable52D461> spec) {
        super();
        spec.accept(this);
    }

    /**
     * Constructs a validated instance of {@link Expandable52D461}.
     * <p>
     * NOTE: This constructor is not considered stable and may change if the model is updated. Consider using {@link #Expandable52D461(Consumer)} instead.
     * @param settings settings
     * @param metadata metadata
     * @param operations operations
     * @param lookAndFeel lookAndFeel
     * @param permissions permissions
     * @param icon icon
     * @param description description
     * @param theme theme
     * @param history history
     * @param homepage homepage
     * @param identifiers identifiers
     */
    @ApiStatus.Internal
    public Expandable52D461(String settings, String metadata, String operations, String lookAndFeel, String permissions, String icon, String description, String theme, String history, String homepage, String identifiers) {
        this.settings = settings;
        this.metadata = metadata;
        this.operations = operations;
        this.lookAndFeel = lookAndFeel;
        this.permissions = permissions;
        this.icon = icon;
        this.description = description;
        this.theme = theme;
        this.history = history;
        this.homepage = homepage;
        this.identifiers = identifiers;
    }
}
