// WARNING: This file was generated by PrimeCodeGen. DO NOT EDIT.

package io.github.primelib.confluence4j.rest.v1.models;

import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;
import com.fasterxml.jackson.annotation.JsonTypeName;
import java.util.Objects;
import java.util.function.Consumer;
import javax.annotation.processing.Generated;
import org.jetbrains.annotations.ApiStatus;

/**
 * Expandableac2380
 *
 */
@JsonTypeName("Expandableac2380")
@JsonPropertyOrder({
    "user",
    "group"
})
@Generated(value = "io.github.primelib.primecodegen")
public class Expandableac2380 {

    @JsonProperty("user")
    protected String user;

    @JsonProperty("group")
    protected String group;

    /**
     * Constructs a validated instance of {@link Expandableac2380}.
     *
     * @param spec the specification to process
     */
    public Expandableac2380(Consumer<Expandableac2380> spec) {
        super();
        spec.accept(this);
    }

    /**
     * Protected no-args constructor for use by serialization frameworks.
     */
    @ApiStatus.Internal
    protected Expandableac2380() {
    }

    /**
     * Constructs a validated instance of {@link Expandableac2380}.
     * <p>
     * NOTE: This constructor is not considered stable and may change if the model is updated. Consider using {@link #Expandableac2380(Consumer)} instead.
     * @param user user
     * @param group group
     */
    @ApiStatus.Internal
    public Expandableac2380(String user, String group) {
        this.user = user;
        this.group = group;
    }


    /**
     * Fluent getter for user.
     *
     * @return user
     */
    public String user() {
        return this.user;
    }

    /**
     * Fluent setter for user.
     *
     * @param user user
     * @return this
     */
    public Expandableac2380 user(String user) {
        this.user = user;
        return this;
    }

    /**
     * Gets the value of user.
     *
     * @return user
     */
    @JsonProperty("user")
    public String getUser() {
        return this.user;
    }

    /**
     * Sets the value of user.
     *
     * @param user user
     */
    public void setUser(String user) {
        this.user = user;
    }
    /**
     * Fluent getter for group.
     *
     * @return group
     */
    public String group() {
        return this.group;
    }

    /**
     * Fluent setter for group.
     *
     * @param group group
     * @return this
     */
    public Expandableac2380 group(String group) {
        this.group = group;
        return this;
    }

    /**
     * Gets the value of group.
     *
     * @return group
     */
    @JsonProperty("group")
    public String getGroup() {
        return this.group;
    }

    /**
     * Sets the value of group.
     *
     * @param group group
     */
    public void setGroup(String group) {
        this.group = group;
    }

    @Override
    public boolean equals(Object o) {
        if (this == o) return true;
        if (o == null || getClass() != o.getClass()) return false;
        Expandableac2380 that = (Expandableac2380) o;
        return
            Objects.equals(this.user, that.user) &&
            Objects.equals(this.group, that.group);
    }

    @Override
    public int hashCode() {
        return Objects.hash(
            this.user, 
            this.group
        );
    }

    @Override
    public String toString() {
        return "Expandableac2380{" +
            "user=" + user + ", " + 
            "group=" + group +
            "}";
    }
}
