// WARNING: This file was generated by PrimeCodeGen. DO NOT EDIT.

package io.github.primelib.confluence4j.rest.v1.models;

import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;
import com.fasterxml.jackson.annotation.JsonTypeName;
import java.util.function.Consumer;
import javax.annotation.processing.Generated;
import lombok.AccessLevel;
import lombok.EqualsAndHashCode;
import lombok.Getter;
import lombok.NoArgsConstructor;
import lombok.Setter;
import lombok.ToString;
import lombok.experimental.Accessors;
import org.jetbrains.annotations.ApiStatus;

/**
 * Expandable5C5D70
 *
 */
@Getter
@Setter
@EqualsAndHashCode
@ToString
@Accessors(fluent = true, chain = true)
@NoArgsConstructor(access = AccessLevel.PROTECTED, force = true)
@JsonTypeName("Expandable5C5D70")
@JsonPropertyOrder({
    "operations",
    "details",
    "personalSpace"
})
@Generated(value = "io.github.primelib.primecodegen")
public class Expandable5C5D70 {

    @JsonProperty("operations")
    protected String operations;

    @JsonProperty("details")
    protected String details;

    @JsonProperty("personalSpace")
    protected String personalSpace;

    /**
     * Constructs a validated instance of {@link Expandable5C5D70}.
     *
     * @param spec the specification to process
     */
    public Expandable5C5D70(Consumer<Expandable5C5D70> spec) {
        super();
        spec.accept(this);
    }

    /**
     * Constructs a validated instance of {@link Expandable5C5D70}.
     * <p>
     * NOTE: This constructor is not considered stable and may change if the model is updated. Consider using {@link #Expandable5C5D70(Consumer)} instead.
     * @param operations operations
     * @param details details
     * @param personalSpace personalSpace
     */
    @ApiStatus.Internal
    public Expandable5C5D70(String operations, String details, String personalSpace) {
        this.operations = operations;
        this.details = details;
        this.personalSpace = personalSpace;
    }
}
