// WARNING: This file was generated by PrimeCodeGen. DO NOT EDIT.

package io.github.primelib.confluence4j.rest.v1.models;

import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;
import com.fasterxml.jackson.annotation.JsonTypeName;
import java.util.function.Consumer;
import javax.annotation.processing.Generated;
import lombok.AccessLevel;
import lombok.EqualsAndHashCode;
import lombok.Getter;
import lombok.NoArgsConstructor;
import lombok.Setter;
import lombok.ToString;
import lombok.experimental.Accessors;
import org.jetbrains.annotations.ApiStatus;

/**
 * GroupIteme9D8Fc
 * <p>
 * A group that the restriction will be applied to.
 *
 */
@Getter
@Setter
@EqualsAndHashCode
@ToString
@Accessors(fluent = true, chain = true)
@NoArgsConstructor(access = AccessLevel.PROTECTED, force = true)
@JsonTypeName("GroupIteme9D8Fc")
@JsonPropertyOrder({
    "type",
    "name"
})
@Generated(value = "io.github.primelib.primecodegen")
public class GroupIteme9D8Fc {

    /**
     * Set to 'group'.
     */
    @JsonProperty("type")
    protected String type;

    /**
     * The name of the group.
     */
    @JsonProperty("name")
    protected String name;

    /**
     * Constructs a validated instance of {@link GroupIteme9D8Fc}.
     *
     * @param spec the specification to process
     */
    public GroupIteme9D8Fc(Consumer<GroupIteme9D8Fc> spec) {
        super();
        spec.accept(this);
    }

    /**
     * Constructs a validated instance of {@link GroupIteme9D8Fc}.
     * <p>
     * NOTE: This constructor is not considered stable and may change if the model is updated. Consider using {@link #GroupIteme9D8Fc(Consumer)} instead.
     * @param type Set to 'group'.
     * @param name The name of the group.
     */
    @ApiStatus.Internal
    public GroupIteme9D8Fc(String type, String name) {
        this.type = type;
        this.name = name;
    }
}
