// WARNING: This file was generated by PrimeCodeGen. DO NOT EDIT.

package io.github.primelib.confluence4j.rest.v1.models;

import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;
import com.fasterxml.jackson.annotation.JsonTypeName;
import java.util.List;
import java.util.Map;
import java.util.Objects;
import java.util.function.Consumer;
import javax.annotation.processing.Generated;
import org.jetbrains.annotations.ApiStatus;

/**
 * Groupcf0E10
 *
 */
@JsonTypeName("Groupcf0E10")
@JsonPropertyOrder({
    "results",
    "size"
})
@Generated(value = "io.github.primelib.primecodegen")
public class Groupcf0E10 {

    @JsonProperty("results")
    protected List<Map<String, Object>> results;

    @JsonProperty("size")
    protected Integer size;

    /**
     * Constructs a validated instance of {@link Groupcf0E10}.
     *
     * @param spec the specification to process
     */
    public Groupcf0E10(Consumer<Groupcf0E10> spec) {
        super();
        spec.accept(this);
    }

    /**
     * Protected no-args constructor for use by serialization frameworks.
     */
    @ApiStatus.Internal
    protected Groupcf0E10() {
    }

    /**
     * Constructs a validated instance of {@link Groupcf0E10}.
     * <p>
     * NOTE: This constructor is not considered stable and may change if the model is updated. Consider using {@link #Groupcf0E10(Consumer)} instead.
     * @param results results
     * @param size size
     */
    @ApiStatus.Internal
    public Groupcf0E10(List<Map<String, Object>> results, Integer size) {
        this.results = results;
        this.size = size;
    }


    /**
     * Fluent getter for results.
     *
     * @return results
     */
    public List<Map<String, Object>> results() {
        return this.results;
    }

    /**
     * Fluent setter for results.
     *
     * @param results results
     * @return this
     */
    public Groupcf0E10 results(List<Map<String, Object>> results) {
        this.results = results;
        return this;
    }

    /**
     * Gets the value of results.
     *
     * @return results
     */
    @JsonProperty("results")
    public List<Map<String, Object>> getResults() {
        return this.results;
    }

    /**
     * Sets the value of results.
     *
     * @param results results
     */
    public void setResults(List<Map<String, Object>> results) {
        this.results = results;
    }
    /**
     * Fluent getter for size.
     *
     * @return size
     */
    public Integer size() {
        return this.size;
    }

    /**
     * Fluent setter for size.
     *
     * @param size size
     * @return this
     */
    public Groupcf0E10 size(Integer size) {
        this.size = size;
        return this;
    }

    /**
     * Gets the value of size.
     *
     * @return size
     */
    @JsonProperty("size")
    public Integer getSize() {
        return this.size;
    }

    /**
     * Sets the value of size.
     *
     * @param size size
     */
    public void setSize(Integer size) {
        this.size = size;
    }

    @Override
    public boolean equals(Object o) {
        if (this == o) return true;
        if (o == null || getClass() != o.getClass()) return false;
        Groupcf0E10 that = (Groupcf0E10) o;
        return
            Objects.equals(this.results, that.results) &&
            Objects.equals(this.size, that.size);
    }

    @Override
    public int hashCode() {
        return Objects.hash(
            this.results, 
            this.size
        );
    }

    @Override
    public String toString() {
        return "Groupcf0E10{" +
            "results=" + results + ", " + 
            "size=" + size +
            "}";
    }
}
