// WARNING: This file was generated by PrimeCodeGen. DO NOT EDIT.

package io.github.primelib.confluence4j.rest.v1.models;

import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;
import com.fasterxml.jackson.annotation.JsonTypeName;
import java.util.List;
import java.util.Objects;
import java.util.function.Consumer;
import javax.annotation.processing.Generated;
import org.jetbrains.annotations.ApiStatus;

/**
 * Name
 *
 */
@JsonTypeName("Name")
@JsonPropertyOrder({
    "key",
    "args"
})
@Generated(value = "io.github.primelib.primecodegen")
public class Name {

    @JsonProperty("key")
    protected String key;

    @JsonProperty("args")
    protected List<Object> args;

    /**
     * Constructs a validated instance of {@link Name}.
     *
     * @param spec the specification to process
     */
    public Name(Consumer<Name> spec) {
        super();
        spec.accept(this);
    }

    /**
     * Protected no-args constructor for use by serialization frameworks.
     */
    @ApiStatus.Internal
    protected Name() {
    }

    /**
     * Constructs a validated instance of {@link Name}.
     * <p>
     * NOTE: This constructor is not considered stable and may change if the model is updated. Consider using {@link #Name(Consumer)} instead.
     * @param key key
     * @param args args
     */
    @ApiStatus.Internal
    public Name(String key, List<Object> args) {
        this.key = key;
        this.args = args;
    }


    /**
     * Fluent getter for key.
     *
     * @return key
     */
    public String key() {
        return this.key;
    }

    /**
     * Fluent setter for key.
     *
     * @param key key
     * @return this
     */
    public Name key(String key) {
        this.key = key;
        return this;
    }

    /**
     * Gets the value of key.
     *
     * @return key
     */
    @JsonProperty("key")
    public String getKey() {
        return this.key;
    }

    /**
     * Sets the value of key.
     *
     * @param key key
     */
    public void setKey(String key) {
        this.key = key;
    }
    /**
     * Fluent getter for args.
     *
     * @return args
     */
    public List<Object> args() {
        return this.args;
    }

    /**
     * Fluent setter for args.
     *
     * @param args args
     * @return this
     */
    public Name args(List<Object> args) {
        this.args = args;
        return this;
    }

    /**
     * Gets the value of args.
     *
     * @return args
     */
    @JsonProperty("args")
    public List<Object> getArgs() {
        return this.args;
    }

    /**
     * Sets the value of args.
     *
     * @param args args
     */
    public void setArgs(List<Object> args) {
        this.args = args;
    }

    @Override
    public boolean equals(Object o) {
        if (this == o) return true;
        if (o == null || getClass() != o.getClass()) return false;
        Name that = (Name) o;
        return
            Objects.equals(this.key, that.key) &&
            Objects.equals(this.args, that.args);
    }

    @Override
    public int hashCode() {
        return Objects.hash(
            this.key, 
            this.args
        );
    }

    @Override
    public String toString() {
        return "Name{" +
            "key=" + key + ", " + 
            "args=" + args +
            "}";
    }
}
