// WARNING: This file was generated by PrimeCodeGen. DO NOT EDIT.

package io.github.primelib.confluence4j.rest.v1.models;

import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;
import com.fasterxml.jackson.annotation.JsonTypeName;
import java.util.function.Consumer;
import javax.annotation.processing.Generated;
import lombok.AccessLevel;
import lombok.EqualsAndHashCode;
import lombok.Getter;
import lombok.NoArgsConstructor;
import lombok.Setter;
import lombok.ToString;
import lombok.experimental.Accessors;
import org.jetbrains.annotations.ApiStatus;

/**
 * Operation
 *
 */
@Getter
@Setter
@EqualsAndHashCode
@ToString
@Accessors(fluent = true, chain = true)
@NoArgsConstructor(access = AccessLevel.PROTECTED, force = true)
@JsonTypeName("Operation")
@JsonPropertyOrder({
    "key",
    "target"
})
@Generated(value = "io.github.primelib.primecodegen")
public class Operation {

    @JsonProperty("key")
    protected String key;

    /**
     * The space or content type that the operation applies to.
     */
    @JsonProperty("target")
    protected String target;

    /**
     * Constructs a validated instance of {@link Operation}.
     *
     * @param spec the specification to process
     */
    public Operation(Consumer<Operation> spec) {
        super();
        spec.accept(this);
    }

    /**
     * Constructs a validated instance of {@link Operation}.
     * <p>
     * NOTE: This constructor is not considered stable and may change if the model is updated. Consider using {@link #Operation(Consumer)} instead.
     * @param key key
     * @param target The space or content type that the operation applies to.
     */
    @ApiStatus.Internal
    public Operation(String key, String target) {
        this.key = key;
        this.target = target;
    }
}
