// WARNING: This file was generated by PrimeCodeGen. DO NOT EDIT.

package io.github.primelib.confluence4j.rest.v1.models;

import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;
import com.fasterxml.jackson.annotation.JsonTypeName;
import java.util.function.Consumer;
import javax.annotation.processing.Generated;
import lombok.AccessLevel;
import lombok.EqualsAndHashCode;
import lombok.Getter;
import lombok.NoArgsConstructor;
import lombok.Setter;
import lombok.ToString;
import lombok.experimental.Accessors;
import org.jetbrains.annotations.ApiStatus;

/**
 * Params
 *
 */
@Getter
@Setter
@EqualsAndHashCode
@ToString
@Accessors(fluent = true, chain = true)
@NoArgsConstructor(access = AccessLevel.PROTECTED, force = true)
@JsonTypeName("Params")
@JsonPropertyOrder({
    "versionNumber",
    "message",
    "restoreTitle"
})
@Generated(value = "io.github.primelib.primecodegen")
public class Params {

    /**
     * The version number to be restored.
     */
    @JsonProperty("versionNumber")
    protected Integer versionNumber;

    /**
     * Description for the version.
     */
    @JsonProperty("message")
    protected String message;

    /**
     * If true, the content title will be the same as the title from the version restored. Defaults to `false`.
     */
    @JsonProperty("restoreTitle")
    protected Boolean restoreTitle;

    /**
     * Constructs a validated instance of {@link Params}.
     *
     * @param spec the specification to process
     */
    public Params(Consumer<Params> spec) {
        super();
        spec.accept(this);
    }

    /**
     * Constructs a validated instance of {@link Params}.
     * <p>
     * NOTE: This constructor is not considered stable and may change if the model is updated. Consider using {@link #Params(Consumer)} instead.
     * @param versionNumber The version number to be restored.
     * @param message Description for the version.
     * @param restoreTitle If true, the content title will be the same as the title from the version restored. Defaults to `false`.
     */
    @ApiStatus.Internal
    public Params(Integer versionNumber, String message, Boolean restoreTitle) {
        this.versionNumber = versionNumber;
        this.message = message;
        this.restoreTitle = restoreTitle;
    }
}
