// WARNING: This file was generated by PrimeCodeGen. DO NOT EDIT.

package io.github.primelib.confluence4j.rest.v1.models;

import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;
import com.fasterxml.jackson.annotation.JsonTypeName;
import java.util.List;
import java.util.Map;
import java.util.function.Consumer;
import javax.annotation.processing.Generated;
import lombok.AccessLevel;
import lombok.EqualsAndHashCode;
import lombok.Getter;
import lombok.NoArgsConstructor;
import lombok.Setter;
import lombok.ToString;
import lombok.experimental.Accessors;
import org.jetbrains.annotations.ApiStatus;

/**
 * PermissionCheckResponse
 * <p>
 * This object represents the response for the content permission check API. If the user or group does not have
 * permissions, the following errors may be returned:
 * 
 * - Group does not have permission to the space
 * - Group does not have permission to the content
 * - User is not allowed to use Confluence
 * - User does not have permission to the space
 * - User does not have permission to the content
 * - Anonymous users are not allowed to use Confluence
 * - Anonymous user does not have permission to the space
 * - Anonymous user does not have permission to the content
 *
 */
@Getter
@Setter
@EqualsAndHashCode
@ToString
@Accessors(fluent = true, chain = true)
@NoArgsConstructor(access = AccessLevel.PROTECTED, force = true)
@JsonTypeName("PermissionCheckResponse")
@JsonPropertyOrder({
    "hasPermission",
    "errors",
    "Links"
})
@Generated(value = "io.github.primelib.primecodegen")
public class PermissionCheckResponse {

    @JsonProperty("hasPermission")
    protected Boolean hasPermission;

    @JsonProperty("errors")
    protected List<Map<String, Object>> errors;

    @JsonProperty("_links")
    protected Map<String, Object> Links;

    /**
     * Constructs a validated instance of {@link PermissionCheckResponse}.
     *
     * @param spec the specification to process
     */
    public PermissionCheckResponse(Consumer<PermissionCheckResponse> spec) {
        super();
        spec.accept(this);
    }

    /**
     * Constructs a validated instance of {@link PermissionCheckResponse}.
     * <p>
     * NOTE: This constructor is not considered stable and may change if the model is updated. Consider using {@link #PermissionCheckResponse(Consumer)} instead.
     * @param hasPermission hasPermission
     * @param errors errors
     * @param Links Links
     */
    @ApiStatus.Internal
    public PermissionCheckResponse(Boolean hasPermission, List<Map<String, Object>> errors, Map<String, Object> Links) {
        this.hasPermission = hasPermission;
        this.errors = errors;
        this.Links = Links;
    }
}
