// WARNING: This file was generated by PrimeCodeGen. DO NOT EDIT.

package io.github.primelib.confluence4j.rest.v1.models;

import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;
import com.fasterxml.jackson.annotation.JsonTypeName;
import java.util.Map;
import java.util.function.Consumer;
import javax.annotation.processing.Generated;
import lombok.AccessLevel;
import lombok.EqualsAndHashCode;
import lombok.Getter;
import lombok.NoArgsConstructor;
import lombok.Setter;
import lombok.ToString;
import lombok.experimental.Accessors;
import org.jetbrains.annotations.ApiStatus;

/**
 * Restrictionsbc3Afc
 *
 */
@Getter
@Setter
@EqualsAndHashCode
@ToString
@Accessors(fluent = true, chain = true)
@NoArgsConstructor(access = AccessLevel.PROTECTED, force = true)
@JsonTypeName("Restrictionsbc3Afc")
@JsonPropertyOrder({
    "read",
    "update",
    "Expandable",
    "Links"
})
@Generated(value = "io.github.primelib.primecodegen")
public class Restrictionsbc3Afc {

    @JsonProperty("read")
    protected ContentRestriction read;

    @JsonProperty("update")
    protected ContentRestriction update;

    @JsonProperty("_expandable")
    protected Expandable25A645 Expandable;

    @JsonProperty("_links")
    protected Map<String, Object> Links;

    /**
     * Constructs a validated instance of {@link Restrictionsbc3Afc}.
     *
     * @param spec the specification to process
     */
    public Restrictionsbc3Afc(Consumer<Restrictionsbc3Afc> spec) {
        super();
        spec.accept(this);
    }

    /**
     * Constructs a validated instance of {@link Restrictionsbc3Afc}.
     * <p>
     * NOTE: This constructor is not considered stable and may change if the model is updated. Consider using {@link #Restrictionsbc3Afc(Consumer)} instead.
     * @param read read
     * @param update update
     * @param Expandable Expandable
     * @param Links Links
     */
    @ApiStatus.Internal
    public Restrictionsbc3Afc(ContentRestriction read, ContentRestriction update, Expandable25A645 Expandable, Map<String, Object> Links) {
        this.read = read;
        this.update = update;
        this.Expandable = Expandable;
        this.Links = Links;
    }
}
