// WARNING: This file was generated by PrimeCodeGen. DO NOT EDIT.

package io.github.primelib.confluence4j.rest.v1.models;

import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;
import com.fasterxml.jackson.annotation.JsonTypeName;
import java.util.List;
import java.util.function.Consumer;
import javax.annotation.processing.Generated;
import lombok.AccessLevel;
import lombok.EqualsAndHashCode;
import lombok.Getter;
import lombok.NoArgsConstructor;
import lombok.Setter;
import lombok.ToString;
import lombok.experimental.Accessors;
import org.jetbrains.annotations.ApiStatus;

/**
 * Restrictionsf477D3
 * <p>
 * The users/groups that the restrictions will be applied to. At least one of
 * `user` or `group` must be specified for this object.
 *
 */
@Getter
@Setter
@EqualsAndHashCode
@ToString
@Accessors(fluent = true, chain = true)
@NoArgsConstructor(access = AccessLevel.PROTECTED, force = true)
@JsonTypeName("Restrictionsf477D3")
@JsonPropertyOrder({
    "group",
    "user"
})
@Generated(value = "io.github.primelib.primecodegen")
public class Restrictionsf477D3 {

    /**
     * The groups that the restrictions will be applied to. This array must
have at least one item, otherwise it should be omitted.
     */
    @JsonProperty("group")
    protected List<GroupItem> group;

    @JsonProperty("user")
    protected Object user;

    /**
     * Constructs a validated instance of {@link Restrictionsf477D3}.
     *
     * @param spec the specification to process
     */
    public Restrictionsf477D3(Consumer<Restrictionsf477D3> spec) {
        super();
        spec.accept(this);
    }

    /**
     * Constructs a validated instance of {@link Restrictionsf477D3}.
     * <p>
     * NOTE: This constructor is not considered stable and may change if the model is updated. Consider using {@link #Restrictionsf477D3(Consumer)} instead.
     * @param group The groups that the restrictions will be applied to. This array must
have at least one item, otherwise it should be omitted.
     * @param user user
     */
    @ApiStatus.Internal
    public Restrictionsf477D3(List<GroupItem> group, Object user) {
        this.group = group;
        this.user = user;
    }
}
