// WARNING: This file was generated by PrimeCodeGen. DO NOT EDIT.

package io.github.primelib.confluence4j.rest.v1.models;

import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;
import com.fasterxml.jackson.annotation.JsonTypeName;
import java.util.function.Consumer;
import javax.annotation.processing.Generated;
import lombok.AccessLevel;
import lombok.EqualsAndHashCode;
import lombok.Getter;
import lombok.NoArgsConstructor;
import lombok.Setter;
import lombok.ToString;
import lombok.experimental.Accessors;
import org.jetbrains.annotations.ApiStatus;

/**
 * Space33569E
 * <p>
 * The space for the content.
 *
 */
@Getter
@Setter
@EqualsAndHashCode
@ToString
@Accessors(fluent = true, chain = true)
@NoArgsConstructor(access = AccessLevel.PROTECTED, force = true)
@JsonTypeName("Space33569E")
@JsonPropertyOrder({
    "key"
})
@Generated(value = "io.github.primelib.primecodegen")
public class Space33569E {

    /**
     * The key of the space
     */
    @JsonProperty("key")
    protected String key;

    /**
     * Constructs a validated instance of {@link Space33569E}.
     *
     * @param spec the specification to process
     */
    public Space33569E(Consumer<Space33569E> spec) {
        super();
        spec.accept(this);
    }

    /**
     * Constructs a validated instance of {@link Space33569E}.
     * <p>
     * NOTE: This constructor is not considered stable and may change if the model is updated. Consider using {@link #Space33569E(Consumer)} instead.
     * @param key The key of the space
     */
    @ApiStatus.Internal
    public Space33569E(String key) {
        this.key = key;
    }
}
