// WARNING: This file was generated by PrimeCodeGen. DO NOT EDIT.

package io.github.primelib.confluence4j.rest.v1.models;

import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;
import com.fasterxml.jackson.annotation.JsonTypeName;
import java.util.function.Consumer;
import javax.annotation.processing.Generated;
import lombok.AccessLevel;
import lombok.EqualsAndHashCode;
import lombok.Getter;
import lombok.NoArgsConstructor;
import lombok.Setter;
import lombok.ToString;
import lombok.experimental.Accessors;
import org.jetbrains.annotations.ApiStatus;

/**
 * SpacePermissionCreate
 * <p>
 * This object represents a permission for given space. Permissions consist of
 * at least one operation object with an accompanying subjects object.
 * 
 * The following combinations of `operation` and `targetType` values are
 * valid for the `operation` object:
 * 
 *   - 'create': 'page', 'blogpost', 'comment', 'attachment'
 *   - 'read': 'space'
 *   - 'delete': 'page', 'blogpost', 'comment', 'attachment'
 *   - 'export': 'space'
 *   - 'administer': 'space'
 *
 */
@Getter
@Setter
@EqualsAndHashCode
@ToString
@Accessors(fluent = true, chain = true)
@NoArgsConstructor(access = AccessLevel.PROTECTED, force = true)
@JsonTypeName("SpacePermissionCreate")
@JsonPropertyOrder({
    "subjects",
    "operation",
    "anonymousAccess",
    "unlicensedAccess"
})
@Generated(value = "io.github.primelib.primecodegen")
public class SpacePermissionCreate {

    /**
     * The users and/or groups that the permission applies to.
     */
    @JsonProperty("subjects")
    protected Subjects96Eb79 subjects;

    /**
     * An operation and the target entity that it applies to, e.g. create page.
     */
    @JsonProperty("operation")
    protected OperationCheckResult operation;

    /**
     * Grant anonymous users permission to use the operation.
     */
    @JsonProperty("anonymousAccess")
    protected Boolean anonymousAccess;

    /**
     * Grants access to unlicensed users from JIRA Service Desk when used
with the 'read space' operation.
     */
    @JsonProperty("unlicensedAccess")
    protected Boolean unlicensedAccess;

    /**
     * Constructs a validated instance of {@link SpacePermissionCreate}.
     *
     * @param spec the specification to process
     */
    public SpacePermissionCreate(Consumer<SpacePermissionCreate> spec) {
        super();
        spec.accept(this);
    }

    /**
     * Constructs a validated instance of {@link SpacePermissionCreate}.
     * <p>
     * NOTE: This constructor is not considered stable and may change if the model is updated. Consider using {@link #SpacePermissionCreate(Consumer)} instead.
     * @param subjects The users and/or groups that the permission applies to.
     * @param operation An operation and the target entity that it applies to, e.g. create page.
     * @param anonymousAccess Grant anonymous users permission to use the operation.
     * @param unlicensedAccess Grants access to unlicensed users from JIRA Service Desk when used
with the 'read space' operation.
     */
    @ApiStatus.Internal
    public SpacePermissionCreate(Subjects96Eb79 subjects, OperationCheckResult operation, Boolean anonymousAccess, Boolean unlicensedAccess) {
        this.subjects = subjects;
        this.operation = operation;
        this.anonymousAccess = anonymousAccess;
        this.unlicensedAccess = unlicensedAccess;
    }
}
