// WARNING: This file was generated by PrimeCodeGen. DO NOT EDIT.

package io.github.primelib.confluence4j.rest.v1.models;

import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;
import com.fasterxml.jackson.annotation.JsonTypeName;
import java.util.Map;
import java.util.function.Consumer;
import javax.annotation.processing.Generated;
import lombok.AccessLevel;
import lombok.EqualsAndHashCode;
import lombok.Getter;
import lombok.NoArgsConstructor;
import lombok.Setter;
import lombok.ToString;
import lombok.experimental.Accessors;
import org.jetbrains.annotations.ApiStatus;

/**
 * SpaceProperty
 *
 */
@Getter
@Setter
@EqualsAndHashCode
@ToString
@Accessors(fluent = true, chain = true)
@NoArgsConstructor(access = AccessLevel.PROTECTED, force = true)
@JsonTypeName("SpaceProperty")
@JsonPropertyOrder({
    "id",
    "key",
    "value",
    "version",
    "space",
    "Links",
    "Expandable"
})
@Generated(value = "io.github.primelib.primecodegen")
public class SpaceProperty {

    @JsonProperty("id")
    protected String id;

    @JsonProperty("key")
    protected String key;

    @JsonProperty("value")
    protected Object value;

    @JsonProperty("version")
    protected Version version;

    @JsonProperty("space")
    protected Space space;

    @JsonProperty("_links")
    protected Map<String, Object> Links;

    @JsonProperty("_expandable")
    protected Expandable3Adce7 Expandable;

    /**
     * Constructs a validated instance of {@link SpaceProperty}.
     *
     * @param spec the specification to process
     */
    public SpaceProperty(Consumer<SpaceProperty> spec) {
        super();
        spec.accept(this);
    }

    /**
     * Constructs a validated instance of {@link SpaceProperty}.
     * <p>
     * NOTE: This constructor is not considered stable and may change if the model is updated. Consider using {@link #SpaceProperty(Consumer)} instead.
     * @param id id
     * @param key key
     * @param value value
     * @param version version
     * @param space space
     * @param Links Links
     * @param Expandable Expandable
     */
    @ApiStatus.Internal
    public SpaceProperty(String id, String key, Object value, Version version, Space space, Map<String, Object> Links, Expandable3Adce7 Expandable) {
        this.id = id;
        this.key = key;
        this.value = value;
        this.version = version;
        this.space = space;
        this.Links = Links;
        this.Expandable = Expandable;
    }
}
