// WARNING: This file was generated by PrimeCodeGen. DO NOT EDIT.

package io.github.primelib.confluence4j.rest.v1.models;

import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;
import com.fasterxml.jackson.annotation.JsonTypeName;
import java.util.List;
import java.util.Map;
import java.util.function.Consumer;
import javax.annotation.processing.Generated;
import lombok.AccessLevel;
import lombok.EqualsAndHashCode;
import lombok.Getter;
import lombok.NoArgsConstructor;
import lombok.Setter;
import lombok.ToString;
import lombok.experimental.Accessors;
import org.jetbrains.annotations.ApiStatus;

/**
 * SpaceCreate
 * <p>
 * This is the request object used when creating a new space.
 *
 */
@Getter
@Setter
@EqualsAndHashCode
@ToString
@Accessors(fluent = true, chain = true)
@NoArgsConstructor(access = AccessLevel.PROTECTED, force = true)
@JsonTypeName("SpaceCreate")
@JsonPropertyOrder({
    "name",
    "key",
    "alias",
    "description",
    "permissions"
})
@Generated(value = "io.github.primelib.primecodegen")
public class SpaceCreate {

    /**
     * The name of the new space.
     */
    @JsonProperty("name")
    protected String name;

    /**
     * The key for the new space. Format: See [Space
keys](https://confluence.atlassian.com/x/lqNMMQ). If `alias` is not provided, this is required.
     */
    @JsonProperty("key")
    protected String key;

    /**
     * This field will be used as the new identifier for the space in confluence page URLs.
If the property is not provided the alias will be the provided key.
This property is experimental and may be changed or removed in the future.
     */
    @JsonProperty("alias")
    protected String alias;

    /**
     * The description of the new/updated space. Note, only the 'plain' representation
can be used for the description when creating or updating a space.
     */
    @JsonProperty("description")
    protected SpaceDescriptionCreate description;

    /**
     * The permissions for the new space. If no permissions are provided, the
[Confluence default space permissions](https://confluence.atlassian.com/x/UAgzKw#CreateaSpace-Spacepermissions)
are applied. Note that if permissions are provided, the space is
created with only the provided set of permissions, not
including the default space permissions. Space permissions
can be modified after creation using the space permissions
endpoints, and a private space can be created using the
create private space endpoint.
     */
    @JsonProperty("permissions")
    protected List<Map<String, Object>> permissions;

    /**
     * Constructs a validated instance of {@link SpaceCreate}.
     *
     * @param spec the specification to process
     */
    public SpaceCreate(Consumer<SpaceCreate> spec) {
        super();
        spec.accept(this);
    }

    /**
     * Constructs a validated instance of {@link SpaceCreate}.
     * <p>
     * NOTE: This constructor is not considered stable and may change if the model is updated. Consider using {@link #SpaceCreate(Consumer)} instead.
     * @param name The name of the new space.
     * @param key The key for the new space. Format: See [Space
keys](https://confluence.atlassian.com/x/lqNMMQ). If `alias` is not provided, this is required.
     * @param alias This field will be used as the new identifier for the space in confluence page URLs.
If the property is not provided the alias will be the provided key.
This property is experimental and may be changed or removed in the future.
     * @param description The description of the new/updated space. Note, only the 'plain' representation
can be used for the description when creating or updating a space.
     * @param permissions The permissions for the new space. If no permissions are provided, the
[Confluence default space permissions](https://confluence.atlassian.com/x/UAgzKw#CreateaSpace-Spacepermissions)
are applied. Note that if permissions are provided, the space is
created with only the provided set of permissions, not
including the default space permissions. Space permissions
can be modified after creation using the space permissions
endpoints, and a private space can be created using the
create private space endpoint.
     */
    @ApiStatus.Internal
    public SpaceCreate(String name, String key, String alias, SpaceDescriptionCreate description, List<Map<String, Object>> permissions) {
        this.name = name;
        this.key = key;
        this.alias = alias;
        this.description = description;
        this.permissions = permissions;
    }
}
