// WARNING: This file was generated by PrimeCodeGen. DO NOT EDIT.

package io.github.primelib.confluence4j.rest.v1.models;

import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;
import com.fasterxml.jackson.annotation.JsonTypeName;
import java.util.Map;
import java.util.function.Consumer;
import javax.annotation.processing.Generated;
import lombok.AccessLevel;
import lombok.EqualsAndHashCode;
import lombok.Getter;
import lombok.NoArgsConstructor;
import lombok.Setter;
import lombok.ToString;
import lombok.experimental.Accessors;
import org.jetbrains.annotations.ApiStatus;

/**
 * SpacePermissionV2
 * <p>
 * This object represents a single space permission. Permissions consist of
 * at least one operation object with an accompanying subjects object.
 * 
 * The following combinations of `operation.key` and `operation.target` values are
 * valid for the `operation` object:
 * ``` bash
 * 'create': 'page', 'blogpost', 'comment', 'attachment'
 * 'read': 'space'
 * 'delete': 'page', 'blogpost', 'comment', 'attachment', 'space'
 * 'export': 'space'
 * 'administer': 'space'
 * 'archive': 'page'
 * 'restrict_content': 'space'
 * ```
 * 
 * For example, to enable Delete Own permission, set the `operation` object to the following:
 * ```
 * "operation": {
 *     "key": "delete",
 *     "target": "space"
 * }
 * ```
 * To enable Add/Delete Restrictions permissions, set the `operation` object to the following:
 * ```
 * "operation": {
 *     "key": "restrict_content",
 *     "target": "space"
 * }
 * ```
 *
 */
@Getter
@Setter
@EqualsAndHashCode
@ToString
@Accessors(fluent = true, chain = true)
@NoArgsConstructor(access = AccessLevel.PROTECTED, force = true)
@JsonTypeName("SpacePermissionV2")
@JsonPropertyOrder({
    "id",
    "subject",
    "operation",
    "Links"
})
@Generated(value = "io.github.primelib.primecodegen")
public class SpacePermissionV2 {

    @JsonProperty("id")
    protected Long id;

    /**
     * The user or group that the permission applies to.
     */
    @JsonProperty("subject")
    protected PermissionSubject subject;

    @JsonProperty("operation")
    protected Operation operation;

    @JsonProperty("_links")
    protected Map<String, Object> Links;

    /**
     * Constructs a validated instance of {@link SpacePermissionV2}.
     *
     * @param spec the specification to process
     */
    public SpacePermissionV2(Consumer<SpacePermissionV2> spec) {
        super();
        spec.accept(this);
    }

    /**
     * Constructs a validated instance of {@link SpacePermissionV2}.
     * <p>
     * NOTE: This constructor is not considered stable and may change if the model is updated. Consider using {@link #SpacePermissionV2(Consumer)} instead.
     * @param id id
     * @param subject The user or group that the permission applies to.
     * @param operation operation
     * @param Links Links
     */
    @ApiStatus.Internal
    public SpacePermissionV2(Long id, PermissionSubject subject, Operation operation, Map<String, Object> Links) {
        this.id = id;
        this.subject = subject;
        this.operation = operation;
        this.Links = Links;
    }
}
