// WARNING: This file was generated by PrimeCodeGen. DO NOT EDIT.

package io.github.primelib.confluence4j.rest.v1.models;

import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;
import com.fasterxml.jackson.annotation.JsonTypeName;
import java.util.List;
import java.util.Map;
import java.util.function.Consumer;
import javax.annotation.processing.Generated;
import lombok.AccessLevel;
import lombok.EqualsAndHashCode;
import lombok.Getter;
import lombok.NoArgsConstructor;
import lombok.Setter;
import lombok.ToString;
import lombok.experimental.Accessors;
import org.jetbrains.annotations.ApiStatus;

/**
 * UserAnonymous
 *
 */
@Getter
@Setter
@EqualsAndHashCode
@ToString
@Accessors(fluent = true, chain = true)
@NoArgsConstructor(access = AccessLevel.PROTECTED, force = true)
@JsonTypeName("UserAnonymous")
@JsonPropertyOrder({
    "type",
    "profilePicture",
    "displayName",
    "operations",
    "Expandable",
    "Links"
})
@Generated(value = "io.github.primelib.primecodegen")
public class UserAnonymous {

    @JsonProperty("type")
    protected String type;

    /**
     * This object represents an icon. If used as a profilePicture, this may be returned as null, depending on the user's privacy setting.
     */
    @JsonProperty("profilePicture")
    protected Icon profilePicture;

    @JsonProperty("displayName")
    protected String displayName;

    @JsonProperty("operations")
    protected List<OperationCheckResult> operations;

    @JsonProperty("_expandable")
    protected Expandabled0Ed16 Expandable;

    @JsonProperty("_links")
    protected Map<String, Object> Links;

    /**
     * Constructs a validated instance of {@link UserAnonymous}.
     *
     * @param spec the specification to process
     */
    public UserAnonymous(Consumer<UserAnonymous> spec) {
        super();
        spec.accept(this);
    }

    /**
     * Constructs a validated instance of {@link UserAnonymous}.
     * <p>
     * NOTE: This constructor is not considered stable and may change if the model is updated. Consider using {@link #UserAnonymous(Consumer)} instead.
     * @param type type
     * @param profilePicture This object represents an icon. If used as a profilePicture, this may be returned as null, depending on the user's privacy setting.
     * @param displayName displayName
     * @param operations operations
     * @param Expandable Expandable
     * @param Links Links
     */
    @ApiStatus.Internal
    public UserAnonymous(String type, Icon profilePicture, String displayName, List<OperationCheckResult> operations, Expandabled0Ed16 Expandable, Map<String, Object> Links) {
        this.type = type;
        this.profilePicture = profilePicture;
        this.displayName = displayName;
        this.operations = operations;
        this.Expandable = Expandable;
        this.Links = Links;
    }
}
