// WARNING: This file was generated by PrimeCodeGen. DO NOT EDIT.

package io.github.primelib.confluence4j.rest.v1.models;

import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;
import com.fasterxml.jackson.annotation.JsonTypeName;
import java.util.List;
import java.util.Map;
import java.util.function.Consumer;
import javax.annotation.processing.Generated;
import lombok.AccessLevel;
import lombok.EqualsAndHashCode;
import lombok.Getter;
import lombok.NoArgsConstructor;
import lombok.Setter;
import lombok.ToString;
import lombok.experimental.Accessors;
import org.jetbrains.annotations.ApiStatus;

/**
 * Userb34Fc6
 *
 */
@Getter
@Setter
@EqualsAndHashCode
@ToString
@Accessors(fluent = true, chain = true)
@NoArgsConstructor(access = AccessLevel.PROTECTED, force = true)
@JsonTypeName("Userb34Fc6")
@JsonPropertyOrder({
    "results",
    "size",
    "start",
    "limit"
})
@Generated(value = "io.github.primelib.primecodegen")
public class Userb34Fc6 {

    @JsonProperty("results")
    protected List<Map<String, Object>> results;

    @JsonProperty("size")
    protected Integer size;

    @JsonProperty("start")
    protected Integer start;

    @JsonProperty("limit")
    protected Integer limit;

    /**
     * Constructs a validated instance of {@link Userb34Fc6}.
     *
     * @param spec the specification to process
     */
    public Userb34Fc6(Consumer<Userb34Fc6> spec) {
        super();
        spec.accept(this);
    }

    /**
     * Constructs a validated instance of {@link Userb34Fc6}.
     * <p>
     * NOTE: This constructor is not considered stable and may change if the model is updated. Consider using {@link #Userb34Fc6(Consumer)} instead.
     * @param results results
     * @param size size
     * @param start start
     * @param limit limit
     */
    @ApiStatus.Internal
    public Userb34Fc6(List<Map<String, Object>> results, Integer size, Integer start, Integer limit) {
        this.results = results;
        this.size = size;
        this.start = start;
        this.limit = limit;
    }
}
