// WARNING: This file was generated by PrimeCodeGen. DO NOT EDIT.

package io.github.primelib.confluence4j.rest.v1.models;

import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;
import com.fasterxml.jackson.annotation.JsonTypeName;
import java.util.function.Consumer;
import javax.annotation.processing.Generated;
import lombok.AccessLevel;
import lombok.EqualsAndHashCode;
import lombok.Getter;
import lombok.NoArgsConstructor;
import lombok.Setter;
import lombok.ToString;
import lombok.experimental.Accessors;
import org.jetbrains.annotations.ApiStatus;

/**
 * Version5F500D
 * <p>
 * The new version for the updated content. Set this to the current version number incremented by one, unless you are changing the status to 'draft' which must have a version number of 1.
 * 
 * To get the current version number, use [Get content by ID](#api-content-id-get) and retrieve `version.number`.
 *
 */
@Getter
@Setter
@EqualsAndHashCode
@ToString
@Accessors(fluent = true, chain = true)
@NoArgsConstructor(access = AccessLevel.PROTECTED, force = true)
@JsonTypeName("Version5F500D")
@JsonPropertyOrder({
    "number",
    "message"
})
@Generated(value = "io.github.primelib.primecodegen")
public class Version5F500D {

    /**
     * The version number.
     */
    @JsonProperty("number")
    protected Integer number;

    /**
     * An optional message to be stored with the corresponding version.
     */
    @JsonProperty("message")
    protected String message;

    /**
     * Constructs a validated instance of {@link Version5F500D}.
     *
     * @param spec the specification to process
     */
    public Version5F500D(Consumer<Version5F500D> spec) {
        super();
        spec.accept(this);
    }

    /**
     * Constructs a validated instance of {@link Version5F500D}.
     * <p>
     * NOTE: This constructor is not considered stable and may change if the model is updated. Consider using {@link #Version5F500D(Consumer)} instead.
     * @param number The version number.
     * @param message An optional message to be stored with the corresponding version.
     */
    @ApiStatus.Internal
    public Version5F500D(Integer number, String message) {
        this.number = number;
        this.message = message;
    }
}
