// WARNING: This file was generated by PrimeCodeGen. DO NOT EDIT.

package io.github.primelib.confluence4j.rest.v1.models;

import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;
import com.fasterxml.jackson.annotation.JsonTypeName;
import java.util.Objects;
import java.util.function.Consumer;
import javax.annotation.processing.Generated;
import org.jetbrains.annotations.ApiStatus;

/**
 * Versiona9Ec0E
 * <p>
 * The version for the new content.
 *
 */
@JsonTypeName("Versiona9Ec0E")
@JsonPropertyOrder({
    "number"
})
@Generated(value = "io.github.primelib.primecodegen")
public class Versiona9Ec0E {

    /**
     * The version number. Set this to `1`.
     */
    @JsonProperty("number")
    protected Integer number;

    /**
     * Constructs a validated instance of {@link Versiona9Ec0E}.
     *
     * @param spec the specification to process
     */
    public Versiona9Ec0E(Consumer<Versiona9Ec0E> spec) {
        super();
        spec.accept(this);
    }

    /**
     * Protected no-args constructor for use by serialization frameworks.
     */
    @ApiStatus.Internal
    protected Versiona9Ec0E() {
    }

    /**
     * Constructs a validated instance of {@link Versiona9Ec0E}.
     * <p>
     * NOTE: This constructor is not considered stable and may change if the model is updated. Consider using {@link #Versiona9Ec0E(Consumer)} instead.
     * @param number The version number. Set this to `1`.
     */
    @ApiStatus.Internal
    public Versiona9Ec0E(Integer number) {
        this.number = number;
    }


    /**
     * Fluent getter for number.
     * <p>
     * The version number. Set this to `1`.
     *
     * @return number
     */
    public Integer number() {
        return this.number;
    }

    /**
     * Fluent setter for number.
     * <p>
     * The version number. Set this to `1`.
     *
     * @param number number
     * @return this
     */
    public Versiona9Ec0E number(Integer number) {
        this.number = number;
        return this;
    }

    /**
     * Gets the value of number.
     * <p>
     * The version number. Set this to `1`.
     *
     * @return number
     */
    @JsonProperty("number")
    public Integer getNumber() {
        return this.number;
    }

    /**
     * Sets the value of number.
     * <p>
     * The version number. Set this to `1`.
     *
     * @param number number
     */
    public void setNumber(Integer number) {
        this.number = number;
    }

    @Override
    public boolean equals(Object o) {
        if (this == o) return true;
        if (o == null || getClass() != o.getClass()) return false;
        Versiona9Ec0E that = (Versiona9Ec0E) o;
        return
            Objects.equals(this.number, that.number);
    }

    @Override
    public int hashCode() {
        return Objects.hash(
            this.number
        );
    }

    @Override
    public String toString() {
        return "Versiona9Ec0E{" +
            "number=" + number +
            "}";
    }
}
