// WARNING: This file was generated by PrimeCodeGen. DO NOT EDIT.

package io.github.primelib.confluence4j.rest.v1.operations;

import java.util.function.Consumer;
import javax.annotation.processing.Generated;
import lombok.EqualsAndHashCode;
import lombok.Getter;
import lombok.Setter;
import lombok.ToString;
import lombok.experimental.Accessors;
import org.jetbrains.annotations.ApiStatus;
import org.jspecify.annotations.Nullable;

/**
 * DeleteSettingsLookandfeelCustomV1
 * <p>
 * Resets the custom look and feel settings for the site or a single space.
 * This changes the values of the custom settings to be the same as the
 * default settings. It does not change which settings (default or custom)
 * are selected. Note, the default space settings are inherited from the
 * current global settings.
 * 
 * **[Permissions](https://confluence.atlassian.com/x/_AozKw) required**:
 * 'Admin' permission for the space.
 *
 */
@Getter
@Setter
@EqualsAndHashCode
@ToString
@Accessors(fluent = true, chain = true)
@Generated(value = "io.github.primelib.primecodegen")
public class DeleteSettingsLookandfeelCustomV1OperationSpec {
    /**
     * allows to disable validation of the spec, use with care!
     */
    @ApiStatus.Experimental
    public static Boolean VALIDATION_ENABLED = true;

    /**
     * The key of the space for which the look and feel settings will be
     * reset. If this is not set, the global look and feel settings will
     * be reset.
     *
     */
    @Nullable
    private String spaceKey;

    /**
     * Constructs a validated instance of {@link DeleteSettingsLookandfeelCustomV1OperationSpec}.
     *
     * @param spec the specification to process
     */
    @ApiStatus.Internal
    public DeleteSettingsLookandfeelCustomV1OperationSpec(Consumer<DeleteSettingsLookandfeelCustomV1OperationSpec> spec) {
        spec.accept(this);
        if (VALIDATION_ENABLED)
            validate();
    }

    /**
     * Validates the Spec, will throw a exception if required parameters are missing
     *
     * @throws NullPointerException
     */
    public void validate() {
    }
}
