// WARNING: This file was generated by PrimeCodeGen. DO NOT EDIT.

package io.github.primelib.confluence4j.rest.v1.operations;

import io.github.primelib.confluence4j.rest.v1.models.AccountId;
import java.util.Objects;
import java.util.function.Consumer;
import javax.annotation.processing.Generated;
import lombok.EqualsAndHashCode;
import lombok.Getter;
import lombok.Setter;
import lombok.ToString;
import lombok.experimental.Accessors;
import org.jetbrains.annotations.ApiStatus;
import org.jspecify.annotations.NonNull;

/**
 * PostGroupUserByGroupIDV1
 * <p>
 * Adds a user as a member in a group represented by its groupId
 * 
 * **[Permissions](https://confluence.atlassian.com/x/_AozKw) required**:
 * User must be a site admin.
 *
 */
@Getter
@Setter
@EqualsAndHashCode
@ToString
@Accessors(fluent = true, chain = true)
@Generated(value = "io.github.primelib.primecodegen")
public class PostGroupUserByGroupIDV1OperationSpec {
    /**
     * allows to disable validation of the spec, use with care!
     */
    @ApiStatus.Experimental
    public static Boolean VALIDATION_ENABLED = true;

    /**
     * GroupId of the group whose membership is updated
     *
     */
    @NonNull
    private String groupId;

    /**
     * AccountId of the user who needs to be added as member.
     *
     */
    @NonNull
    private AccountId payload;

    /**
     * Constructs a validated instance of {@link PostGroupUserByGroupIDV1OperationSpec}.
     *
     * @param spec the specification to process
     */
    @ApiStatus.Internal
    public PostGroupUserByGroupIDV1OperationSpec(Consumer<PostGroupUserByGroupIDV1OperationSpec> spec) {
        spec.accept(this);
        if (VALIDATION_ENABLED)
            validate();
    }

    /**
     * Validates the Spec, will throw a exception if required parameters are missing
     *
     * @throws NullPointerException
     */
    public void validate() {
        Objects.requireNonNull(groupId, "groupId is a required parameter!");
        Objects.requireNonNull(payload, "payload is a required parameter!");
    }
}
