// WARNING: This file was generated by PrimeCodeGen. DO NOT EDIT.

package io.github.primelib.confluence4j.rest.v1.operations;

import io.github.primelib.confluence4j.rest.v1.models.SpacePermissionCustomContent;
import java.util.Objects;
import java.util.function.Consumer;
import javax.annotation.processing.Generated;
import lombok.EqualsAndHashCode;
import lombok.Getter;
import lombok.Setter;
import lombok.ToString;
import lombok.experimental.Accessors;
import org.jetbrains.annotations.ApiStatus;
import org.jspecify.annotations.NonNull;

/**
 * PostSpaceBySpaceKeyPermissionCustomContentV1
 * <p>
 * Adds new custom content permission to space.
 * 
 * If the permission to be added is a group permission, the group can be identified
 * by its group name or group id.
 * 
 * Note: Only apps can access this REST resource and only make changes to the respective app permissions.
 * 
 * **[Permissions](https://confluence.atlassian.com/x/_AozKw) required**:
 * 'Admin' permission for the space.
 *
 */
@Getter
@Setter
@EqualsAndHashCode
@ToString
@Accessors(fluent = true, chain = true)
@Generated(value = "io.github.primelib.primecodegen")
public class PostSpaceBySpaceKeyPermissionCustomContentV1OperationSpec {
    /**
     * allows to disable validation of the spec, use with care!
     */
    @ApiStatus.Experimental
    public static Boolean VALIDATION_ENABLED = true;

    /**
     * The key of the space to be queried for its content.
     *
     */
    @NonNull
    private String spaceKey;

    /**
     * The permissions to be created.
     *
     */
    @NonNull
    private SpacePermissionCustomContent payload;

    /**
     * Constructs a validated instance of {@link PostSpaceBySpaceKeyPermissionCustomContentV1OperationSpec}.
     *
     * @param spec the specification to process
     */
    @ApiStatus.Internal
    public PostSpaceBySpaceKeyPermissionCustomContentV1OperationSpec(Consumer<PostSpaceBySpaceKeyPermissionCustomContentV1OperationSpec> spec) {
        spec.accept(this);
        if (VALIDATION_ENABLED)
            validate();
    }

    /**
     * Validates the Spec, will throw a exception if required parameters are missing
     *
     * @throws NullPointerException
     */
    public void validate() {
        Objects.requireNonNull(spaceKey, "spaceKey is a required parameter!");
        Objects.requireNonNull(payload, "payload is a required parameter!");
    }
}
