// WARNING: This file was generated by PrimeCodeGen. DO NOT EDIT.

package io.github.primelib.confluence4j.rest.v1.client;

import feign.Headers;
import feign.Param;
import feign.RequestLine;
import io.github.primelib.confluence4j.rest.v1.models.LabelDetails;
import javax.annotation.processing.Generated;
import org.jetbrains.annotations.NotNull;
import org.jetbrains.annotations.Nullable;

/**
 * ConfluenceRestClientLabelInfoApi
 */
@Generated(value = "io.github.primelib.primecodegen")
public interface ConfluenceRestClientLabelInfoApi {

    /**
    * GetLabelV1
    * Get label information
    * Returns label information and a list of contents associated with the label.
    * 
    * **[Permissions](https://confluence.atlassian.com/x/_AozKw) required**:
    * Permission to access the Confluence site ('Can use' global permission). Only contents
    * that the user is permitted to view is returned.
    *
    * @param name Name of the label to query.
    * @param type The type of contents that are to be returned.
    * @param start The starting offset for the results.
    * @param limit The number of results to be returned.
    */
    @RequestLine("GET /rest/api/label?name={name}&type={type}&start={start}&limit={limit}")
    @Headers({
        "Accept: application/json"
    })
    LabelDetails GetLabelV1(
            @NotNull @Param("name") String name,
            @Nullable @Param("type") String type,
            @Nullable @Param("start") Integer start,
            @Nullable @Param("limit") Integer limit
    );

}
