// WARNING: This file was generated by PrimeCodeGen. DO NOT EDIT.

package io.github.primelib.confluence4j.rest.v1.client;

import io.github.primelib.confluence4j.rest.v1.models.LongTaskStatusArray;
import io.github.primelib.confluence4j.rest.v1.models.LongTaskStatusWithLinks;
import io.github.primelib.confluence4j.rest.v1.operations.GetLongtaskByIDV1OperationSpec;
import io.github.primelib.confluence4j.rest.v1.operations.GetLongtaskV1OperationSpec;
import java.util.function.Consumer;
import javax.annotation.processing.Generated;

/**
 * ConfluenceRestClientLongRunningTaskConsumerApi
 */
@Generated(value = "io.github.primelib.primecodegen")
public class ConfluenceRestClientLongRunningTaskConsumerApi {
    private final ConfluenceRestClientLongRunningTaskApi api;

    public ConfluenceRestClientLongRunningTaskConsumerApi(ConfluenceRestClientLongRunningTaskApi api) {
        this.api = api;
    }


    /**
    * GetLongtaskV1
    * Get long-running tasks
    * Returns information about all active long-running tasks (e.g. space export),
    * such as how long each task has been running and the percentage of each task
    * that has completed.
    * 
    * **[Permissions](https://confluence.atlassian.com/x/_AozKw) required**:
    * Permission to access the Confluence site ('Can use' global permission).
    *
    * @param spec a consumer that creates the payload for this operation. Supports the following properties:
    * <ul>
    *   <li>key: The key of the tasks.</li>
    *   <li>start: The starting index of the returned tasks.</li>
    *   <li>limit: The maximum number of tasks to return per page. Note, this may be restricted by fixed system limits.</li>
    * </ul>
    */
    public LongTaskStatusArray GetLongtaskV1(Consumer<GetLongtaskV1OperationSpec> spec) {
        GetLongtaskV1OperationSpec r = new GetLongtaskV1OperationSpec(spec);
        return api.GetLongtaskV1(r.key(), r.start(), r.limit());
    }

    /**
    * GetLongtaskByIDV1
    * Get long-running task
    * Returns information about an active long-running task (e.g. space export),
    * such as how long it has been running and the percentage of the task that
    * has completed.
    * 
    * **[Permissions](https://confluence.atlassian.com/x/_AozKw) required**:
    * Permission to access the Confluence site ('Can use' global permission).
    *
    * @param spec a consumer that creates the payload for this operation. Supports the following properties:
    * <ul>
    *   <li>id: The ID of the task.</li>
    * </ul>
    */
    public LongTaskStatusWithLinks GetLongtaskByIDV1(Consumer<GetLongtaskByIDV1OperationSpec> spec) {
        GetLongtaskByIDV1OperationSpec r = new GetLongtaskByIDV1OperationSpec(spec);
        return api.GetLongtaskByIDV1(r.id());
    }

}
