// WARNING: This file was generated by PrimeCodeGen. DO NOT EDIT.

package io.github.primelib.confluence4j.rest.v1.models;

import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;
import com.fasterxml.jackson.annotation.JsonTypeName;
import java.util.Objects;
import java.util.function.Consumer;
import javax.annotation.processing.Generated;
import org.jetbrains.annotations.ApiStatus;

/**
 * AttachmentUpdateContainer
 * <p>
 * The new content to attach the attachment to.
 *
 */
@JsonTypeName("AttachmentUpdateContainer")
@JsonPropertyOrder({
    "id",
    "type"
})
@Generated(value = "io.github.primelib.primecodegen")
public class AttachmentUpdateContainer {

    /**
     * The `id` of the parent content.
     */
    @JsonProperty("id")
    protected String id;

    /**
     * The content type. You can only attach attachments to content
of type: `page`, `blogpost`.
     */
    @JsonProperty("type")
    protected String type;

    /**
     * Constructs a validated instance of {@link AttachmentUpdateContainer}.
     *
     * @param spec the specification to process
     */
    public AttachmentUpdateContainer(Consumer<AttachmentUpdateContainer> spec) {
        super();
        spec.accept(this);
    }

    /**
     * Protected no-args constructor for use by serialization frameworks.
     */
    @ApiStatus.Internal
    protected AttachmentUpdateContainer() {
    }

    /**
     * Constructs a validated instance of {@link AttachmentUpdateContainer}.
     * <p>
     * NOTE: This constructor is not considered stable and may change if the model is updated. Consider using {@link #AttachmentUpdateContainer(Consumer)} instead.
     * @param id The `id` of the parent content.
     * @param type The content type. You can only attach attachments to content
of type: `page`, `blogpost`.
     */
    @ApiStatus.Internal
    public AttachmentUpdateContainer(String id, String type) {
        this.id = id;
        this.type = type;
    }


    /**
     * Fluent getter for id.
     * <p>
     * The `id` of the parent content.
     *
     * @return id
     */
    public String id() {
        return this.id;
    }

    /**
     * Fluent setter for id.
     * <p>
     * The `id` of the parent content.
     *
     * @param id id
     * @return this
     */
    public AttachmentUpdateContainer id(String id) {
        this.id = id;
        return this;
    }

    /**
     * Gets the value of id.
     * <p>
     * The `id` of the parent content.
     *
     * @return id
     */
    @JsonProperty("id")
    public String getId() {
        return this.id;
    }

    /**
     * Sets the value of id.
     * <p>
     * The `id` of the parent content.
     *
     * @param id id
     */
    public void setId(String id) {
        this.id = id;
    }
    /**
     * Fluent getter for type.
     * <p>
     * The content type. You can only attach attachments to content
     * of type: `page`, `blogpost`.
     *
     * @return type
     */
    public String type() {
        return this.type;
    }

    /**
     * Fluent setter for type.
     * <p>
     * The content type. You can only attach attachments to content
     * of type: `page`, `blogpost`.
     *
     * @param type type
     * @return this
     */
    public AttachmentUpdateContainer type(String type) {
        this.type = type;
        return this;
    }

    /**
     * Gets the value of type.
     * <p>
     * The content type. You can only attach attachments to content
     * of type: `page`, `blogpost`.
     *
     * @return type
     */
    @JsonProperty("type")
    public String getType() {
        return this.type;
    }

    /**
     * Sets the value of type.
     * <p>
     * The content type. You can only attach attachments to content
     * of type: `page`, `blogpost`.
     *
     * @param type type
     */
    public void setType(String type) {
        this.type = type;
    }

    @Override
    public boolean equals(Object o) {
        if (this == o) return true;
        if (o == null || getClass() != o.getClass()) return false;
        AttachmentUpdateContainer that = (AttachmentUpdateContainer) o;
        return
            Objects.equals(this.id, that.id) &&
            Objects.equals(this.type, that.type);
    }

    @Override
    public int hashCode() {
        return Objects.hash(
            this.id, 
            this.type
        );
    }

    @Override
    public String toString() {
        return "AttachmentUpdateContainer{" +
            "id=" + id + ", " + 
            "type=" + type +
            "}";
    }
}
