// WARNING: This file was generated by PrimeCodeGen. DO NOT EDIT.

package io.github.primelib.confluence4j.rest.v1.models;

import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;
import com.fasterxml.jackson.annotation.JsonTypeName;
import java.util.List;
import java.util.Objects;
import java.util.function.Consumer;
import javax.annotation.processing.Generated;
import org.jetbrains.annotations.ApiStatus;

/**
 * BulkContentBodyConversionInput
 *
 */
@JsonTypeName("BulkContentBodyConversionInput")
@JsonPropertyOrder({
    "conversionInputs"
})
@Generated(value = "io.github.primelib.primecodegen")
public class BulkContentBodyConversionInput {

    @JsonProperty("conversionInputs")
    protected List<ContentBodyConversionInput> conversionInputs;

    /**
     * Constructs a validated instance of {@link BulkContentBodyConversionInput}.
     *
     * @param spec the specification to process
     */
    public BulkContentBodyConversionInput(Consumer<BulkContentBodyConversionInput> spec) {
        super();
        spec.accept(this);
    }

    /**
     * Protected no-args constructor for use by serialization frameworks.
     */
    @ApiStatus.Internal
    protected BulkContentBodyConversionInput() {
    }

    /**
     * Constructs a validated instance of {@link BulkContentBodyConversionInput}.
     * <p>
     * NOTE: This constructor is not considered stable and may change if the model is updated. Consider using {@link #BulkContentBodyConversionInput(Consumer)} instead.
     * @param conversionInputs conversionInputs
     */
    @ApiStatus.Internal
    public BulkContentBodyConversionInput(List<ContentBodyConversionInput> conversionInputs) {
        this.conversionInputs = conversionInputs;
    }


    /**
     * Fluent getter for conversionInputs.
     *
     * @return conversionInputs
     */
    public List<ContentBodyConversionInput> conversionInputs() {
        return this.conversionInputs;
    }

    /**
     * Fluent setter for conversionInputs.
     *
     * @param conversionInputs conversionInputs
     * @return this
     */
    public BulkContentBodyConversionInput conversionInputs(List<ContentBodyConversionInput> conversionInputs) {
        this.conversionInputs = conversionInputs;
        return this;
    }

    /**
     * Gets the value of conversionInputs.
     *
     * @return conversionInputs
     */
    @JsonProperty("conversionInputs")
    public List<ContentBodyConversionInput> getConversionInputs() {
        return this.conversionInputs;
    }

    /**
     * Sets the value of conversionInputs.
     *
     * @param conversionInputs conversionInputs
     */
    public void setConversionInputs(List<ContentBodyConversionInput> conversionInputs) {
        this.conversionInputs = conversionInputs;
    }

    @Override
    public boolean equals(Object o) {
        if (this == o) return true;
        if (o == null || getClass() != o.getClass()) return false;
        BulkContentBodyConversionInput that = (BulkContentBodyConversionInput) o;
        return
            Objects.equals(this.conversionInputs, that.conversionInputs);
    }

    @Override
    public int hashCode() {
        return Objects.hash(
            this.conversionInputs
        );
    }

    @Override
    public String toString() {
        return "BulkContentBodyConversionInput{" +
            "conversionInputs=" + conversionInputs +
            "}";
    }
}
