// WARNING: This file was generated by PrimeCodeGen. DO NOT EDIT.

package io.github.primelib.confluence4j.rest.v1.models;

import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;
import com.fasterxml.jackson.annotation.JsonTypeName;
import java.util.Objects;
import java.util.function.Consumer;
import javax.annotation.processing.Generated;
import org.jetbrains.annotations.ApiStatus;

/**
 * ContentBodyCreateStorage
 * <p>
 * This object is used when creating or updating content.
 *
 */
@JsonTypeName("ContentBodyCreateStorage")
@JsonPropertyOrder({
    "value",
    "representation"
})
@Generated(value = "io.github.primelib.primecodegen")
public class ContentBodyCreateStorage {

    /**
     * The body of the content in the relevant format.
     */
    @JsonProperty("value")
    protected String value;

    /**
     * The content format type. Set the value of this property to
the name of the format being used, e.g. 'storage'.
     */
    @JsonProperty("representation")
    protected String representation;

    /**
     * Constructs a validated instance of {@link ContentBodyCreateStorage}.
     *
     * @param spec the specification to process
     */
    public ContentBodyCreateStorage(Consumer<ContentBodyCreateStorage> spec) {
        super();
        spec.accept(this);
    }

    /**
     * Protected no-args constructor for use by serialization frameworks.
     */
    @ApiStatus.Internal
    protected ContentBodyCreateStorage() {
    }

    /**
     * Constructs a validated instance of {@link ContentBodyCreateStorage}.
     * <p>
     * NOTE: This constructor is not considered stable and may change if the model is updated. Consider using {@link #ContentBodyCreateStorage(Consumer)} instead.
     * @param value The body of the content in the relevant format.
     * @param representation The content format type. Set the value of this property to
the name of the format being used, e.g. 'storage'.
     */
    @ApiStatus.Internal
    public ContentBodyCreateStorage(String value, String representation) {
        this.value = value;
        this.representation = representation;
    }


    /**
     * Fluent getter for value.
     * <p>
     * The body of the content in the relevant format.
     *
     * @return value
     */
    public String value() {
        return this.value;
    }

    /**
     * Fluent setter for value.
     * <p>
     * The body of the content in the relevant format.
     *
     * @param value value
     * @return this
     */
    public ContentBodyCreateStorage value(String value) {
        this.value = value;
        return this;
    }

    /**
     * Gets the value of value.
     * <p>
     * The body of the content in the relevant format.
     *
     * @return value
     */
    @JsonProperty("value")
    public String getValue() {
        return this.value;
    }

    /**
     * Sets the value of value.
     * <p>
     * The body of the content in the relevant format.
     *
     * @param value value
     */
    public void setValue(String value) {
        this.value = value;
    }
    /**
     * Fluent getter for representation.
     * <p>
     * The content format type. Set the value of this property to
     * the name of the format being used, e.g. 'storage'.
     *
     * @return representation
     */
    public String representation() {
        return this.representation;
    }

    /**
     * Fluent setter for representation.
     * <p>
     * The content format type. Set the value of this property to
     * the name of the format being used, e.g. 'storage'.
     *
     * @param representation representation
     * @return this
     */
    public ContentBodyCreateStorage representation(String representation) {
        this.representation = representation;
        return this;
    }

    /**
     * Gets the value of representation.
     * <p>
     * The content format type. Set the value of this property to
     * the name of the format being used, e.g. 'storage'.
     *
     * @return representation
     */
    @JsonProperty("representation")
    public String getRepresentation() {
        return this.representation;
    }

    /**
     * Sets the value of representation.
     * <p>
     * The content format type. Set the value of this property to
     * the name of the format being used, e.g. 'storage'.
     *
     * @param representation representation
     */
    public void setRepresentation(String representation) {
        this.representation = representation;
    }

    @Override
    public boolean equals(Object o) {
        if (this == o) return true;
        if (o == null || getClass() != o.getClass()) return false;
        ContentBodyCreateStorage that = (ContentBodyCreateStorage) o;
        return
            Objects.equals(this.value, that.value) &&
            Objects.equals(this.representation, that.representation);
    }

    @Override
    public int hashCode() {
        return Objects.hash(
            this.value, 
            this.representation
        );
    }

    @Override
    public String toString() {
        return "ContentBodyCreateStorage{" +
            "value=" + value + ", " + 
            "representation=" + representation +
            "}";
    }
}
