// WARNING: This file was generated by PrimeCodeGen. DO NOT EDIT.

package io.github.primelib.confluence4j.rest.v1.models;

import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;
import com.fasterxml.jackson.annotation.JsonTypeName;
import java.util.Map;
import java.util.Objects;
import java.util.function.Consumer;
import javax.annotation.processing.Generated;
import org.jetbrains.annotations.ApiStatus;

/**
 * ContentHistoryContributors
 *
 */
@JsonTypeName("ContentHistoryContributors")
@JsonPropertyOrder({
    "publishers"
})
@Generated(value = "io.github.primelib.primecodegen")
public class ContentHistoryContributors {

    @JsonProperty("publishers")
    protected Map<String, Object> publishers;

    /**
     * Constructs a validated instance of {@link ContentHistoryContributors}.
     *
     * @param spec the specification to process
     */
    public ContentHistoryContributors(Consumer<ContentHistoryContributors> spec) {
        super();
        spec.accept(this);
    }

    /**
     * Protected no-args constructor for use by serialization frameworks.
     */
    @ApiStatus.Internal
    protected ContentHistoryContributors() {
    }

    /**
     * Constructs a validated instance of {@link ContentHistoryContributors}.
     * <p>
     * NOTE: This constructor is not considered stable and may change if the model is updated. Consider using {@link #ContentHistoryContributors(Consumer)} instead.
     * @param publishers publishers
     */
    @ApiStatus.Internal
    public ContentHistoryContributors(Map<String, Object> publishers) {
        this.publishers = publishers;
    }


    /**
     * Fluent getter for publishers.
     *
     * @return publishers
     */
    public Map<String, Object> publishers() {
        return this.publishers;
    }

    /**
     * Fluent setter for publishers.
     *
     * @param publishers publishers
     * @return this
     */
    public ContentHistoryContributors publishers(Map<String, Object> publishers) {
        this.publishers = publishers;
        return this;
    }

    /**
     * Gets the value of publishers.
     *
     * @return publishers
     */
    @JsonProperty("publishers")
    public Map<String, Object> getPublishers() {
        return this.publishers;
    }

    /**
     * Sets the value of publishers.
     *
     * @param publishers publishers
     */
    public void setPublishers(Map<String, Object> publishers) {
        this.publishers = publishers;
    }

    @Override
    public boolean equals(Object o) {
        if (this == o) return true;
        if (o == null || getClass() != o.getClass()) return false;
        ContentHistoryContributors that = (ContentHistoryContributors) o;
        return
            Objects.equals(this.publishers, that.publishers);
    }

    @Override
    public int hashCode() {
        return Objects.hash(
            this.publishers
        );
    }

    @Override
    public String toString() {
        return "ContentHistoryContributors{" +
            "publishers=" + publishers +
            "}";
    }
}
