// WARNING: This file was generated by PrimeCodeGen. DO NOT EDIT.

package io.github.primelib.confluence4j.rest.v1.models;

import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;
import com.fasterxml.jackson.annotation.JsonTypeName;
import java.util.Map;
import java.util.Objects;
import java.util.function.Consumer;
import javax.annotation.processing.Generated;
import org.jetbrains.annotations.ApiStatus;

/**
 * CopyPageRequestBody
 * <p>
 * If defined, this will replace the body of the destination page.
 *
 */
@JsonTypeName("CopyPageRequestBody")
@JsonPropertyOrder({
    "storage",
    "editor2"
})
@Generated(value = "io.github.primelib.primecodegen")
public class CopyPageRequestBody {

    /**
     * This object is used when creating or updating content.
     */
    @JsonProperty("storage")
    protected Map<String, Object> storage;

    /**
     * This object is used when creating or updating content.
     */
    @JsonProperty("editor2")
    protected Map<String, Object> editor2;

    /**
     * Constructs a validated instance of {@link CopyPageRequestBody}.
     *
     * @param spec the specification to process
     */
    public CopyPageRequestBody(Consumer<CopyPageRequestBody> spec) {
        super();
        spec.accept(this);
    }

    /**
     * Protected no-args constructor for use by serialization frameworks.
     */
    @ApiStatus.Internal
    protected CopyPageRequestBody() {
    }

    /**
     * Constructs a validated instance of {@link CopyPageRequestBody}.
     * <p>
     * NOTE: This constructor is not considered stable and may change if the model is updated. Consider using {@link #CopyPageRequestBody(Consumer)} instead.
     * @param storage This object is used when creating or updating content.
     * @param editor2 This object is used when creating or updating content.
     */
    @ApiStatus.Internal
    public CopyPageRequestBody(Map<String, Object> storage, Map<String, Object> editor2) {
        this.storage = storage;
        this.editor2 = editor2;
    }


    /**
     * Fluent getter for storage.
     * <p>
     * This object is used when creating or updating content.
     *
     * @return storage
     */
    public Map<String, Object> storage() {
        return this.storage;
    }

    /**
     * Fluent setter for storage.
     * <p>
     * This object is used when creating or updating content.
     *
     * @param storage storage
     * @return this
     */
    public CopyPageRequestBody storage(Map<String, Object> storage) {
        this.storage = storage;
        return this;
    }

    /**
     * Gets the value of storage.
     * <p>
     * This object is used when creating or updating content.
     *
     * @return storage
     */
    @JsonProperty("storage")
    public Map<String, Object> getStorage() {
        return this.storage;
    }

    /**
     * Sets the value of storage.
     * <p>
     * This object is used when creating or updating content.
     *
     * @param storage storage
     */
    public void setStorage(Map<String, Object> storage) {
        this.storage = storage;
    }
    /**
     * Fluent getter for editor2.
     * <p>
     * This object is used when creating or updating content.
     *
     * @return editor2
     */
    public Map<String, Object> editor2() {
        return this.editor2;
    }

    /**
     * Fluent setter for editor2.
     * <p>
     * This object is used when creating or updating content.
     *
     * @param editor2 editor2
     * @return this
     */
    public CopyPageRequestBody editor2(Map<String, Object> editor2) {
        this.editor2 = editor2;
        return this;
    }

    /**
     * Gets the value of editor2.
     * <p>
     * This object is used when creating or updating content.
     *
     * @return editor2
     */
    @JsonProperty("editor2")
    public Map<String, Object> getEditor2() {
        return this.editor2;
    }

    /**
     * Sets the value of editor2.
     * <p>
     * This object is used when creating or updating content.
     *
     * @param editor2 editor2
     */
    public void setEditor2(Map<String, Object> editor2) {
        this.editor2 = editor2;
    }

    @Override
    public boolean equals(Object o) {
        if (this == o) return true;
        if (o == null || getClass() != o.getClass()) return false;
        CopyPageRequestBody that = (CopyPageRequestBody) o;
        return
            Objects.equals(this.storage, that.storage) &&
            Objects.equals(this.editor2, that.editor2);
    }

    @Override
    public int hashCode() {
        return Objects.hash(
            this.storage, 
            this.editor2
        );
    }

    @Override
    public String toString() {
        return "CopyPageRequestBody{" +
            "storage=" + storage + ", " + 
            "editor2=" + editor2 +
            "}";
    }
}
