// WARNING: This file was generated by PrimeCodeGen. DO NOT EDIT.

package io.github.primelib.confluence4j.rest.v1.models;

import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;
import com.fasterxml.jackson.annotation.JsonTypeName;
import java.util.Map;
import java.util.Objects;
import java.util.function.Consumer;
import javax.annotation.processing.Generated;
import org.jetbrains.annotations.ApiStatus;

/**
 * GetWikiRestcontentByIDRestrictionByOperationV1
 *
 */
@JsonTypeName("GetWikiRestcontentByIDRestrictionByOperationV1")
@JsonPropertyOrder({
    "operationType",
    "additionalLinks"
})
@Generated(value = "io.github.primelib.primecodegen")
public class GetWikiRestcontentByIDRestrictionByOperationV1 {

    @JsonProperty("operationType")
    protected ContentRestriction operationType;

    @JsonProperty("_links")
    protected Map<String, Object> additionalLinks;

    /**
     * Constructs a validated instance of {@link GetWikiRestcontentByIDRestrictionByOperationV1}.
     *
     * @param spec the specification to process
     */
    public GetWikiRestcontentByIDRestrictionByOperationV1(Consumer<GetWikiRestcontentByIDRestrictionByOperationV1> spec) {
        super();
        spec.accept(this);
    }

    /**
     * Protected no-args constructor for use by serialization frameworks.
     */
    @ApiStatus.Internal
    protected GetWikiRestcontentByIDRestrictionByOperationV1() {
    }

    /**
     * Constructs a validated instance of {@link GetWikiRestcontentByIDRestrictionByOperationV1}.
     * <p>
     * NOTE: This constructor is not considered stable and may change if the model is updated. Consider using {@link #GetWikiRestcontentByIDRestrictionByOperationV1(Consumer)} instead.
     * @param operationType operationType
     * @param additionalLinks additionalLinks
     */
    @ApiStatus.Internal
    public GetWikiRestcontentByIDRestrictionByOperationV1(ContentRestriction operationType, Map<String, Object> additionalLinks) {
        this.operationType = operationType;
        this.additionalLinks = additionalLinks;
    }


    /**
     * Fluent getter for operationType.
     *
     * @return operationType
     */
    public ContentRestriction operationType() {
        return this.operationType;
    }

    /**
     * Fluent setter for operationType.
     *
     * @param operationType operationType
     * @return this
     */
    public GetWikiRestcontentByIDRestrictionByOperationV1 operationType(ContentRestriction operationType) {
        this.operationType = operationType;
        return this;
    }

    /**
     * Gets the value of operationType.
     *
     * @return operationType
     */
    @JsonProperty("operationType")
    public ContentRestriction getOperationType() {
        return this.operationType;
    }

    /**
     * Sets the value of operationType.
     *
     * @param operationType operationType
     */
    public void setOperationType(ContentRestriction operationType) {
        this.operationType = operationType;
    }
    /**
     * Fluent getter for additionalLinks.
     *
     * @return additionalLinks
     */
    public Map<String, Object> additionalLinks() {
        return this.additionalLinks;
    }

    /**
     * Fluent setter for additionalLinks.
     *
     * @param additionalLinks additionalLinks
     * @return this
     */
    public GetWikiRestcontentByIDRestrictionByOperationV1 additionalLinks(Map<String, Object> additionalLinks) {
        this.additionalLinks = additionalLinks;
        return this;
    }

    /**
     * Gets the value of additionalLinks.
     *
     * @return additionalLinks
     */
    @JsonProperty("_links")
    public Map<String, Object> getAdditionalLinks() {
        return this.additionalLinks;
    }

    /**
     * Sets the value of additionalLinks.
     *
     * @param additionalLinks additionalLinks
     */
    public void setAdditionalLinks(Map<String, Object> additionalLinks) {
        this.additionalLinks = additionalLinks;
    }

    @Override
    public boolean equals(Object o) {
        if (this == o) return true;
        if (o == null || getClass() != o.getClass()) return false;
        GetWikiRestcontentByIDRestrictionByOperationV1 that = (GetWikiRestcontentByIDRestrictionByOperationV1) o;
        return
            Objects.equals(this.operationType, that.operationType) &&
            Objects.equals(this.additionalLinks, that.additionalLinks);
    }

    @Override
    public int hashCode() {
        return Objects.hash(
            this.operationType, 
            this.additionalLinks
        );
    }

    @Override
    public String toString() {
        return "GetWikiRestcontentByIDRestrictionByOperationV1{" +
            "operationType=" + operationType + ", " + 
            "additionalLinks=" + additionalLinks +
            "}";
    }
}
