// WARNING: This file was generated by PrimeCodeGen. DO NOT EDIT.

package io.github.primelib.confluence4j.rest.v1.models;

import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;
import com.fasterxml.jackson.annotation.JsonTypeName;
import java.util.Objects;
import java.util.function.Consumer;
import javax.annotation.processing.Generated;
import org.jetbrains.annotations.ApiStatus;

/**
 * HeaderLookAndFeel
 *
 */
@JsonTypeName("HeaderLookAndFeel")
@JsonPropertyOrder({
    "backgroundColor",
    "button",
    "primaryNavigation",
    "secondaryNavigation",
    "search"
})
@Generated(value = "io.github.primelib.primecodegen")
public class HeaderLookAndFeel {

    @JsonProperty("backgroundColor")
    protected String backgroundColor;

    @JsonProperty("button")
    protected ButtonLookAndFeel button;

    @JsonProperty("primaryNavigation")
    protected NavigationLookAndFeel primaryNavigation;

    @JsonProperty("secondaryNavigation")
    protected NavigationLookAndFeel secondaryNavigation;

    @JsonProperty("search")
    protected SearchFieldLookAndFeel search;

    /**
     * Constructs a validated instance of {@link HeaderLookAndFeel}.
     *
     * @param spec the specification to process
     */
    public HeaderLookAndFeel(Consumer<HeaderLookAndFeel> spec) {
        super();
        spec.accept(this);
    }

    /**
     * Protected no-args constructor for use by serialization frameworks.
     */
    @ApiStatus.Internal
    protected HeaderLookAndFeel() {
    }

    /**
     * Constructs a validated instance of {@link HeaderLookAndFeel}.
     * <p>
     * NOTE: This constructor is not considered stable and may change if the model is updated. Consider using {@link #HeaderLookAndFeel(Consumer)} instead.
     * @param backgroundColor backgroundColor
     * @param button button
     * @param primaryNavigation primaryNavigation
     * @param secondaryNavigation secondaryNavigation
     * @param search search
     */
    @ApiStatus.Internal
    public HeaderLookAndFeel(String backgroundColor, ButtonLookAndFeel button, NavigationLookAndFeel primaryNavigation, NavigationLookAndFeel secondaryNavigation, SearchFieldLookAndFeel search) {
        this.backgroundColor = backgroundColor;
        this.button = button;
        this.primaryNavigation = primaryNavigation;
        this.secondaryNavigation = secondaryNavigation;
        this.search = search;
    }


    /**
     * Fluent getter for backgroundColor.
     *
     * @return backgroundColor
     */
    public String backgroundColor() {
        return this.backgroundColor;
    }

    /**
     * Fluent setter for backgroundColor.
     *
     * @param backgroundColor backgroundColor
     * @return this
     */
    public HeaderLookAndFeel backgroundColor(String backgroundColor) {
        this.backgroundColor = backgroundColor;
        return this;
    }

    /**
     * Gets the value of backgroundColor.
     *
     * @return backgroundColor
     */
    @JsonProperty("backgroundColor")
    public String getBackgroundColor() {
        return this.backgroundColor;
    }

    /**
     * Sets the value of backgroundColor.
     *
     * @param backgroundColor backgroundColor
     */
    public void setBackgroundColor(String backgroundColor) {
        this.backgroundColor = backgroundColor;
    }
    /**
     * Fluent getter for button.
     *
     * @return button
     */
    public ButtonLookAndFeel button() {
        return this.button;
    }

    /**
     * Fluent setter for button.
     *
     * @param button button
     * @return this
     */
    public HeaderLookAndFeel button(ButtonLookAndFeel button) {
        this.button = button;
        return this;
    }

    /**
     * Gets the value of button.
     *
     * @return button
     */
    @JsonProperty("button")
    public ButtonLookAndFeel getButton() {
        return this.button;
    }

    /**
     * Sets the value of button.
     *
     * @param button button
     */
    public void setButton(ButtonLookAndFeel button) {
        this.button = button;
    }
    /**
     * Fluent getter for primaryNavigation.
     *
     * @return primaryNavigation
     */
    public NavigationLookAndFeel primaryNavigation() {
        return this.primaryNavigation;
    }

    /**
     * Fluent setter for primaryNavigation.
     *
     * @param primaryNavigation primaryNavigation
     * @return this
     */
    public HeaderLookAndFeel primaryNavigation(NavigationLookAndFeel primaryNavigation) {
        this.primaryNavigation = primaryNavigation;
        return this;
    }

    /**
     * Gets the value of primaryNavigation.
     *
     * @return primaryNavigation
     */
    @JsonProperty("primaryNavigation")
    public NavigationLookAndFeel getPrimaryNavigation() {
        return this.primaryNavigation;
    }

    /**
     * Sets the value of primaryNavigation.
     *
     * @param primaryNavigation primaryNavigation
     */
    public void setPrimaryNavigation(NavigationLookAndFeel primaryNavigation) {
        this.primaryNavigation = primaryNavigation;
    }
    /**
     * Fluent getter for secondaryNavigation.
     *
     * @return secondaryNavigation
     */
    public NavigationLookAndFeel secondaryNavigation() {
        return this.secondaryNavigation;
    }

    /**
     * Fluent setter for secondaryNavigation.
     *
     * @param secondaryNavigation secondaryNavigation
     * @return this
     */
    public HeaderLookAndFeel secondaryNavigation(NavigationLookAndFeel secondaryNavigation) {
        this.secondaryNavigation = secondaryNavigation;
        return this;
    }

    /**
     * Gets the value of secondaryNavigation.
     *
     * @return secondaryNavigation
     */
    @JsonProperty("secondaryNavigation")
    public NavigationLookAndFeel getSecondaryNavigation() {
        return this.secondaryNavigation;
    }

    /**
     * Sets the value of secondaryNavigation.
     *
     * @param secondaryNavigation secondaryNavigation
     */
    public void setSecondaryNavigation(NavigationLookAndFeel secondaryNavigation) {
        this.secondaryNavigation = secondaryNavigation;
    }
    /**
     * Fluent getter for search.
     *
     * @return search
     */
    public SearchFieldLookAndFeel search() {
        return this.search;
    }

    /**
     * Fluent setter for search.
     *
     * @param search search
     * @return this
     */
    public HeaderLookAndFeel search(SearchFieldLookAndFeel search) {
        this.search = search;
        return this;
    }

    /**
     * Gets the value of search.
     *
     * @return search
     */
    @JsonProperty("search")
    public SearchFieldLookAndFeel getSearch() {
        return this.search;
    }

    /**
     * Sets the value of search.
     *
     * @param search search
     */
    public void setSearch(SearchFieldLookAndFeel search) {
        this.search = search;
    }

    @Override
    public boolean equals(Object o) {
        if (this == o) return true;
        if (o == null || getClass() != o.getClass()) return false;
        HeaderLookAndFeel that = (HeaderLookAndFeel) o;
        return
            Objects.equals(this.backgroundColor, that.backgroundColor) &&
            Objects.equals(this.button, that.button) &&
            Objects.equals(this.primaryNavigation, that.primaryNavigation) &&
            Objects.equals(this.secondaryNavigation, that.secondaryNavigation) &&
            Objects.equals(this.search, that.search);
    }

    @Override
    public int hashCode() {
        return Objects.hash(
            this.backgroundColor, 
            this.button, 
            this.primaryNavigation, 
            this.secondaryNavigation, 
            this.search
        );
    }

    @Override
    public String toString() {
        return "HeaderLookAndFeel{" +
            "backgroundColor=" + backgroundColor + ", " + 
            "button=" + button + ", " + 
            "primaryNavigation=" + primaryNavigation + ", " + 
            "secondaryNavigation=" + secondaryNavigation + ", " + 
            "search=" + search +
            "}";
    }
}
