// WARNING: This file was generated by PrimeCodeGen. DO NOT EDIT.

package io.github.primelib.confluence4j.rest.v1.models;

import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;
import com.fasterxml.jackson.annotation.JsonTypeName;
import java.time.Instant;
import java.util.Map;
import java.util.Objects;
import java.util.function.Consumer;
import javax.annotation.processing.Generated;
import org.jetbrains.annotations.ApiStatus;

/**
 * RelationTargetHistory
 *
 */
@JsonTypeName("RelationTargetHistory")
@JsonPropertyOrder({
    "createdDate",
    "createdBy"
})
@Generated(value = "io.github.primelib.primecodegen")
public class RelationTargetHistory {

    @JsonProperty("createdDate")
    protected Instant createdDate;

    @JsonProperty("createdBy")
    protected Map<String, Object> createdBy;

    /**
     * Constructs a validated instance of {@link RelationTargetHistory}.
     *
     * @param spec the specification to process
     */
    public RelationTargetHistory(Consumer<RelationTargetHistory> spec) {
        super();
        spec.accept(this);
    }

    /**
     * Protected no-args constructor for use by serialization frameworks.
     */
    @ApiStatus.Internal
    protected RelationTargetHistory() {
    }

    /**
     * Constructs a validated instance of {@link RelationTargetHistory}.
     * <p>
     * NOTE: This constructor is not considered stable and may change if the model is updated. Consider using {@link #RelationTargetHistory(Consumer)} instead.
     * @param createdDate createdDate
     * @param createdBy createdBy
     */
    @ApiStatus.Internal
    public RelationTargetHistory(Instant createdDate, Map<String, Object> createdBy) {
        this.createdDate = createdDate;
        this.createdBy = createdBy;
    }


    /**
     * Fluent getter for createdDate.
     *
     * @return createdDate
     */
    public Instant createdDate() {
        return this.createdDate;
    }

    /**
     * Fluent setter for createdDate.
     *
     * @param createdDate createdDate
     * @return this
     */
    public RelationTargetHistory createdDate(Instant createdDate) {
        this.createdDate = createdDate;
        return this;
    }

    /**
     * Gets the value of createdDate.
     *
     * @return createdDate
     */
    @JsonProperty("createdDate")
    public Instant getCreatedDate() {
        return this.createdDate;
    }

    /**
     * Sets the value of createdDate.
     *
     * @param createdDate createdDate
     */
    public void setCreatedDate(Instant createdDate) {
        this.createdDate = createdDate;
    }
    /**
     * Fluent getter for createdBy.
     *
     * @return createdBy
     */
    public Map<String, Object> createdBy() {
        return this.createdBy;
    }

    /**
     * Fluent setter for createdBy.
     *
     * @param createdBy createdBy
     * @return this
     */
    public RelationTargetHistory createdBy(Map<String, Object> createdBy) {
        this.createdBy = createdBy;
        return this;
    }

    /**
     * Gets the value of createdBy.
     *
     * @return createdBy
     */
    @JsonProperty("createdBy")
    public Map<String, Object> getCreatedBy() {
        return this.createdBy;
    }

    /**
     * Sets the value of createdBy.
     *
     * @param createdBy createdBy
     */
    public void setCreatedBy(Map<String, Object> createdBy) {
        this.createdBy = createdBy;
    }

    @Override
    public boolean equals(Object o) {
        if (this == o) return true;
        if (o == null || getClass() != o.getClass()) return false;
        RelationTargetHistory that = (RelationTargetHistory) o;
        return
            Objects.equals(this.createdDate, that.createdDate) &&
            Objects.equals(this.createdBy, that.createdBy);
    }

    @Override
    public int hashCode() {
        return Objects.hash(
            this.createdDate, 
            this.createdBy
        );
    }

    @Override
    public String toString() {
        return "RelationTargetHistory{" +
            "createdDate=" + createdDate + ", " + 
            "createdBy=" + createdBy +
            "}";
    }
}
