// WARNING: This file was generated by PrimeCodeGen. DO NOT EDIT.

package io.github.primelib.confluence4j.rest.v1.models;

import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;
import com.fasterxml.jackson.annotation.JsonTypeName;
import java.util.Objects;
import java.util.function.Consumer;
import javax.annotation.processing.Generated;
import org.jetbrains.annotations.ApiStatus;

/**
 * SpaceSettingsUpdate
 *
 */
@JsonTypeName("SpaceSettingsUpdate")
@JsonPropertyOrder({
    "routeOverrideEnabled"
})
@Generated(value = "io.github.primelib.primecodegen")
public class SpaceSettingsUpdate {

    /**
     * Defines whether an override for the space home should be used. This is
used in conjunction with a space theme provided by an app. For
example, if this property is set to true, a theme can display a page
other than the space homepage when users visit the root URL for a
space. This property allows apps to provide content-only theming
without overriding the space home.
     */
    @JsonProperty("routeOverrideEnabled")
    protected Boolean routeOverrideEnabled;

    /**
     * Constructs a validated instance of {@link SpaceSettingsUpdate}.
     *
     * @param spec the specification to process
     */
    public SpaceSettingsUpdate(Consumer<SpaceSettingsUpdate> spec) {
        super();
        spec.accept(this);
    }

    /**
     * Protected no-args constructor for use by serialization frameworks.
     */
    @ApiStatus.Internal
    protected SpaceSettingsUpdate() {
    }

    /**
     * Constructs a validated instance of {@link SpaceSettingsUpdate}.
     * <p>
     * NOTE: This constructor is not considered stable and may change if the model is updated. Consider using {@link #SpaceSettingsUpdate(Consumer)} instead.
     * @param routeOverrideEnabled Defines whether an override for the space home should be used. This is
used in conjunction with a space theme provided by an app. For
example, if this property is set to true, a theme can display a page
other than the space homepage when users visit the root URL for a
space. This property allows apps to provide content-only theming
without overriding the space home.
     */
    @ApiStatus.Internal
    public SpaceSettingsUpdate(Boolean routeOverrideEnabled) {
        this.routeOverrideEnabled = routeOverrideEnabled;
    }


    /**
     * Fluent getter for routeOverrideEnabled.
     * <p>
     * Defines whether an override for the space home should be used. This is
     * used in conjunction with a space theme provided by an app. For
     * example, if this property is set to true, a theme can display a page
     * other than the space homepage when users visit the root URL for a
     * space. This property allows apps to provide content-only theming
     * without overriding the space home.
     *
     * @return routeOverrideEnabled
     */
    public Boolean routeOverrideEnabled() {
        return this.routeOverrideEnabled;
    }

    /**
     * Fluent setter for routeOverrideEnabled.
     * <p>
     * Defines whether an override for the space home should be used. This is
     * used in conjunction with a space theme provided by an app. For
     * example, if this property is set to true, a theme can display a page
     * other than the space homepage when users visit the root URL for a
     * space. This property allows apps to provide content-only theming
     * without overriding the space home.
     *
     * @param routeOverrideEnabled routeOverrideEnabled
     * @return this
     */
    public SpaceSettingsUpdate routeOverrideEnabled(Boolean routeOverrideEnabled) {
        this.routeOverrideEnabled = routeOverrideEnabled;
        return this;
    }

    /**
     * Gets the value of routeOverrideEnabled.
     * <p>
     * Defines whether an override for the space home should be used. This is
     * used in conjunction with a space theme provided by an app. For
     * example, if this property is set to true, a theme can display a page
     * other than the space homepage when users visit the root URL for a
     * space. This property allows apps to provide content-only theming
     * without overriding the space home.
     *
     * @return routeOverrideEnabled
     */
    @JsonProperty("routeOverrideEnabled")
    public Boolean getRouteOverrideEnabled() {
        return this.routeOverrideEnabled;
    }

    /**
     * Sets the value of routeOverrideEnabled.
     * <p>
     * Defines whether an override for the space home should be used. This is
     * used in conjunction with a space theme provided by an app. For
     * example, if this property is set to true, a theme can display a page
     * other than the space homepage when users visit the root URL for a
     * space. This property allows apps to provide content-only theming
     * without overriding the space home.
     *
     * @param routeOverrideEnabled routeOverrideEnabled
     */
    public void setRouteOverrideEnabled(Boolean routeOverrideEnabled) {
        this.routeOverrideEnabled = routeOverrideEnabled;
    }

    @Override
    public boolean equals(Object o) {
        if (this == o) return true;
        if (o == null || getClass() != o.getClass()) return false;
        SpaceSettingsUpdate that = (SpaceSettingsUpdate) o;
        return
            Objects.equals(this.routeOverrideEnabled, that.routeOverrideEnabled);
    }

    @Override
    public int hashCode() {
        return Objects.hash(
            this.routeOverrideEnabled
        );
    }

    @Override
    public String toString() {
        return "SpaceSettingsUpdate{" +
            "routeOverrideEnabled=" + routeOverrideEnabled +
            "}";
    }
}
