// WARNING: This file was generated by PrimeCodeGen. DO NOT EDIT.

package io.github.primelib.confluence4j.rest.v1.models;

import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;
import com.fasterxml.jackson.annotation.JsonTypeName;
import java.util.Objects;
import java.util.function.Consumer;
import javax.annotation.processing.Generated;
import org.jetbrains.annotations.ApiStatus;

/**
 * SpaceSettingsEditor
 *
 */
@JsonTypeName("SpaceSettingsEditor")
@JsonPropertyOrder({
    "page",
    "blogpost",
    "defaultProp"
})
@Generated(value = "io.github.primelib.primecodegen")
public class SpaceSettingsEditor {

    @JsonProperty("page")
    protected String page;

    @JsonProperty("blogpost")
    protected String blogpost;

    @JsonProperty("default")
    protected String defaultProp;

    /**
     * Constructs a validated instance of {@link SpaceSettingsEditor}.
     *
     * @param spec the specification to process
     */
    public SpaceSettingsEditor(Consumer<SpaceSettingsEditor> spec) {
        super();
        spec.accept(this);
    }

    /**
     * Protected no-args constructor for use by serialization frameworks.
     */
    @ApiStatus.Internal
    protected SpaceSettingsEditor() {
    }

    /**
     * Constructs a validated instance of {@link SpaceSettingsEditor}.
     * <p>
     * NOTE: This constructor is not considered stable and may change if the model is updated. Consider using {@link #SpaceSettingsEditor(Consumer)} instead.
     * @param page page
     * @param blogpost blogpost
     * @param defaultProp defaultProp
     */
    @ApiStatus.Internal
    public SpaceSettingsEditor(String page, String blogpost, String defaultProp) {
        this.page = page;
        this.blogpost = blogpost;
        this.defaultProp = defaultProp;
    }


    /**
     * Fluent getter for page.
     *
     * @return page
     */
    public String page() {
        return this.page;
    }

    /**
     * Fluent setter for page.
     *
     * @param page page
     * @return this
     */
    public SpaceSettingsEditor page(String page) {
        this.page = page;
        return this;
    }

    /**
     * Gets the value of page.
     *
     * @return page
     */
    @JsonProperty("page")
    public String getPage() {
        return this.page;
    }

    /**
     * Sets the value of page.
     *
     * @param page page
     */
    public void setPage(String page) {
        this.page = page;
    }
    /**
     * Fluent getter for blogpost.
     *
     * @return blogpost
     */
    public String blogpost() {
        return this.blogpost;
    }

    /**
     * Fluent setter for blogpost.
     *
     * @param blogpost blogpost
     * @return this
     */
    public SpaceSettingsEditor blogpost(String blogpost) {
        this.blogpost = blogpost;
        return this;
    }

    /**
     * Gets the value of blogpost.
     *
     * @return blogpost
     */
    @JsonProperty("blogpost")
    public String getBlogpost() {
        return this.blogpost;
    }

    /**
     * Sets the value of blogpost.
     *
     * @param blogpost blogpost
     */
    public void setBlogpost(String blogpost) {
        this.blogpost = blogpost;
    }
    /**
     * Fluent getter for defaultProp.
     *
     * @return defaultProp
     */
    public String defaultProp() {
        return this.defaultProp;
    }

    /**
     * Fluent setter for defaultProp.
     *
     * @param defaultProp defaultProp
     * @return this
     */
    public SpaceSettingsEditor defaultProp(String defaultProp) {
        this.defaultProp = defaultProp;
        return this;
    }

    /**
     * Gets the value of defaultProp.
     *
     * @return defaultProp
     */
    @JsonProperty("default")
    public String getDefaultProp() {
        return this.defaultProp;
    }

    /**
     * Sets the value of defaultProp.
     *
     * @param defaultProp defaultProp
     */
    public void setDefaultProp(String defaultProp) {
        this.defaultProp = defaultProp;
    }

    @Override
    public boolean equals(Object o) {
        if (this == o) return true;
        if (o == null || getClass() != o.getClass()) return false;
        SpaceSettingsEditor that = (SpaceSettingsEditor) o;
        return
            Objects.equals(this.page, that.page) &&
            Objects.equals(this.blogpost, that.blogpost) &&
            Objects.equals(this.defaultProp, that.defaultProp);
    }

    @Override
    public int hashCode() {
        return Objects.hash(
            this.page, 
            this.blogpost, 
            this.defaultProp
        );
    }

    @Override
    public String toString() {
        return "SpaceSettingsEditor{" +
            "page=" + page + ", " + 
            "blogpost=" + blogpost + ", " + 
            "defaultProp=" + defaultProp +
            "}";
    }
}
