// WARNING: This file was generated by PrimeCodeGen. DO NOT EDIT.

package io.github.primelib.confluence4j.rest.v1.models;

import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;
import com.fasterxml.jackson.annotation.JsonTypeName;
import java.util.Objects;
import java.util.function.Consumer;
import javax.annotation.processing.Generated;
import org.jetbrains.annotations.ApiStatus;

/**
 * SpaceMetadata
 *
 */
@JsonTypeName("SpaceMetadata")
@JsonPropertyOrder({
    "labels",
    "additionalExpandable"
})
@Generated(value = "io.github.primelib.primecodegen")
public class SpaceMetadata {

    @JsonProperty("labels")
    protected LabelArray labels;

    @JsonProperty("_expandable")
    protected Object additionalExpandable;

    /**
     * Constructs a validated instance of {@link SpaceMetadata}.
     *
     * @param spec the specification to process
     */
    public SpaceMetadata(Consumer<SpaceMetadata> spec) {
        super();
        spec.accept(this);
    }

    /**
     * Protected no-args constructor for use by serialization frameworks.
     */
    @ApiStatus.Internal
    protected SpaceMetadata() {
    }

    /**
     * Constructs a validated instance of {@link SpaceMetadata}.
     * <p>
     * NOTE: This constructor is not considered stable and may change if the model is updated. Consider using {@link #SpaceMetadata(Consumer)} instead.
     * @param labels labels
     * @param additionalExpandable additionalExpandable
     */
    @ApiStatus.Internal
    public SpaceMetadata(LabelArray labels, Object additionalExpandable) {
        this.labels = labels;
        this.additionalExpandable = additionalExpandable;
    }


    /**
     * Fluent getter for labels.
     *
     * @return labels
     */
    public LabelArray labels() {
        return this.labels;
    }

    /**
     * Fluent setter for labels.
     *
     * @param labels labels
     * @return this
     */
    public SpaceMetadata labels(LabelArray labels) {
        this.labels = labels;
        return this;
    }

    /**
     * Gets the value of labels.
     *
     * @return labels
     */
    @JsonProperty("labels")
    public LabelArray getLabels() {
        return this.labels;
    }

    /**
     * Sets the value of labels.
     *
     * @param labels labels
     */
    public void setLabels(LabelArray labels) {
        this.labels = labels;
    }
    /**
     * Fluent getter for additionalExpandable.
     *
     * @return additionalExpandable
     */
    public Object additionalExpandable() {
        return this.additionalExpandable;
    }

    /**
     * Fluent setter for additionalExpandable.
     *
     * @param additionalExpandable additionalExpandable
     * @return this
     */
    public SpaceMetadata additionalExpandable(Object additionalExpandable) {
        this.additionalExpandable = additionalExpandable;
        return this;
    }

    /**
     * Gets the value of additionalExpandable.
     *
     * @return additionalExpandable
     */
    @JsonProperty("_expandable")
    public Object getAdditionalExpandable() {
        return this.additionalExpandable;
    }

    /**
     * Sets the value of additionalExpandable.
     *
     * @param additionalExpandable additionalExpandable
     */
    public void setAdditionalExpandable(Object additionalExpandable) {
        this.additionalExpandable = additionalExpandable;
    }

    @Override
    public boolean equals(Object o) {
        if (this == o) return true;
        if (o == null || getClass() != o.getClass()) return false;
        SpaceMetadata that = (SpaceMetadata) o;
        return
            Objects.equals(this.labels, that.labels) &&
            Objects.equals(this.additionalExpandable, that.additionalExpandable);
    }

    @Override
    public int hashCode() {
        return Objects.hash(
            this.labels, 
            this.additionalExpandable
        );
    }

    @Override
    public String toString() {
        return "SpaceMetadata{" +
            "labels=" + labels + ", " + 
            "additionalExpandable=" + additionalExpandable +
            "}";
    }
}
