// WARNING: This file was generated by PrimeCodeGen. DO NOT EDIT.

package io.github.primelib.confluence4j.rest.v1.models;

import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;
import com.fasterxml.jackson.annotation.JsonTypeName;
import java.util.List;
import java.util.Objects;
import java.util.function.Consumer;
import javax.annotation.processing.Generated;
import org.jetbrains.annotations.ApiStatus;

/**
 * SpacePermissionSubjectsGroup
 *
 */
@JsonTypeName("SpacePermissionSubjectsGroup")
@JsonPropertyOrder({
    "results",
    "size",
    "start",
    "limit"
})
@Generated(value = "io.github.primelib.primecodegen")
public class SpacePermissionSubjectsGroup {

    @JsonProperty("results")
    protected List<Group> results;

    @JsonProperty("size")
    protected Integer size;

    @JsonProperty("start")
    protected Integer start;

    @JsonProperty("limit")
    protected Integer limit;

    /**
     * Constructs a validated instance of {@link SpacePermissionSubjectsGroup}.
     *
     * @param spec the specification to process
     */
    public SpacePermissionSubjectsGroup(Consumer<SpacePermissionSubjectsGroup> spec) {
        super();
        spec.accept(this);
    }

    /**
     * Protected no-args constructor for use by serialization frameworks.
     */
    @ApiStatus.Internal
    protected SpacePermissionSubjectsGroup() {
    }

    /**
     * Constructs a validated instance of {@link SpacePermissionSubjectsGroup}.
     * <p>
     * NOTE: This constructor is not considered stable and may change if the model is updated. Consider using {@link #SpacePermissionSubjectsGroup(Consumer)} instead.
     * @param results results
     * @param size size
     * @param start start
     * @param limit limit
     */
    @ApiStatus.Internal
    public SpacePermissionSubjectsGroup(List<Group> results, Integer size, Integer start, Integer limit) {
        this.results = results;
        this.size = size;
        this.start = start;
        this.limit = limit;
    }


    /**
     * Fluent getter for results.
     *
     * @return results
     */
    public List<Group> results() {
        return this.results;
    }

    /**
     * Fluent setter for results.
     *
     * @param results results
     * @return this
     */
    public SpacePermissionSubjectsGroup results(List<Group> results) {
        this.results = results;
        return this;
    }

    /**
     * Gets the value of results.
     *
     * @return results
     */
    @JsonProperty("results")
    public List<Group> getResults() {
        return this.results;
    }

    /**
     * Sets the value of results.
     *
     * @param results results
     */
    public void setResults(List<Group> results) {
        this.results = results;
    }
    /**
     * Fluent getter for size.
     *
     * @return size
     */
    public Integer size() {
        return this.size;
    }

    /**
     * Fluent setter for size.
     *
     * @param size size
     * @return this
     */
    public SpacePermissionSubjectsGroup size(Integer size) {
        this.size = size;
        return this;
    }

    /**
     * Gets the value of size.
     *
     * @return size
     */
    @JsonProperty("size")
    public Integer getSize() {
        return this.size;
    }

    /**
     * Sets the value of size.
     *
     * @param size size
     */
    public void setSize(Integer size) {
        this.size = size;
    }
    /**
     * Fluent getter for start.
     *
     * @return start
     */
    public Integer start() {
        return this.start;
    }

    /**
     * Fluent setter for start.
     *
     * @param start start
     * @return this
     */
    public SpacePermissionSubjectsGroup start(Integer start) {
        this.start = start;
        return this;
    }

    /**
     * Gets the value of start.
     *
     * @return start
     */
    @JsonProperty("start")
    public Integer getStart() {
        return this.start;
    }

    /**
     * Sets the value of start.
     *
     * @param start start
     */
    public void setStart(Integer start) {
        this.start = start;
    }
    /**
     * Fluent getter for limit.
     *
     * @return limit
     */
    public Integer limit() {
        return this.limit;
    }

    /**
     * Fluent setter for limit.
     *
     * @param limit limit
     * @return this
     */
    public SpacePermissionSubjectsGroup limit(Integer limit) {
        this.limit = limit;
        return this;
    }

    /**
     * Gets the value of limit.
     *
     * @return limit
     */
    @JsonProperty("limit")
    public Integer getLimit() {
        return this.limit;
    }

    /**
     * Sets the value of limit.
     *
     * @param limit limit
     */
    public void setLimit(Integer limit) {
        this.limit = limit;
    }

    @Override
    public boolean equals(Object o) {
        if (this == o) return true;
        if (o == null || getClass() != o.getClass()) return false;
        SpacePermissionSubjectsGroup that = (SpacePermissionSubjectsGroup) o;
        return
            Objects.equals(this.results, that.results) &&
            Objects.equals(this.size, that.size) &&
            Objects.equals(this.start, that.start) &&
            Objects.equals(this.limit, that.limit);
    }

    @Override
    public int hashCode() {
        return Objects.hash(
            this.results, 
            this.size, 
            this.start, 
            this.limit
        );
    }

    @Override
    public String toString() {
        return "SpacePermissionSubjectsGroup{" +
            "results=" + results + ", " + 
            "size=" + size + ", " + 
            "start=" + start + ", " + 
            "limit=" + limit +
            "}";
    }
}
