// WARNING: This file was generated by PrimeCodeGen. DO NOT EDIT.

package io.github.primelib.confluence4j.rest.v1.models;

import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;
import com.fasterxml.jackson.annotation.JsonTypeName;
import java.util.Map;
import java.util.Objects;
import java.util.function.Consumer;
import javax.annotation.processing.Generated;
import org.jetbrains.annotations.ApiStatus;

/**
 * TargetDescription
 *
 */
@JsonTypeName("TargetDescription")
@JsonPropertyOrder({
    "plain",
    "view",
    "additionalExpandable"
})
@Generated(value = "io.github.primelib.primecodegen")
public class TargetDescription {

    @JsonProperty("plain")
    protected Map<String, Object> plain;

    @JsonProperty("view")
    protected Map<String, Object> view;

    @JsonProperty("_expandable")
    protected TargetDescriptionExpandable additionalExpandable;

    /**
     * Constructs a validated instance of {@link TargetDescription}.
     *
     * @param spec the specification to process
     */
    public TargetDescription(Consumer<TargetDescription> spec) {
        super();
        spec.accept(this);
    }

    /**
     * Protected no-args constructor for use by serialization frameworks.
     */
    @ApiStatus.Internal
    protected TargetDescription() {
    }

    /**
     * Constructs a validated instance of {@link TargetDescription}.
     * <p>
     * NOTE: This constructor is not considered stable and may change if the model is updated. Consider using {@link #TargetDescription(Consumer)} instead.
     * @param plain plain
     * @param view view
     * @param additionalExpandable additionalExpandable
     */
    @ApiStatus.Internal
    public TargetDescription(Map<String, Object> plain, Map<String, Object> view, TargetDescriptionExpandable additionalExpandable) {
        this.plain = plain;
        this.view = view;
        this.additionalExpandable = additionalExpandable;
    }


    /**
     * Fluent getter for plain.
     *
     * @return plain
     */
    public Map<String, Object> plain() {
        return this.plain;
    }

    /**
     * Fluent setter for plain.
     *
     * @param plain plain
     * @return this
     */
    public TargetDescription plain(Map<String, Object> plain) {
        this.plain = plain;
        return this;
    }

    /**
     * Gets the value of plain.
     *
     * @return plain
     */
    @JsonProperty("plain")
    public Map<String, Object> getPlain() {
        return this.plain;
    }

    /**
     * Sets the value of plain.
     *
     * @param plain plain
     */
    public void setPlain(Map<String, Object> plain) {
        this.plain = plain;
    }
    /**
     * Fluent getter for view.
     *
     * @return view
     */
    public Map<String, Object> view() {
        return this.view;
    }

    /**
     * Fluent setter for view.
     *
     * @param view view
     * @return this
     */
    public TargetDescription view(Map<String, Object> view) {
        this.view = view;
        return this;
    }

    /**
     * Gets the value of view.
     *
     * @return view
     */
    @JsonProperty("view")
    public Map<String, Object> getView() {
        return this.view;
    }

    /**
     * Sets the value of view.
     *
     * @param view view
     */
    public void setView(Map<String, Object> view) {
        this.view = view;
    }
    /**
     * Fluent getter for additionalExpandable.
     *
     * @return additionalExpandable
     */
    public TargetDescriptionExpandable additionalExpandable() {
        return this.additionalExpandable;
    }

    /**
     * Fluent setter for additionalExpandable.
     *
     * @param additionalExpandable additionalExpandable
     * @return this
     */
    public TargetDescription additionalExpandable(TargetDescriptionExpandable additionalExpandable) {
        this.additionalExpandable = additionalExpandable;
        return this;
    }

    /**
     * Gets the value of additionalExpandable.
     *
     * @return additionalExpandable
     */
    @JsonProperty("_expandable")
    public TargetDescriptionExpandable getAdditionalExpandable() {
        return this.additionalExpandable;
    }

    /**
     * Sets the value of additionalExpandable.
     *
     * @param additionalExpandable additionalExpandable
     */
    public void setAdditionalExpandable(TargetDescriptionExpandable additionalExpandable) {
        this.additionalExpandable = additionalExpandable;
    }

    @Override
    public boolean equals(Object o) {
        if (this == o) return true;
        if (o == null || getClass() != o.getClass()) return false;
        TargetDescription that = (TargetDescription) o;
        return
            Objects.equals(this.plain, that.plain) &&
            Objects.equals(this.view, that.view) &&
            Objects.equals(this.additionalExpandable, that.additionalExpandable);
    }

    @Override
    public int hashCode() {
        return Objects.hash(
            this.plain, 
            this.view, 
            this.additionalExpandable
        );
    }

    @Override
    public String toString() {
        return "TargetDescription{" +
            "plain=" + plain + ", " + 
            "view=" + view + ", " + 
            "additionalExpandable=" + additionalExpandable +
            "}";
    }
}
