// WARNING: This file was generated by PrimeCodeGen. DO NOT EDIT.

package io.github.primelib.confluence4j.rest.v1.models;

import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;
import com.fasterxml.jackson.annotation.JsonTypeName;
import java.util.Map;
import java.util.Objects;
import java.util.function.Consumer;
import javax.annotation.processing.Generated;
import org.jetbrains.annotations.ApiStatus;

/**
 * WebResourceDependenciesTags
 *
 */
@JsonTypeName("WebResourceDependenciesTags")
@JsonPropertyOrder({
    "all",
    "css",
    "data",
    "js",
    "additionalExpandable"
})
@Generated(value = "io.github.primelib.primecodegen")
public class WebResourceDependenciesTags {

    @JsonProperty("all")
    protected String all;

    @JsonProperty("css")
    protected String css;

    @JsonProperty("data")
    protected String data;

    @JsonProperty("js")
    protected String js;

    @JsonProperty("_expandable")
    protected Map<String, Object> additionalExpandable;

    /**
     * Constructs a validated instance of {@link WebResourceDependenciesTags}.
     *
     * @param spec the specification to process
     */
    public WebResourceDependenciesTags(Consumer<WebResourceDependenciesTags> spec) {
        super();
        spec.accept(this);
    }

    /**
     * Protected no-args constructor for use by serialization frameworks.
     */
    @ApiStatus.Internal
    protected WebResourceDependenciesTags() {
    }

    /**
     * Constructs a validated instance of {@link WebResourceDependenciesTags}.
     * <p>
     * NOTE: This constructor is not considered stable and may change if the model is updated. Consider using {@link #WebResourceDependenciesTags(Consumer)} instead.
     * @param all all
     * @param css css
     * @param data data
     * @param js js
     * @param additionalExpandable additionalExpandable
     */
    @ApiStatus.Internal
    public WebResourceDependenciesTags(String all, String css, String data, String js, Map<String, Object> additionalExpandable) {
        this.all = all;
        this.css = css;
        this.data = data;
        this.js = js;
        this.additionalExpandable = additionalExpandable;
    }


    /**
     * Fluent getter for all.
     *
     * @return all
     */
    public String all() {
        return this.all;
    }

    /**
     * Fluent setter for all.
     *
     * @param all all
     * @return this
     */
    public WebResourceDependenciesTags all(String all) {
        this.all = all;
        return this;
    }

    /**
     * Gets the value of all.
     *
     * @return all
     */
    @JsonProperty("all")
    public String getAll() {
        return this.all;
    }

    /**
     * Sets the value of all.
     *
     * @param all all
     */
    public void setAll(String all) {
        this.all = all;
    }
    /**
     * Fluent getter for css.
     *
     * @return css
     */
    public String css() {
        return this.css;
    }

    /**
     * Fluent setter for css.
     *
     * @param css css
     * @return this
     */
    public WebResourceDependenciesTags css(String css) {
        this.css = css;
        return this;
    }

    /**
     * Gets the value of css.
     *
     * @return css
     */
    @JsonProperty("css")
    public String getCss() {
        return this.css;
    }

    /**
     * Sets the value of css.
     *
     * @param css css
     */
    public void setCss(String css) {
        this.css = css;
    }
    /**
     * Fluent getter for data.
     *
     * @return data
     */
    public String data() {
        return this.data;
    }

    /**
     * Fluent setter for data.
     *
     * @param data data
     * @return this
     */
    public WebResourceDependenciesTags data(String data) {
        this.data = data;
        return this;
    }

    /**
     * Gets the value of data.
     *
     * @return data
     */
    @JsonProperty("data")
    public String getData() {
        return this.data;
    }

    /**
     * Sets the value of data.
     *
     * @param data data
     */
    public void setData(String data) {
        this.data = data;
    }
    /**
     * Fluent getter for js.
     *
     * @return js
     */
    public String js() {
        return this.js;
    }

    /**
     * Fluent setter for js.
     *
     * @param js js
     * @return this
     */
    public WebResourceDependenciesTags js(String js) {
        this.js = js;
        return this;
    }

    /**
     * Gets the value of js.
     *
     * @return js
     */
    @JsonProperty("js")
    public String getJs() {
        return this.js;
    }

    /**
     * Sets the value of js.
     *
     * @param js js
     */
    public void setJs(String js) {
        this.js = js;
    }
    /**
     * Fluent getter for additionalExpandable.
     *
     * @return additionalExpandable
     */
    public Map<String, Object> additionalExpandable() {
        return this.additionalExpandable;
    }

    /**
     * Fluent setter for additionalExpandable.
     *
     * @param additionalExpandable additionalExpandable
     * @return this
     */
    public WebResourceDependenciesTags additionalExpandable(Map<String, Object> additionalExpandable) {
        this.additionalExpandable = additionalExpandable;
        return this;
    }

    /**
     * Gets the value of additionalExpandable.
     *
     * @return additionalExpandable
     */
    @JsonProperty("_expandable")
    public Map<String, Object> getAdditionalExpandable() {
        return this.additionalExpandable;
    }

    /**
     * Sets the value of additionalExpandable.
     *
     * @param additionalExpandable additionalExpandable
     */
    public void setAdditionalExpandable(Map<String, Object> additionalExpandable) {
        this.additionalExpandable = additionalExpandable;
    }

    @Override
    public boolean equals(Object o) {
        if (this == o) return true;
        if (o == null || getClass() != o.getClass()) return false;
        WebResourceDependenciesTags that = (WebResourceDependenciesTags) o;
        return
            Objects.equals(this.all, that.all) &&
            Objects.equals(this.css, that.css) &&
            Objects.equals(this.data, that.data) &&
            Objects.equals(this.js, that.js) &&
            Objects.equals(this.additionalExpandable, that.additionalExpandable);
    }

    @Override
    public int hashCode() {
        return Objects.hash(
            this.all, 
            this.css, 
            this.data, 
            this.js, 
            this.additionalExpandable
        );
    }

    @Override
    public String toString() {
        return "WebResourceDependenciesTags{" +
            "all=" + all + ", " + 
            "css=" + css + ", " + 
            "data=" + data + ", " + 
            "js=" + js + ", " + 
            "additionalExpandable=" + additionalExpandable +
            "}";
    }
}
