// WARNING: This file was generated by PrimeCodeGen. DO NOT EDIT.

package io.github.primelib.confluence4j.rest.v1.client;

import feign.Headers;
import feign.Param;
import feign.RequestLine;
import io.github.primelib.confluence4j.rest.v1.models.SpaceSettings;
import io.github.primelib.confluence4j.rest.v1.models.SpaceSettingsUpdate;
import javax.annotation.processing.Generated;
import org.jetbrains.annotations.NotNull;

/**
 * ConfluenceClientSpaceSettingsApi
 */
@Generated(value = "io.github.primelib.primecodegen")
public interface ConfluenceClientSpaceSettingsApi {

    /**
     * GetSpaceBySpaceKeySettingsV1
     * Get space settings
     * Returns the settings of a space. Currently only the
    * `routeOverrideEnabled` setting can be returned.
    * 
    * **[Permissions](https://confluence.atlassian.com/x/_AozKw) required**:
    * 'View' permission for the space.
     *
     * API Method: GET /rest/api/space/{spaceKey}/settings
     *
     * @param spaceKey The key of the space to be queried for its settings.
     */
    @RequestLine("GET /rest/api/space/{spaceKey}/settings")
    @Headers({
        "Accept: application/json"
    })
    SpaceSettings getSpaceBySpaceKeySettingsV1(
            @NotNull @Param("spaceKey") String spaceKey
    );

    /**
     * PutSpaceBySpaceKeySettingsV1
     * Update space settings
     * Updates the settings for a space. Currently only the
    * `routeOverrideEnabled` setting can be updated.
    * 
    * **[Permissions](https://confluence.atlassian.com/x/_AozKw) required**:
    * 'Admin' permission for the space.
     *
     * API Method: PUT /rest/api/space/{spaceKey}/settings
     *
     * @param spaceKey The key of the space whose settings will be updated.
     * @param payload The space settings to update.
     */
    @RequestLine("PUT /rest/api/space/{spaceKey}/settings")
    @Headers({
        "Content-Type: application/json",
        "Accept: application/json"
    })
    SpaceSettings putSpaceBySpaceKeySettingsV1(
            @NotNull @Param("spaceKey") String spaceKey,
            @NotNull SpaceSettingsUpdate payload
    );

}
