// WARNING: This file was generated by PrimeCodeGen. DO NOT EDIT.

package io.github.primelib.confluence4j.rest.v1.client;

import io.github.primelib.confluence4j.rest.v1.models.AuditRecord;
import io.github.primelib.confluence4j.rest.v1.models.AuditRecordArray;
import io.github.primelib.confluence4j.rest.v1.models.RetentionPeriod;
import io.github.primelib.confluence4j.rest.v1.operations.GetAuditExportV1OperationSpec;
import io.github.primelib.confluence4j.rest.v1.operations.GetAuditRetentionV1OperationSpec;
import io.github.primelib.confluence4j.rest.v1.operations.GetAuditSinceV1OperationSpec;
import io.github.primelib.confluence4j.rest.v1.operations.GetAuditV1OperationSpec;
import io.github.primelib.confluence4j.rest.v1.operations.PostAuditV1OperationSpec;
import io.github.primelib.confluence4j.rest.v1.operations.PutAuditRetentionV1OperationSpec;
import java.util.function.Consumer;
import javax.annotation.processing.Generated;

/**
 * ConfluenceClientAuditConsumerApi
 */
@Generated(value = "io.github.primelib.primecodegen")
public class ConfluenceClientAuditConsumerApi {
    private final ConfluenceClientAuditApi api;

    public ConfluenceClientAuditConsumerApi(ConfluenceClientAuditApi api) {
        this.api = api;
    }


    /**
     * GetAuditV1
     * Get audit records
     * Returns all records in the audit log, optionally for a certain date range.
    * This contains information about events like space exports, group membership
    * changes, app installations, etc. For more information, see
    * [Audit log](https://confluence.atlassian.com/confcloud/audit-log-802164269.html)
    * in the Confluence administrator's guide.
    * 
    * **[Permissions](https://confluence.atlassian.com/x/_AozKw) required**:
    * 'Confluence Administrator' global permission.
     *
     * API Method: GET /rest/api/audit
     *
     * @param spec a consumer that creates the payload for this operation. Supports the following properties:
     * <ul>
     *   <li>startDate: Filters the results to the records on or after the `startDate`. The `startDate` must be specified as [epoch time](https://www.epochconverter.com/) in milliseconds.</li>
     *   <li>endDate: Filters the results to the records on or before the `endDate`. The `endDate` must be specified as [epoch time](https://www.epochconverter.com/) in milliseconds.</li>
     *   <li>searchString: Filters the results to records that have string property values matching the `searchString`.</li>
     *   <li>start: The starting index of the returned records.</li>
     *   <li>limit: The maximum number of records to return per page. Note, this may be restricted by fixed system limits.</li>
     * </ul>
     */
    public AuditRecordArray getAuditV1(Consumer<GetAuditV1OperationSpec> spec) {
        GetAuditV1OperationSpec r = new GetAuditV1OperationSpec(spec);
        return api.getAuditV1(r.startDate(), r.endDate(), r.searchString(), r.start(), r.limit());
    }

    /**
     * PostAuditV1
     * Create audit record
     * Creates a record in the audit log.
    * 
    * **[Permissions](https://confluence.atlassian.com/x/_AozKw) required**:
    * 'Confluence Administrator' global permission.
     *
     * API Method: POST /rest/api/audit
     *
     * @param spec a consumer that creates the payload for this operation. Supports the following properties:
     * <ul>
     *   <li>payload: The record to be created in the audit log.</li>
     * </ul>
     */
    public AuditRecord postAuditV1(Consumer<PostAuditV1OperationSpec> spec) {
        PostAuditV1OperationSpec r = new PostAuditV1OperationSpec(spec);
        return api.postAuditV1(r.payload());
    }

    /**
     * GetAuditExportV1
     * Export audit records
     * Exports audit records as a CSV file or ZIP file.
    * 
    * **[Permissions](https://confluence.atlassian.com/x/_AozKw) required**:
    * 'Confluence Administrator' global permission.
     *
     * API Method: GET /rest/api/audit/export
     *
     * @param spec a consumer that creates the payload for this operation. Supports the following properties:
     * <ul>
     *   <li>startDate: Filters the exported results to the records on or after the `startDate`. The `startDate` must be specified as [epoch time](https://www.epochconverter.com/) in milliseconds.</li>
     *   <li>endDate: Filters the exported results to the records on or before the `endDate`. The `endDate` must be specified as [epoch time](https://www.epochconverter.com/) in milliseconds.</li>
     *   <li>searchString: Filters the exported results to records that have string property values matching the `searchString`.</li>
     *   <li>format: The format of the export file for the audit records.</li>
     * </ul>
     */
    public Byte[] getAuditExportV1(Consumer<GetAuditExportV1OperationSpec> spec) {
        GetAuditExportV1OperationSpec r = new GetAuditExportV1OperationSpec(spec);
        return api.getAuditExportV1(r.startDate(), r.endDate(), r.searchString(), r.format());
    }

    /**
     * GetAuditRetentionV1
     * Get retention period
     * Returns the retention period for records in the audit log. The retention
    * period is how long an audit record is kept for, from creation date until
    * it is deleted.
    * 
    * **[Permissions](https://confluence.atlassian.com/x/_AozKw) required**:
    * 'Confluence Administrator' global permission.
     *
     * API Method: GET /rest/api/audit/retention
     *
     */
    public RetentionPeriod getAuditRetentionV1(Consumer<GetAuditRetentionV1OperationSpec> spec) {
        GetAuditRetentionV1OperationSpec r = new GetAuditRetentionV1OperationSpec(spec);
        return api.getAuditRetentionV1();
    }

    /**
     * PutAuditRetentionV1
     * Set retention period
     * Sets the retention period for records in the audit log. The retention period
    * can be set to a maximum of 1 year.
    * 
    * **[Permissions](https://confluence.atlassian.com/x/_AozKw) required**:
    * 'Confluence Administrator' global permission.
     *
     * API Method: PUT /rest/api/audit/retention
     *
     * @param spec a consumer that creates the payload for this operation. Supports the following properties:
     * <ul>
     *   <li>payload: The updated retention period.</li>
     * </ul>
     */
    public RetentionPeriod putAuditRetentionV1(Consumer<PutAuditRetentionV1OperationSpec> spec) {
        PutAuditRetentionV1OperationSpec r = new PutAuditRetentionV1OperationSpec(spec);
        return api.putAuditRetentionV1(r.payload());
    }

    /**
     * GetAuditSinceV1
     * Get audit records for time period
     * Returns records from the audit log, for a time period back from the current
    * date. For example, you can use this method to get the last 3 months of records.
    * 
    * This contains information about events like space exports, group membership
    * changes, app installations, etc. For more information, see
    * [Audit log](https://confluence.atlassian.com/confcloud/audit-log-802164269.html)
    * in the Confluence administrator's guide.
    * 
    * **[Permissions](https://confluence.atlassian.com/x/_AozKw) required**:
    * 'Confluence Administrator' global permission.
     *
     * API Method: GET /rest/api/audit/since
     *
     * @param spec a consumer that creates the payload for this operation. Supports the following properties:
     * <ul>
     *   <li>number: The number of units for the time period.</li>
     *   <li>units: The unit of time that the time period is measured in.</li>
     *   <li>searchString: Filters the results to records that have string property values matching the `searchString`.</li>
     *   <li>start: The starting index of the returned records.</li>
     *   <li>limit: The maximum number of records to return per page. Note, this may be restricted by fixed system limits.</li>
     * </ul>
     */
    public AuditRecordArray getAuditSinceV1(Consumer<GetAuditSinceV1OperationSpec> spec) {
        GetAuditSinceV1OperationSpec r = new GetAuditSinceV1OperationSpec(spec);
        return api.getAuditSinceV1(r.number(), r.units(), r.searchString(), r.start(), r.limit());
    }

}
